### ISSUE TITLE
Very slow performance messagelog pages

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#1052]
**Describe the bug**
I have an Ibis with approximately 8 million messages in the ibisstore table, and opening the messagelog of an adapter/sender takes a long time to display messages. Messagelogs with a small number of messages load faster than with large numbers of messages.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Open the messagelog for an adapter with a lot of messages
2. Wait very long
3. Get results

**Expected behavior**
Not taking as long as it is now.

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WebSphere 8.5
- Database: MSSQL
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.5-RC3

**Additional context**
N/A

**Comment by ricardovh** [comment]
Possibly related to #1004?

**Comment by gvanbrakel** [comment]
The long delay is due to the method that is deployed for the browsing of the messagelog: the list of all messages (excluding the contents) is read into memory. 
I would not consider this behavior to be a bug.

**Comment by ricardovh** [comment]
Some of the messagelogs contain over 2 million messages, the time it takes reading them all into memory makes the messagelog almost useless. After the initial load it works really fast, but it takes too long to get there. 

If this is not a bug, I would consider this a feature request to look into ways to increase loading speed. I think there should be some kind of limit on how much is loaded into memory. That might impact search and sorting speed, as those need to go round to the database to query all data, but I think that outweighs the load time of the current situation.

**Comment by nielsm5** [comment]
https://github.com/frankframework/frankframework/issues/7089 is probably relevant here. We're reworking the console endpoints to further improve the performance.
