### ISSUE TITLE
Logout button not shown when logging in via 401 pop-up

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#1232]
**Describe the bug**
When going directly to the console (for example, /iaf/gui/#!/status), no logout option appears in the console. When logging in via /iaf/gui/#!/login the logout option does appear.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Go to the console via /iaf/gui/#!/status
2. Log in with your credentials
3. No logout option appears
4. Force a logout by manually browsing to /iaf/gui/#!/logout (this should also place you at /iaf/gui/#!/login)
5. Log in with your credentials
6. The logout option now is present
7. Open a new tab and go to /iaf/gui/#!/status
8. Logout option is gone again

**Expected behavior**
The logout to also be available when not entering the console using the login screen

**Screenshots**
N/A

**Environment:**
 - Application server (f.e. Tomcat/WebSphere/JBOSS/Jetty): WbSphere
 - Browser [e.g. chrome, safari]: Chrome
 - IAF Version [e.g. 7.5 RC3, 7.6]: 7.6-20201030.100621

**Additional context**
N/A

**Comment by nielsm5** [comment]
You can now logout via `/logout` behind the servlet path. A frontend change is still required to show the logout button (and potentially cleanup the authservice).
