### ISSUE TITLE
Feature Request: JavaListener expected session keys attribute

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#1286]
**Reporter**
Ricardo

**Is your feature request related to a problem? Please describe.**
When using multiple adapters to process a message, sometimes it is needed to move several session keys with the message (counters, temporary values). There is now no way to indicate which sessionkeys are expected, outside of using comments or reading the code. 

**Describe the solution you'd like**
An attribute on the JavaListener to give a list of session keys that calling senders must provide. If the IbisLocalSender does not have all session keys as params in the list, display a warning in the console that not all session keys are provided. Some edge cases might be a problem, like *, so maybe an ignore-option to disable the warning is also required.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tnleeuw** [comment]
I will add this as feature to the FrankListener / FrankSender that are newly added in 8.3
