### ISSUE TITLE
getTokenPipe/sender

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#1373]
**Reporter**
Jeroen Jansen van Rosendaal

**Is your feature request related to a problem? Please describe.**
When a call to an external system is made i would like to have a building block that is wrapped around the http call and will provide me with the requested token.

**Describe the solution you'd like**
Seperate buidling block that can be used for getting different types of tokens 

**Describe alternatives you've considered**
As a work around we do an http call to collect the data

**Additional context**

**Comment by nielsm5** [comment]
What kind of token are we talking about? JWT's?

**Comment by nielsm5** [comment]
Stale, closing
