### ISSUE TITLE
Add receiver times to adapter statistics

### ISSUE THREAD

**Issue by BonnoSmeele** [frankframework/frankframework#1428]
**Reporter**
Bonno Smeele

**Is your feature request related to a problem? Please describe.**
Durations are logged for every pipe which can be seen`by clicking the "more statistics button".
However, statisticsa are not logged for the receivers in the adapter. This leads to discrepancies when calculating throughput from the logfiles. If there are performance problems with the receiver, that might escape notice as well(with query listeners this might be an issue)

**Describe the solution you'd like**
add receiver duration times to the statistics page.
log receiver duration times to log files

**Describe alternatives you've considered**
NA

**Additional context**
https://jira.nn-group.com/browse/DLMI-513

**Comment by jacodg** [comment]
When this is urgent please contact me

**Comment by nielsm5** [comment]
These statistics exist, but are displayed slightly differently for Pulling vs Pushing listeners, and thus how a receiver processes a message.
