### ISSUE TITLE
Stats log uses old interface

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#1477]
**Describe the bug**
When opening the statistics log to view the adapter statistics, the old interface is still used.

**Reporter**
Ricardo

**Category** 
Use following Tags to categorize your bug report
 - Frank Console

**To Reproduce**
1. Go to 'https://ibis4example.ibissource.org/iaf/gui/#!/logging?directory=%2Fopt%2Ftomcat%2Flogs%2Fibis4example&file=ibis4example-stats_2021W07.log'
2. See old-style interface for statistics

**Expected behavior**
To be styled the same as the rest of the GUI.

**Screenshots**
N/A

**Environment:**
 - Application server: [e.g. Tomcat/WebSphere/JBOSS/Jetty]: Tomcat
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]: N/A
 - Browser: [e.g. Chrome, Safari, Edge]: Chrome
 - IAF Version: [e.g. 7.5, 7.6]: 7.6-SNAPSHOT

**Additional context**
N/A

**Comment by jacodg** [comment]
We want to refactor the statistics and not waste effort on styling for now

**Comment by nielsm5** [comment]
Functionality has been removed in #5722.
