### ISSUE TITLE
Improve multiplicity detection in FrankDoc generation

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#1601]
Should fix #2519

**Reporter**
Gerrit

A change in multiplicity of config children is now implemented with a hack in digester-rules.xml and the digester. Should be replaced by something proper.

**Comment by nielsm5** [comment]
Should fix patch #1598

**Comment by jacodg** [comment]
Use annotation instead of digester (probably)

**Comment by nielsm5** [comment]
In the Configuration class are 3 methods (JmsRealms, JmsRealm and MonitorManager) to add them to the Frank!Doc
