### ISSUE TITLE
Base64Pipe attributes convertToString and OutputType should be removed

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#1691]
**Describe the issue**
It should not be necessary to specify attributes 'convertToString'  or 'outputType' .

**Reporter**
Gerrit

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.6-RC2-SNAPSHOT: Ibis4Test
Running on LPZWNL000040524 using Apache Tomcat/9.0.43
Java Version: OpenJDK Runtime Environment (1.8.0_41-b04)
Heap size: 153M, total JVM memory: 247M
Free disk space: 312GB, total disk space: 476GB
Up since: 2021-04-09 11:37:38 (13m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql,PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Solved in #5888
