### ISSUE TITLE
Cleanup script for old or misnamed configurations

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#1931]
**Describe the issue**
Up till version 7.5 (FF! 7.2 to 7.4) it was possible to override the automatically determined name and version of a configuration jar file. This caused many applications to have faulty non-usable configurations that will never be visible in the 'Manage Configurations' page.

**Possible solution**
A possible solution would be to create a new page to display all these 'unused' configurations and notify the user that (s)he should clean up these files from the database.

**Reporter**
Niels Meijer

**Comment by jacodg** [comment]
Also show wrong configurations at 'Manage Configurations' page and option to delete them

**Comment by nielsm5** [comment]
It's old, and harmless. If this applies to somebody it's easier to execute a database statement to clear the faulty blobs in the ibisconfig table.
