### ISSUE TITLE
Open report in Ladybug  test tab gives: An application error has occurred.  Your session has been reset.

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#2309]
**Describe the issue**
When you try to open a report in the test tab of the Ladybug it will give the following error:

An application error has occurred.  Your session has been reset.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Go to https://ibis4example.ibissource.org/iaf/gui/#!/testing/ladybug
2. Go to the Test tab
3. Click on Open (left to /Pipeline HelloWorld)
4. See error: An application error has occurred.  Your session has been reset.

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 422M, total JVM memory: 1102M
Free disk space: 11GB, total disk space: 17GB
Up since: 2021-10-06 15:49:01 (21h)
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
Next time, could you try and download/attach the log file(s) ?
I cannot reproduce this (locally/ibis4example)

**Comment by jacodg** [comment]
Doesn't happen when running Ladybug without IAF
