### ISSUE TITLE
Report names for database scheduled adapters are always Sender AdapterJob

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#2419]
**Describe the issue**
When an adapter is triggered by a scheduler that is stored in the database the report name in Ladybug is always Sender AdapterJob instead of Pipeline \<adapter name>.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Create a scheduler in the database to trigger an adapter with a Java listener
2. See that all reports in the Ladybug for the adapter are called Sender AdapterJob instead of Pipeline \<adapter name>

**Screenshots**

![image](https://user-images.githubusercontent.com/2970084/140773299-0e40960c-8d8b-4a84-8fc6-468fcd19c546.png)

**Configuration**
The configuration for the job is stored in the database (created by adding the job with the Frank!Console Scheduler page) calling the following listener:
```
<listener className="nl.nn.adapterframework.receivers.JavaListener"
                      name="BulkUpdate_UpdateByQuery_QueryIterator"/>
```

**Input**
\-

**Environment**
```
FF! 7.7-20211105.102530: Ibis4Titan 403-3b023912-release7-7
Running on *** using IBM WebSphere Application Server/8.5
Java Version: Java(TM) SE Runtime Environment (8.0.6.25 - pxa6480sr6fp25-20210115_01(SR6 FP25))
Heap size: 1282M, total JVM memory: 1536M
Free disk space: 8GB, total disk space: 10GB
Up since: 2021-11-08 07:46:49 (9h)
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by jacodg** [comment]
I now see it's the same for config file based schedulers:

![image](https://user-images.githubusercontent.com/2970084/140784036-e4233b0d-b833-43ef-a56f-33ee28463587.png)

**Comment by jacodg** [comment]
Is is possible to remove the Sender startpoint and endpoint from the report? So the report would be the same as when created by a listener or test a pipeline? I think this was the case for older versions of F!F

**Comment by nielsm5** [comment]
I think this is because it's now wired through Spring and thus appears in the OAP (pointcut) of the ladybug. The simplest way would be to give this sender a distinctive name, and in the ladybug AOP config check if the senderInputOutput should do something or not...
