### ISSUE TITLE
Solution Approach "The database's default holdability for ResultSet objects is 2 instead of 1"

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#2681]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Ricardo: 
Voor ILS liepen we tegen de warning aan van "The database's default holdability for ResultSet objects is 2 instead of 1", en met de informatie in de code snap ik waar die vandaan komt in mijn adapter (en is niets aan te doen), maar ik snap niet precies wat het nou inhoud en ik kwam in mijn zoektocht tegen dat we die waarde zelf op de connectie kunnen zetten, maar ik kan niet achterhalen waarom we dat niet doen vanuit het framework. Misschien komt het omdat ik niet snap wat het precies doet en wat de impact zou zijn van de waarde op de connectie zetten, en uit de comment bij de warning kan ik het ook niet halen, kan een van jullie dat toelichten?
Gerrit: 
Ik denk dat het inderdaad handig zou zijn om de warning uit te breiden met een (verwijzing naar een)  beschrijving van opties die er zijn. Dat zijn volgens mij:
1)	Als uit analyse blijkt dat er geen transactionaliteitsverschil is tussen hoofd en subadapter, dan wel dat er op TST  en ACC geen DSRA9110E gezien worden, of er niet op WebSphere gedraaid wordt, dan kan door middel van een property de melding onderdrukt worden (Het zou handig zijn als er ook een verwijzing naar die mogelijkheid was)
2)	Als het probleem wel op kan treden, dan kan 
a.	De transactionaliteit van de adapters op elkaar afgestemd worden, of
b.	de resultset holdability dus gezet worden (Is het duidelijk hoe dat kan?)

We zouden ook nog een attribuut aan de ResultSetIteratingPipe toe kunnen voegen om daar specifiek de holdability over commit te forceren.
En er is natuurlijk ook de mogelijkheid om dat default te doen, voor deze pipe, maar dat zou natuurlijk ook problemen op kunnen leveren bij ander databases en/of applicatieservers.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
This is specific for the WebSphere environment, there's not much more we can do other then displaying a warning in te console (which we already do)
