### ISSUE TITLE
Give configurationwarning on unsafe attribute values

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#2727]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I would like to have warnings in the console if unsafe attributes are used. With unsafe attributes, I mean attributes like:
- allowSelfSignedCertificates=true
- verifyHostname=false
- password=not empty

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
A new annotation should be introduced `@UnSafe(String description)` to `commons/../doc`.
ValidateAttributeRule should be adjusted to make use of the new annotation.
Once implemented a Frank!Doc issue should be created to make use of the annotation.
