### ISSUE TITLE
Feature request: possibility to open messagelog and errorstore in a new tab

### ISSUE THREAD

**Issue by laura-dimitra** [frankframework/frankframework#2943]
It would be very nice if the messagelog and errorstorage can be opened in a new tab with ctrl+click or right mouse button.
For errorstore and messagelog this is not possible in the adapter overview page, but individual messages can be opened in a new tab.
It would be very nice if this is possible as well in the adapter overview page.

![messsagelog en errorstore kunnen openen in nieuw tabblad](https://user-images.githubusercontent.com/30295058/160595343-d2f3aa11-9f9d-4524-b76e-7b7c25214842.PNG)

![messsagelog en errorstore kunnen openen in nieuw tabblad 2](https://user-images.githubusercontent.com/30295058/160595365-566e4fa6-ee2f-439c-85aa-0b1bfcb53e03.PNG)

**Comment by Matthbo** [comment]
closing this as this request is already being handled in #1418
