### ISSUE TITLE
Add feature to the pattern attribute to reference the input message

### ISSUE THREAD

**Issue by lenardvandermaas** [frankframework/frankframework#2983]
**Describe the issue**
When using the pattern attribute on a Parameter it can sometimes be useful to reference the input message the same way as you would any sessionKey. To my knowledge, this is currently not possible. I would suggest adding an option to reference the input message by typing `{inputmessage}`.

**Reporter**
Lenard

**Comment by alisihab** [comment]
It is already possible to use the input of the pipe as parameter value by not setting value or sessionKey attribute. For example, 
`<Param name="anyString"/>` 
you may even apply an xpathExpression
`<Param name="anyString" xpathExpression="/root"/>` 

Do you have a specific case which requires the pattern feature?

**Comment by lenardvandermaas** [comment]
I do have a specific use case where this would be useful, but let me first explain why I feel like this would be a good addition to the pattern attribute function:

Any form of this problem could be solved by using the `xpathExpression` attribute, because just like with the pattern attribute, you can concat strings and even reference sessionKeys by specifying them in nested Params. The reason I feel like the xpathExpression shouldn't be a replacement of the pattern attribute is the fact that it is a more costly operation and it is way less readable. Compare the following examples:
```
<Param name="test" xpathExpression="concat('test message session key 1: ', $sessionKey1, ', and input message: ', .)">
	<Param name="sessionKey1" sessionKey="sessionKey1"/>
</Param>
```
```
<Param name="test" pattern="test message session key 1: {sessionKey1}, and input message: {inputMessage}"/>
```

I feel like it's a misuse of xpathExpression to concat strings, the inputMessage and sessionKeys when it could be elegantly solved with my suggestion. I think xpathExpression should either be used for xml operations like selecting subtrees, or for complex string operations using stuff like string length and indexOf.

In my case, I used a SenderSeriesSender to first call another adapter that returned an access_token, which I then wanted to use in a Param in the next sender that would be added to the HTTP request as an header:
```
<SenderPipe name="Request">
	<IbisLocalSender javaListener="GetAccessToken"/>
	<HttpSender name="Request"
		methodType="GET"
		urlParam="urlParam"
		headersParams="Authorization">
		<Param name="urlParam" sessionKey="urlParam"/>
		<Param name="Authorization" xpathExpression="concat('Bearer', access_token)"/>
	</HttpSender>
	<Forward name="success" path="READY"/>
</SenderPipe>
```
Additionally to being an ugly solution, having to use the xpathExpression forced me to return the access token as xml, because the xpathExpression can't handle a non xml string as input. Now I'm aware that this could also be solved by returning the access token in a sessionKey by using the `returnedSessionKeys` attribute on the IbisLocalSender and then referencing the sessionKey in the pattern, but I feel like this is a workaround that shouldn't be necessary.

Additionally, I'm trying to create issues that will help make the framework more intuitive for new users, and I feel like this would definitely be helpful in that regard

**Comment by jjansenvr** [comment]
nice to have

**Comment by nielsm5** [comment]
This should work
```xml
<param pattern="{jeroen} en jaco">
  <param name="jeroen" /> <!-- uses inputmessage -->
</param>
```
jeroen needs to be defined either in or above the param with the pattern.
