### ISSUE TITLE
implement responses multipart for api listener

### ISSUE THREAD

**Issue by BonnoSmeele** [frankframework/frankframework#3018]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I'm using an api listener with a get method.
I would like to be able to return a multipart message for the get request.

I have no big ideas on implementing this but there should probably be a multipart XML sessionkey that is used at the end of the adapter that references file sessionkeys. Something like that.

**Reporter**
Bonno Smeele

NA

**Screenshots**

**Configuration**
			<Receiver 
				name="GetClaimDocumentFileReceiver">
				<ApiListener
					method="GET"
					name="GetClaimDocumentFileListener"
					uriPattern="portfolios/{portfolio_number}/claims/{claim_number}/documents{document_id}/versiondata"
					produces="MULTIPART_FORMDATA"/>

			</Receiver>

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
FF! 7.7-20211015.110538: ibis4salesforce
Running on LPZWNL000013838 using Apache Tomcat/9.0.56
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 185M, total JVM memory: 340M
Free disk space: 11GB, total disk space: 237GB
Up since: 2022-04-07 12:43:22 (1h)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
can we reconsider this as we need this or a workaround  urgently

**Comment by nielsm5** [comment]
Is part of #3288
