### ISSUE TITLE
Make it possible to test with null value

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#3033]
**Describe the issue**
For #3032 I used an ApiListener to test the adapter with a null value. It would be "a nice to have" to be able to use test a pipeline to test with null values.

**Reporter**
Jaco de Groot

**Environment**
```
FF! 7.8-20220407.104516: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 259M, total JVM memory: 614M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-07 17:43:01 (1h) 
```

**Comment by jacodg** [comment]
See https://github.com/ibissource/iaf/issues/2620#issuecomment-1040196511 also

**Comment by nielsm5** [comment]
Allow frontend to send 'null' message in the test-pipeline form, backend should pick this up as a `Message.nullMessage()`.

**Comment by Matthbo** [comment]
I see 2 ways of doing this
- The user has a checkbox that sets the message to `null` and disables the message box
- The user types "null" themselves which the backend checks as an exact value

Which one of the two would make more sense?

**Comment by nielsm5** [comment]
Option 3, an empty field :)
