### ISSUE TITLE
httpsender should be able to use a JWT from a inbound message for authetication against a backend system

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3129]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Passing through the JWT to the backend service

**Reporter**
jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
clients infra is not ready for this feature

**Comment by nielsm5** [comment]
Not sure what this is, but copying headers over can already be done using message context keys.
