### ISSUE TITLE
FrankSender to replace IbisJavaSender and IbisLocalSender

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#3143]
**Describe the issue**
Implement a new sender for calling other code from an adapter: `FrankSender`.

This will replace both IbisJavaSender and IbisLocalSender, to make it clearer how to call other adapters and how to call external software and offer the same features for each.

**Reporter**
Core Team

**Comment by tnleeuw** [comment]
What names for these two?

`IbisJavaSender` -> `JavaServiceSender`,
`IbisLocalSender` -> `SubAdapterSender`?

**Comment by tnleeuw** [comment]
As discussed in the Core meeting of 8-7-2024, the new FrankSender will not have an option to call a regular adapter in a separate thread in synchronous mode. If somebody really needs this functionality, we can consider adding this in the future.

**Comment by tnleeuw** [comment]
I'm thinking:
- `FrankSender` has an option `scope` with values `adapter` or `JVM`. `adapter` calls another adapter, `JVM` calls another application in the same JVM. (@nielsm5 you mentioned an option `remote` but I don't know what that means?).
- Calling another application in same JVM uses the DispatcherManager of the current `IbisJavaSender`. This could happen to be another adapter if that adapter has a `JavaListener`
- Calling another adapter can happen by adapter-name (+configuration-name for adapters in a different configuration). This does not need to go via a JavaListener, I think. The target adapter can be directly invoked (with a new session of course), using method `Adapter.processMessageDirect`. This would save some overhead, and some confusion regarding the extra session that the JavaListener again creates, and the double layering of `returnedSessionKeys` that is now both in the `JavaListener`, and in the caller (`IbisJavaSender` or `IbisLocalSender`), and that works slightly differently in each.
-
