### ISSUE TITLE
Security (MFA) 

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3193]
### Goal

the framework needs to be able to implement MFA and other authorization without being dependent on application server logic 

### Description

By implementing spring security we have a plugable way to implement openid connect, username pwd login and other methods

### Tasks 
Version 7.9:
- [x] #3377
- [x] #5416
- [x] #3495
- [x] Implement inbound connectors (LDAP/openid Connect)

Version 8.0:
- [ ] Implement outbound security connectors (JWT, oauth client flow) 
- [ ] #3045

**Comment by nielsm5** [comment]
Closing this as a sub task exists to fix the HttpSender. All inbound endpoints are using Spring Security.
