### ISSUE TITLE
make narayana work on kubernetes

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3228]
Narayana on K8
Narayana is not fully k8s ready (https://jbossts.blogspot.com/2022/04/narayana-on-cloud-part-1.html)  Wildfly seems to have the solution specific for K8s?

**Comment by jjansenvr** [comment]
add documentation about the way to implement

**Comment by gvanbrakel** [comment]
To make Narayana (and BTM at the same time) work on Kubernetes, an InitContainer need to be configured, that arranges for a proper TMUID and log-directory. The function of the init container is similar to the IbisOnCloud script.
[initialize-transaction-logs.sh](https://github.com/ibissource/iaf/files/9754703/initialize-transaction-logs.sh.txt).

Transaction-Log files are stored on a persistent filesystem, that survives a crash of the container that is using it.
Every instance that starts up gets a directory on this filesystem, that stores its TMUID, its state, and the transaction logs.
At proper shutdown, the state is set to COMPLETED.
At start up, the script searches for state COMPLETED, if found, deletes the corresponding directory.
For other folders:
If the owner of the script does not exist anymore, it tries to take ownership of the folder. It does so by creating a lock file in the folder via 'ln' (ln is an atomic operation).
If the lock is obtained, the ownership can be taken. 
If in the end no ownership of any folder can be taken, a fresh folder is created for this instance
