### ISSUE TITLE
hideRegex does not work with LocalSender

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#3254]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using the hideRegex on a SenderPipe with an IbisLocalSender, the hideRegex does not work.

**Reporter**
Ricardo

**To Reproduce**
1. Start a Frank!Application with the below module
2. Use test a pipeline to send a message to it
3. See the Ladybug that the hideRegex is applied in the subadapter but not the main adapter
4. See the same in the logging

**Screenshots**

**Configuration**
```
<module>	
	<adapter name="Repro">
		<receiver name="Repro">
			<listener name="Repro" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro"
				className="nl.nn.adapterframework.pipes.SenderPipe"
				hideRegex="Test .*">
				<sender className="nl.nn.adapterframework.senders.IbisLocalSender"
					javaListener="Repro-Child"/>
				<forward name="success" path="EXIT"/>
			</pipe>
		</pipeline>
	</adapter>

	<adapter name="Repro-Child">
		<receiver name="Repro-Child">
			<listener name="Repro-Child" className="nl.nn.adapterframework.receivers.JavaListener"/>
		</receiver>	

		<pipeline>
			<exits>
				<exit path="EXIT" state="success"/>
			</exits>

			<pipe name="Repro"
				className="nl.nn.adapterframework.pipes.SenderPipe"
				hideRegex="Test .*">
				<sender className="nl.nn.adapterframework.senders.FixedResultSender"
					returnString="Test hideRegex"/>
				<forward name="success" path="EXIT"/>
			</pipe>
		</pipeline>
	</adapter>
</module>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Did it work in an older version? Which F!F version are you using now?

**Comment by nielsm5** [comment]
Related issue: https://github.com/ibissource/iaf/issues/850

**Comment by tnleeuw** [comment]
Where exactly does the `hideRegex` not work as expected for the sub-adapter? Log lines, or MessageStore/MessageLog?

Why not set the correct `hideRegex` on the subadapter?
