### ISSUE TITLE
Messagelog missing Label column (7.7.1)

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#3442]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When working on a small screen with long data fields, the Label column of a messagelog is not always visible, and it is not possible to scroll that far to the right. Switching to a larger screen does show the label.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.7.1
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Do you think an overflow-x would help? It is difficult to fix this as the table is filled after the it's been rendered.

**Comment by nielsm5** [comment]
This issue appears to be stale so I'm closing this.
