### ISSUE TITLE
Larva on ibis4testiaf fails with 'too many redirects

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#3485]
**Describe the issue**
Larva on ibis4testiaf fails with 'too many redirects'

**Reporter**
Gerrit

**To Reproduce**
1. Go to ibis4testiaf
2. Click on testing -> Larva
4. See error 'xxxx redirected you too many times.'

**Environment**
```
FF! 7.8-20220705.153038: Ibis4Test
Running on xxxx using IBM WebSphere Application Server/9.0.5.10
Java Version: Java(TM) SE Runtime Environment (8.0.7.0 - pxa6480sr7-20211025_01(SR7))
Heap size: 769M, total JVM memory: 1024M
Free disk space: 1GB, total disk space: 2GB
Up since: 2022-07-05 23:20:06 (9h)
```

**Comment by nielsm5** [comment]
https://www.ibm.com/support/pages/javalangstring-getpathinfo-returns-null
