### ISSUE TITLE
Reorganize urls for frontend (loadbalancer),

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3664]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Loadbalancers (ALB) on AWS have a maximum of 5 conditions, due to the fact that the urls are not organized in a structured manner the 5 conditions become a blocking issue.

All GUI urls should be grouped under a central url (f.e. https://frank2example.frankframework.org/iaf/*)

**examples**
https://frank2example.frankframework.org/iaf/gui/
https://frank2example.frankframework.org/larva/index.jsp
https://frank2example.frankframework.org/testtool
https://frank2example.frankframework.org/api/openapi.json?uri=/hello-beautiful-world

All service urls should be available under a single url (f.e. https://frank2example.frankframework.org/api/*)
https://frank2example.frankframework.org/api

**Reporter**
Jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jjansenvr** [comment]
Updated prio, the AWS limitation does not allow us to use all functionality of the framework
Jaco made a pull request to move the ladybug under the iaf endpoint (https://github.com/ibissource/iaf/pull/3782)

**Comment by jjansenvr** [comment]
workaround is setting the endpoint url for a servlet by using a property
f.e. 
servlet.LarvaServlet.urlMapping=/iaf/larva/* 
this will allow you to map servlets to better organized urls

**Comment by nielsm5** [comment]
Larva has been migrated to the iaf context in #4105.

**Comment by jjansenvr** [comment]
closed as fixed
