### ISSUE TITLE
OpenApi issue with different HTTP verbs on same URL

### ISSUE THREAD

**Issue by dirkjanp** [frankframework/frankframework#3983]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We have an Ibis with 2 rest adapters with a Get /object/{objectId} and Patch /object/{objectId endpoints.
Both adapters are used for the same object. However there is a GetObject.xsd and a PatchObject.xsd which have 85% overlapping elements but some elements are unique for each xsd.

When generating the openapi definition from the /webservices menu these 2 adapters are put together in an openapi definition. However under components/schemas/ only the patch version of the object is generated. The path for the get object then refers to this object schema which belongs to the patch. Making it look like the get object returns attributes which don't belong there.

In this case there should be a separate components/schema/object for get and one for patch.

**Reporter**
Dirk-Jan

**Comment by evandongen** [comment]
@dirkjanp , can you provide an example configuration? I have to make a lot of assumptions about your configuration with only this description

**Comment by evandongen** [comment]
Test maken voor POST/PUT/PATCH listener
