### ISSUE TITLE
Statistics show JMS Connection time

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#4073]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The adapter statistics for database related senders and senders with messagelogs show information regarding the time to get the connection to the database. I would also like to have those statistics for JMS senders, as I sometimes have long times on those senders without differentiation between the time to get the connection and the actual waiting time for a response, requiring a lot of testing and support from other teams to eliminate issues with connection pooling.

**Reporter**
Ricardo

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
N/A, Feature request
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
#3180
