### ISSUE TITLE
FileSystemSender option to list directories

### ISSUE THREAD

**Issue by ricardovh** [frankframework/frankframework#4085]
I would like the `FileSystemSenders` to have an option to list directories in addition to listing files, either as separate action or as toggle (file, directory, both) to set on the Sender.

Use case: I have a folder structure that looks like `root/<date>/<filename>`, where files are generated by an external application and put in a subdirectory matching the date of creation. I need to process the files in each subdirectory. In this case I could determine the name of the <date> directory as its format is fixed and as the directory names corresponds with a date, I can limit to which directories I should be looking for files instead of filtering on modification dates/times, but it would be easier if I could list directories and then filter on modification date/time and then process the files in those directories.

Note that recursive listing of files is not desired or possible in this case (if that were an option available on the FileSystemSenders), the Frank!Application that gave me the idea for this request has thousands of files per date in the filesystem, with a big archive being kept, so a full recursive listing would easily go to millions of files, while the application would only need to process the last few days at most.

**Reporter**
Ricardo

**Comment by nielsm5** [comment]
Add a file mask; `FileSystem.listFiles(folder, FileMask);`

**Comment by jkosternl** [comment]
All filesystems now have list folder support, except for Imap and Exchange. 
Now, we need to add the new folder option to the `FileSystemSender`.
