### ISSUE TITLE
Option to disable certain GUI pages and related API endpoints in DTAP

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#4514]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
We are busy implementing several security related requirements and one of those requirements is that we would like to disable the Execute JDBC Query page and the related API endpoints in production. Developers and service management should be granted access 
to the database on their own personal accounts instead of making use of the application NPA.

It would be possible to change our roles from IbisTester to some other role, although we are not sure which other permissions we might lose by changing roles. 

Besides that, from a security perspective, it is still possible for an evil person to grant himself the required role to execute queries. The only way to make sure that an evil person is prevented from executing queries is to disable the functionallity on its own.

Yes, an evil person could still make modifications to an existing configuration in the database by downloading, modifying, reuploading and reloading a configuration and execute hand crafted queries this way. 

In that situation other security measurements should have already detected suspicious activity regarding downloading/uploading/reloading configuration files.

**Reporter**
Laurens

**Comment by jacodg** [comment]
IbisTester is not meant to be used in P. We don't fully understand the requirement. Look here for detailed information about the roles per endpoint:
 
https://frank2example.frankframework.org/iaf/api/?allowedRoles=true

Disabling endpoints per Ibis will make it less clear in general how Ibisses are secured. Every Ibis then needs to be checked for specific configuration.

**Comment by Laurens-makel** [comment]
> IbisTester is not meant to be used in P. We don't fully understand the requirement. 

Yes, we are aware of this.

Even if we don't assign the IbisTester role to anyone, the related endpoints are still 'enabled'. The point I'm trying to make here is that an evil person (read 'hacker') could theoretically still grant himself the IbisTester role.

Let's word the requirement a little different:

'Disable all API endpoints related to IbisTester in production'

This request is somewhat similair to #3628

**Comment by jacodg** [comment]
Difficult/impossible to implement. Not a community issue
