### ISSUE TITLE
Improve usage / documentation of etags and Memcached implementation

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#4543]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I noticed that the documentation on the usage of etags in combination with Memcached is missing.

According to `ApiCacheManager.java` and `ApiMemcached.java` one has to set atleast the following properties to make it work:

- `etag.cache.server=<ip or hostname>:<port>`
- `etag.cache.type=memcached`

In case there is any authentication required, one should also set the following properties:

- `etag.cache.username`
- `etag.cache.password`

It would be a nice addition to the frankdoc page of the ApiListener to mention that it is possible to use Memcached with an ApiListener when the above properties are in place and `updateEtags="true"` is configured on the related ApiListener.

In addition to this, wouldn't it be better to implement these properties at ApiListener level as attributes? Currently the Frank developer is limited to a single Memcached configuration for their whole Frank instance. 

It would be much cleaner to be able to use an auth alias for the username and password instead of relying on some construction with environment variables that are hidden for Frank console users.

**Reporter**
Laurens

**Comment by nielsm5** [comment]
I've added some documentation and the alias is a very good improvement!
