### ISSUE TITLE
(7.7) AmazonS3Sender produces invalid XML when action=write

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#4603]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The following line causes the `name` attribute to appear twice in the XML produced by AmazonS3Sender when action=write:

https://github.com/ibissource/iaf/blob/7.7-release/core/src/main/java/nl/nn/adapterframework/filesystem/AmazonS3FileSystem.java
![image](https://user-images.githubusercontent.com/37303445/223492832-44e46576-b03d-4e54-bf0a-7efdcc3b2461.png)

In the 7.8 release and master branches this has been changed to `bucketName`.

**Reporter**
Laurens

**Comment by jjansenvr** [comment]
Laurens can we consider this to be a backport request?

**Comment by Laurens-makel** [comment]
Yes, I made a PR #4604 for the 7.7 release branche
