### ISSUE TITLE
Refactor duplicated code and generic utility code into iaf-commons module

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#4622]
### Goal
Get rid of duplicated utility classes and make more generic utility classes available to projects that do not depend on the `core` module.

### Description
The framework has various classes that are needed in projects that do not depend on the `core` project, but cannot easily be moved to a generic utility type project because `core`-classes such as `Message`, `Configuration` or `Adapter` are intermingled with the more generic code.

These utility classes need to be pulled apart and refactored into more generic code, with perhaps hooks for extensions that `core` can hook into, or separate utility classes for `core` and `common`.

Specific classes and tasks for code to be moved to module `iaf-commons`:
### Tasks 
- [x] #4790
- [x] #4782
- [x] `AppConstants`
- [x] `ClassUtils`
- [ ] `TestFileUtils`?
- [x] `DateUtils`, `CalendarUtils` --> also needs refactoring to support Java8 data classes
- [x] `EnumUtils`
- [x] `FilenameUtils`
- [ ] `FileNameComparator`
- [ ] `JtaUtil`?
- [ ] Various generic methods from `Misc` need to find a good home in `iaf-commons`: `byteArrayToString()`, `getHostname()`, `toFileSize()`?

Other Code Cleanup Tasks:
- [x] #6567
- Clean up `StringResolver` API

**Comment by nielsm5** [comment]
I think we can close this for now. There are a few methods in Misc that don't really belong there but are also don't belong in common. I think we need to cleanup/refactor when we see things that can be clean up, and don't need to keep this issue open any longer.
