### ISSUE TITLE
Manage cleanup of temporary files

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#4725]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**

The Frank!Framework creates temporary files which are not cleaned up. Some of those files were marked for "delete on exit" but that is bad practice for a number of reasons, so this has been removed in 7.9.

Now what we need to do instead is our own management of deleting temp files.

Options:

1. Track temporary files in the PipelineSession and delete them when that is closed

2. The `FileUtils.createTempFile()` and `FileUtils.createTempDirectory()` methods can track a list of temporary files / folders created, with timestamp, and at regular intervals all temporary files / folders older than given age are deleted via a background-thread.

Option 1 has bigger impact on code and larger chance that we miss some temporary files created in some pipes, so it's more error-prone. The advantage is that it scopes files more precisely and so we are more certain that files really can be deleted when we close the PipelineSession.

Option 2 has the drawback of needing to keep a list of files in memory for longer so memory usage goes up, but not by a lot probably.
Bigger drawback is that perhaps a temp folder created and reaching its "max age" may actually still be in use so we need extra coding to account for that. (For instance, is a Pipe creates a temp folder on start and deletes it only on close of the Pipe, the temp folder will be in use as long as the Adapter is running. So it will soon be older than whatever aging limit we set).

**Reporter**
Tim van der Leeuw

**Comment by jkosternl** [comment]
We need to recheck if the new Cleaner job in #5705 already fixes this issue perhaps for the majority of the files.

**Comment by nielsm5** [comment]
It seems the cleaner seems to be doing it's job.
