### ISSUE TITLE
Add regex replacements to ReplacerPipe

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#4849]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The ReplacerPipe lacks clear documentation, would be useful to allow the use of regex or other smart stuff

in older versions it seems to have supported replacement of newlines somehow

**Reporter**
jjansenvr

**Comment by evandongen** [comment]
@jjansenvr , this summer I reworked the `ReplacerPipe` to become 'streaming' and added documentation as well (see #6987). Can you let me know if you think this is complete enough? --> https://frankdoc.frankframework.org/#/All/ReplacerPipe

BTW: As far as I see, this pipe didn't support regular expressions before I worked on it (I checked the history for the past two years).

**Comment by nielsm5** [comment]
In #7650 we implemented a RegEx pipe
