### ISSUE TITLE
Frank-runner: Not redirecting to Frank console, User details are not being shown, upon logout not redirecting to login screen

### ISSUE THREAD

**Issue by ramanjulu-decos** [frankframework/frankframework#5059]
Hi Team,
    I have been trying to enable authentication in Frank-runner by following the document https://frank-manual.readthedocs.io/en/latest/deploying/security.html
1. As soon as I enter url https://localhost:443, it is loading the landing page of frank runner and showing prompt box to enter username and password instead of redirecting to frank console (login screen), upon entering valid details showing the landing page that is /iaf/gui, but right side corner not showing logged in user details. if I cancel the prompt, then it is redirecting to the frank console, after entering valid credentials in frank console, landing on /iaf/gui and again showing prompt to enter credentials
2. upon logout also not redirecting to login screen, instead prompt is being shown to enter credentials

**Comment by jacodg** [comment]
Can you confirm this problem still exists in the latest version?
