### ISSUE TITLE
Vague "Cannot convert string to double" error when accidentally using ** instead of * as xpath wildcard on a Param

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#5253]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Clearly an user error, but would be nice to have a more helpful error here. The only reason I accidentally found out the ** wildcard was the problem was because I was generating a Ladybug report to complement the issue I writing here for it and happened to use a syntax without a wildcard there.

**Reporter**
M. Lenterman

**To Reproduce**
[Pipeline SoapEndpointRouter_VrijeBerichten - Cannot convert to double error.zip](https://github.com/ibissource/iaf/files/12358382/Pipeline.SoapEndpointRouter_VrijeBerichten.-.Cannot.convert.to.double.error.zip)

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230810.190012: ZaakBrug
Running on b8aa95859d75 using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (1.8.0_372-b07)
Heap size: 2220M, total JVM memory: 2426M
Free disk space: 235GB, total disk space: 251GB
Up since: 2023-08-16 12:35:19 (46s) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
The stack looks horrid due to streaming which was removed in the 7.9 final. When streaming is disabled the stack as well as the ladybug report will make sense again.
