### ISSUE TITLE
Error in JSON parser when running larva scenario

### ISSUE THREAD

**Issue by dirkjanp** [frankframework/frankframework#5437]
When running larva scenario the larva tool crashes with the following error

![image](https://github.com/ibissource/iaf/assets/110221429/a70594c2-6930-4150-9617-abaea3afb4b6)

This works with snapshot FF 7.8.1-20230420.190150 and now fails when trying to upgrade to FF 7.8.1

**Reporter**
Dirk-Jan / Ali

**To Reproduce**
For more info about the larva test and the adapter handling this test you can contact me.

**Comment by jacodg** [comment]
Larva is expecting json because the file name ends with .json but the adapter is returning xml, hence it is not expecting char 6 (\<). So it's not strange that Larva cannot parse the "json" but a more user friendly error message would be nice

**Comment by jkosternl** [comment]
This is already fixed in september 2022 and works in 7.9.0 and higher already. See #3736
