### ISSUE TITLE
Key Vault integration for managing credentials

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#5438]
A great addition would be to have a way to load credentials from an external source, there are several different solutions regarding key vaults, for example Azure Key Vault.

It would be great to have a generic interface, which one could implement and provide methods to retrieve credentials from external sources which could be used in adapters, in combination with the `authAlias` attribute and a new attribute `authSource` or something similar.

**Comment by jacodg** [comment]
Interface in CredentialProvider needs to be implemented. Niels will share more info

**Comment by nielsm5** [comment]
Yess, the common interface is [ICredentialFactory](https://github.com/ibissource/iaf/blob/master/credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentialFactory.java).

**Comment by Laurens-makel** [comment]
> Yess, the common interface is [ICredentialFactory](https://github.com/ibissource/iaf/blob/master/credentialProvider/src/main/java/nl/nn/credentialprovider/ICredentialFactory.java).
> 
> There is a property which allows you to choose the implementation.

So it's either one or the other?

I feel that it would be a good addition to be able to specify from which credential factory to load a certain set of cerdentials from. 

The reason I'm asking for an external key vault integration is because it makes it easier to rotate secrets/passwords periodically,  although some credentials are used by test tooling and other appliances. To solve this, we would like to be able to load certain secrets 'the oldschool' way and some secrets we can rotate via Azure for example.

**Comment by nielsm5** [comment]
We need to verify if we can use the K8S credential store, which can (hopefully) delegate to AWS or Azure, depending on which cloud is being used. Else we might blow up the CredentialProvider with tens or hundreds of dependencies.
