### ISSUE TITLE
Health endpoint returns healthy when losing connection to the database due to out of memory

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#5441]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
That the database connection breaks when running out of memory is understandable. The broken database connection should be reflected in the health endpoint though, so that the container host can replace the broken instance.

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Can you give us additional information? Environment info? Stacktrace of the OutOfMemory? Which  healthcheck endpoint and what does it return?
