### ISSUE TITLE
XsltPipe resolves escaped line endings after processing an xml

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#5466]
I have an XsltPipe which tries to replace the conversationId in the soap header. After processing an xml that has `&#xd;` chars in the body with an XsltPipe, in the output:
 - Ladybug shows that the chars are resolved line feed
 - Test a pipeline shows everything in one line without the char and lf

When I do the same transformation with the same xml and xsl in XMLSpy I see that the body content is not changed. I'd like to see the same behavior in the framework.

**Reporter**
Ali

Pipe:
`<pipe className="nl.nn.adapterframework.pipes.XsltPipe" name="InjectId" styleSheetName="InjectId.xsl">
	<param name="customId" value="asd"/>
</pipe>`

[InjectConvId.xsl.txt](https://github.com/ibissource/iaf/files/12735322/InjectConvId.xsl.txt)
[input.xml.txt](https://github.com/ibissource/iaf/files/12735323/input.xml.txt)

Test a pipeline screen:
![image](https://github.com/ibissource/iaf/assets/10929856/147fdcc5-c9ba-4abc-a1cd-fde4e9ea1d58)

Ladybug screen:
![image](https://github.com/ibissource/iaf/assets/10929856/8f1e725d-f59a-4125-986b-520d60b18a97)

When I write the output of XsltPipe to a file:
[asd.txt](https://github.com/ibissource/iaf/files/12735370/asd.txt)

FF: 7.9-20230811.190015

**Comment by jkosternl** [comment]
@alisihab, the current implementation of the XsltPipe always seems to work like that. Meaning that input `asd&#xd;` turns into 'asd' and a new line added. 
See `nl.nn.adapterframework.xslt.XsltPipeTest#testSessionKey` since 2019 or 2020. 
I'll discuss if we need to change the displaying of the results in some screens in the UI now.
