### ISSUE TITLE
Unexpected empty array behaviour Json2XmlValidatorPipe Xml to Json conversion with Xsd

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#5530]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When converting Xml to Json with the Json2XmlValidatorPipe, with the help of an XSD, an empty array is not translated correctly. In Xml an array would be multiple occurrences of a certain element. The XSD helps the conversion with minOccurs="0" maxOccurs="unbounded" to indicate that the element is an array. Currently having zero occurrences of the element marked as an array is resulting in the element not being present in the output. I'm expecting this to be `[ ]` indicating an empty array in Json.

**Reporter**
M. Lenterman

**To Reproduce**
1. Xsd with `<xs:element name="productenOfDiensten" type="zgw:Uri1_1000" minOccurs="0" maxOccurs="unbounded"/>`
2. Xml input without the `productenOfDiensten` element.
3. Observe element not being present in output. Expected `"productenOfDiensten": [ ]`.

**Screenshots**

**Configuration**
```xml
<Json2XmlValidatorPipe
	name="XmlToJson"
	schema="Zgw/Zaken/Model/PostZgwZaak.xsd"
	outputFormat="JSON"
	deepSearch="true"
	throwException="true"
        >
	<Forward name="success" path="Created"/>
        <Forward name="error" path="InternalServerError"/>
</Json2XmlValidatorPipe>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9-20230905.223421: Openforms2bpel 1.0.0
Running on 97c8c3993f6d using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 1049M, total JVM memory: 1973M
Free disk space: 202GB, total disk space: 251GB
Up since: 2023-10-06 13:36:26 (26m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Why is this required? JSON likes to 'hide' empty elements.

**Comment by MLenterman** [comment]
It is not strictly needed, as it is still valid JSON. It is a "nice to have" to keep empty/null/missing value behavior consistent between different data-types.

**Comment by nielsm5** [comment]
When you don't send the xml element, I also don't expect it to appear in the JSON result.
When you add the nil=true attribute on an element, the element in JSON should return NULL.
When you provide an empty element, the corresponding JSON element should be an empty object, array, etc.

**Comment by jacodg** [comment]
Could you attempt to add nil=true? Please re-open issue when needed

**Comment by MLenterman** [comment]
> When you don't send the xml element, I also don't expect it to appear in the JSON result. When you add the nil=true attribute on an element, the element in JSON should return NULL. When you provide an empty element, the corresponding JSON element should be an empty object, array, etc.

The issue is that XML does not have a syntax for array's. In XML an array is simply having multiple of the same element. With a single element there is no way to tell from the syntax if it is just a normal field or if it should be an array. So with an XSD it the translation can be helped to always interpret a given element as an array. That also means that the only way an empty array can be achieved is to have zero elements and have it marked as array in the XSD. Leaving the element empty would suggest an array with the first element being an empty string.

As for a use-case of why it is important to have the ability to send an empty array: We are adding an arbitrary resource via an API that contains an array of names for example. Next we want to PATCH this resources to an empty array of names. The only way to do that would be to PATCH it with `{ "listOfNames": [ ] }`
