### ISSUE TITLE
Convert frank-doc-doclet to Java 11+ (Doclet API)

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#5558]
Currently, project frank-doc-doclet is made with hard dependencies on Java 8. 
```
<groupId>com.sun</groupId>
<artifactId>tools</artifactId>
<version>1.8</version>
```

Since we're moving to Java 11 (#5485), also this project needs to get updated. It needs to use the new Doclet API. See https://openjdk.org/groups/compiler/using-new-doclet.html

**Comment by philipsens** [comment]
Waiting on ci/cd to make release

- [ ] Fix gpg signing with maven release plugin
