### ISSUE TITLE
Allow secrets shorter than 256 bits to be used with the JwtPipe

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#5645]
It difficult for us to ask many different customers to change their existing password policy and automatic secret generation methods for our application. I understand this restriction comes from the used library. Would it it be possible to pad with 0's if < 256 bits perhaps?

**Reporter**
M.Lenterman

**Screenshots**
![image](https://github.com/ibissource/iaf/assets/9280762/cd43bc11-5839-4888-8388-fd17e4b3f6ac)

**Comment by nielsm5** [comment]
I think we'd need to add a suffix not a postfix. See https://stackoverflow.com/questions/51883048/should-right-padding-an-hmac-sha256-secret-key-with-0-return-the-same-hash

**Comment by jkosternl** [comment]
Still need to go into 7.9!
