### ISSUE TITLE
resending messages in directory listener not working

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#5749]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When trying to resend a message in the directory listener we get an error 

**Situation 1**
Unable to resend message [test]. Cannot change processState to [ERROR] for [test]: Cannot move file [C:\Users\M66I476\git\dropfolders\ibis4sapcd\MFHIn_00109\error\test] to [error]: (NoSuchFileException) C:\Users\M66I476\git\dropfolders\ibis4sapcd\MFHIn_00109\error\test

**Situation 2 setting overwrite to true**
Unable to resend message [test]. Cannot change processState to [ERROR] for [test]: Cannot move file [C:\Users\M66I476\git\dropfolders\ibis4sapcd\MFHIn_00109\error\test] to [error]: (NoSuchFileException) C:\Users\M66I476\git\dropfolders\ibis4sapcd\MFHIn_00109\error\test

**Reporter**
jjansenvr | eddy

**To Reproduce**

**Screenshots**

**Configuration**
```
<Adapter name="MFHIn_00109" active="${active.mfh}" description="Create trigger in the IBISFILETRIGGER table for legacy flow 00109">
        <Receiver pollInterval="${mfh.MFHIn_00109.pollInterval}">
            <DirectoryListener
                minStableTime ="${mfh.MFHIn_00109.minstabletime}"
                fileTimeSensitive="false"
                name="MFHIn"
                messageType="info"
                root="${mfh.MFHIn_00109.rootdir}"
                inputFolder="in"
                inProcessFolder="inProcess"
                errorFolder="error"
                createFolders="true"
                wildcard="${mfh.MFHIn_00109.wildcard}"/>
        </Receiver>
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.8.3: Ibis4SapCD
Running on LPCENL005288323 using Apache Tomcat/9.0.74
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 357M, total JVM memory: 604M
Free disk space: 101GB, total disk space: 238GB
Up since: 2023-11-14 12:44:45 (8m)

```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
There's a "move to available" button.

**Comment by tnleeuw** [comment]
I don't know what "move to available" does, I overlooked that button?
"Resend" uses a "PUT" URL that is invalid with these double-encoded filenames, so whatever it tried to do on the backend doesn't even happen yet.
I don't know how "move to available" sends its command to the backend.
