### ISSUE TITLE
Startup time deterioration

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#5786]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In 7.9RC3 the startup time seems to be a lot longer causing redeploys on our cloud environment

I would like the startup speed to improved and also tested in the regular testproces

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
Opstart tijd iaf-test in 7.8: 34576 ms
Opstart tijd iaf-test in 7.9: 68352 ms

**Comment by philipsens** [comment]
While focussing on the start time of ff-test, I focused on loading the `MainConfig`.

| Bisect | Commit                                   | Description                            | Startup Time |
| ------ | ---------------------------------------- | -------------------------------------- | ------------ |
| ✔️      | 0dd59a7a437eb235f3489f1150d4c4732a4b9131 | Docker restructure (early 7.9-release) | 25852        |
| ✔️      | 369e662c                                 |                                        | 35606        |
| ✔️      | 1a67926e                                 |                                        | 41419        |
| ✔️      | 7a68844950ba6fd5196a1195d4be23d0e802f381 |                                        | 39328        |
| ✔️      | 576c6f14                                 |                                        | 42447        |
| ❌      | C89484b8bb431c5c8ea01a61a3e6636f22b0a38f |                                        | 52703        |
| ❌      | C3c650b81d91f9aac9bf85243766b9905a44441f |                                        | 52228        |
| ❌      | fe5e1557                                 |                                        | 51067        |
| ❌      | Eb67dd29ecae94c71a625cc4f03c8ff784e6f6d0 |                                        | 55885        |
| ❌      | 294f5321                                 |                                        | 50826        |
| ❌      | 73d468d519f7aff9d0b045e64a256906fe777024 | Last 7.9-release commit                | 49871        |

At commit C89484b8bb431c5c8ea01a61a3e6636f22b0a38f we see a jump in start time, although it's not the only commit where we see this. In this commit, the loading of the `MainConfig` jumped with ~7 seconds. The change was a version bump for Spring.

Earlier we also see a jump at 369e662c, I did a git bisect between the first two commits and fount that this delay originated at adding Aspose to the WebApp. That has been removed in #5875. 

Further investigation for the other differences can be done. It would also be nice to know what the startup time would be on java 11.

**Comment by philipsens** [comment]
At 273ae4c17fa0a7da77df11d449292f16495aff90 spring-security got bumped to 5.8.4 which resulted in an additional 5 second of startup time.
