### ISSUE TITLE
Adapters with functional errors end up in SUCCESS state, this is confusing for users using ladybug

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#5852]
**Describe the issue**
A pipeline will either end in a success or a exception / Error.  This is perfect for FF pattern where the exception or error will force retry and eventually pushes the message into the errorstore.

When you have a RR pattern, and say the backend system is not the exception is handled and an error response is mapped, the adapter ends in a state SUCCESS but functionally there was a problem.

Solution could be:  add  a success / failure / error and some extra field called "errormessage" that can be manipulated by the frank developer. 
Ladybug could pick this up (as well as the logcontextpipe)  

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
We could perhaps expand the `pipeLineAbort` and `pipeLineOutput` methods to provide the exit name?

```
if (!pipeLineResult.isSuccessful()) {
	ibisDebugger.showValue(correlationId, "result", pipeLineResult.getResult());
	ibisDebugger.pipeLineAbort(pipeLine, correlationId, null);
} else {
	Message result = ibisDebugger.pipeLineOutput(pipeLine, correlationId, pipeLineResult.getResult());
```

And then either add a new column or add the exit name to the existing column eg. `ERROR (name)`

**Comment by nielsm5** [comment]
It's now possible to send pipeline abort messages with a (functional) result :)
