### ISSUE TITLE
Add dynamic drop-down to faster select an adapter in Test a Pipeline

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#5893]
**Current situation**

1. The screen 'Test a Pipeline' has a mandatory step to select a Configuration and then select an adapter from the whole list. That also involves a lot of scrolling. You need to know which Configuration is used in advance. 

**To Be situation**
1. The 'Test a Pipeline' screen has a dynamic drop-down, at 'select an adapter' which supports text filtering, where you can type in e.g. 'xslt' and all matching scenario's with '*xslt*' (case insensitive) are shown in the drop down. Easy to select directly the one you like. 
2. The 'Test a Pipeline' screen 'Configuration' pull-down' is not mandatory anymore. When nothing is selected, all adapters are shown/available to filter the result list at step 2. Also add an empty entry in that pull-down, to select nothing (empty the configuration filter). 

**Reporter**
Jacobjob

**Comment by nielsm5** [comment]
Cannot implement 'feature' 2, you MUST always select a configuration.

**Comment by philipsens** [comment]
:(
