### ISSUE TITLE
Unwrapping soap envelope does not work properly in the pipeline

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#5925]
In the pipeline, I have a SoapValidator with `soapVersion="auto"` and a soapWrapper that unwraps the incoming soap message. After some mappings, I send a message using EsbJmsSender(RR) in the pipeline. There is no problem so far(!). The framework throws an error when unwrapping the response of the outgoing call. 

`SOAP Body is empty or message is not a SOAP Message`

In the adapter input, the soap namespace is 1.2. In the outgoing call response it is 1.1. 
That seems to be the issue. I think the namespace from the adapter input is stored somewhere and be used later although the outgoing call response should not be impacted by the input.

Please reach me for additional info.

**Reporter**
Ali

FF: 7.9-RC1-hotfix8

**Comment by alisihab** [comment]
changing the soap ns to 1.2 in the outgoing call response fixes the issue

**Comment by jjansenvr** [comment]
We have multiple things relying on the same  soapVerison property

Simple solution?

- If direction is UNWRAP I do not care about the soap version just unwrap (input and output wrappers)
- if I have an inputwrapper, direction is UNWRAP with soap version auto I will need to use the version in the response (keep in session param)
- if I have an inputwrapper , direction is WRAP soapversion auto is not an option, we will have to tell the wrapper which version to use (default to (1.1?) (should not use the session param value) 
- if I have a output wrapper, direction is WRAP soap version should be copied from the session param version

**Comment by nielsm5** [comment]
As mentioned in #6032, this is a potential duplicate.
