### ISSUE TITLE
Display MailSender smtpHost & smtpPort attributes in console

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#5938]
In the Adapter Status overview page each adapter displays a list of used senders and some information about how these senders are configured.

It would be a good addition to display the configured smtpHost & smtpPort attributes here.

![image](https://github.com/frankframework/frankframework/assets/37303445/8cc7be38-ff5f-4e48-8a90-ebe23c389ef2)

**Reporter**
Laurens

**Comment by jkosternl** [comment]
Solution now looks as follows: 
<img width="788" alt="Scherm­afbeelding 2024-03-21 om 13 25 19" src="https://github.com/frankframework/frankframework/assets/29304914/533b53f9-42e9-4604-b76b-4b606db7a4f1">

In text, it was:
`MailSender [SendMail-sender]`
And after the change, it is:
`MailSender [SendMail-sender] (localhost:25; TLS=false)`
