### ISSUE TITLE
Return 404 instead of 500 from FF API when items are not found

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#5939]
For example, when calling `/iaf/api/configurations/unknownName` the FF API will respond with a 500 internal server error whilst a 404 would be a better fit.

![image](https://github.com/frankframework/frankframework/assets/37303445/6b95c73f-ee02-4c22-9019-89564b0083d8)

EDIT: In frank2example a 400 Bad Request is returned, which is cleaner than a 500 but in fact there is nothing wrong with the request, the API completely understood my request but there was no resource found.

**Comment by jacodg** [comment]
We can change 400 to 404 but it might be WebSphere changing it to 500
