### ISSUE TITLE
Tibco/Ems receiver sleep interrupted java.lang.InterruptedException: null

### ISSUE THREAD

**Issue by rvdstel** [frankframework/frankframework#5943]
Error message on the Console: `Receiver [ProcessDPDHTitan] sleep interrupted, java.lang.InterruptedException: null`.
The tibco/ems receiver does not start after `ConnectionWaitTimeoutException's` happened. 
The Receiver can only be started manually, through the console. 

Versie: FF! 7.8.3-hotfix1

**Reporter**
Richard van der Stel

**Additional Context**
Sent by mail to Niels: logfile and adapter xml.

**Comment by jkosternl** [comment]
Hello @rvdstel, 

We've investigated this issue on the interrupt exceptions together with the `SocketTimeoutException` (Read timed out) messages, found in the log file. 
First, we've concluded that in F!F version 7.9 and higher, the error handling works quite differently and is improved already. 
Secondly, it is hard to get clear who exactly interrupted our receivers. That stack is quite short somehow. 
Thirdly, we think that it is okay that it moves to the state STOPPED after somebody interrupted our receivers. That's with the current information we have. 

If you encounter the same issue in the future again, with version 7.9 or higher, we like to investigate this once more. So, please then let us know. For now, we're just doing some minor cleanups, but no functional changes on this logic. 

Thanks,
Jacobjob
