### ISSUE TITLE
Remove sources from menu in Frank!Console

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#5948]
FrankDoc in console alleen bij dev stage? (en sourcecode misschien ook)

**Comment by nielsm5** [comment]
Sources mogen weg uit het menu links, staat al vaak genoeg (onder aan het scherm en in het info tabje).
Frank!Doc hoeft alleen bij otap LOC en DEV zichtbaar te zijn.

**Comment by jjansenvr** [comment]
ik ben het hier niet echt mee eens, sommige klanten hebben geen dev omgeving en soms is het ook handig op andere omgevingen, liever zie ik een property per menu item die we in de properies file van ACC en PRD indien gewenst kunnen uitzetten
