### ISSUE TITLE
(OutOfMemoryError) Failed to create a thread

### ISSUE THREAD

**Issue by rvdstel** [frankframework/frankframework#5953]
In productie zijn een aantal nodes tegen hetzelfde probleem aangelopen, waarna alleen een herstart van de jvm de oplossing was:
(OutOfMemoryError) Failed to create a thread
FF: 7.8.3-hotfix1

**Reporter**
Richard van der Stel

**Additional Context**
Aan Niels is de mail met de volledige stacktrace gestuurd. Ook is de heapdump gedeeld ter analyse.

**Comment by jacodg** [comment]
Was JEE CDI overhead
