### ISSUE TITLE
Cleanup/Merge IExtendedPipe with IPipe

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#5957]
**Describe the issue**
We now have an `IExtendedPipe` and `IPipe` interface, we need to find out if both are needed, and potentially refactor the code in order to simplify things.
The same goes for IWithParameters, IValidator and IWrapperPipe (which do not implement `ExtendedPipe` for instance).

**Comment by tnleeuw** [comment]
`IExtendedPipe` and `IPipe` can indeed be merged. I meant to create a ticket for that some weeks ago already... probably forgot! 😳
