### ISSUE TITLE
Query Timeout not applied for StoredProcedure queries

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#5986]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I use a storedprocedurequerysender. It has timeout="30". That seems ineffective to me since in ladybug I see the following
![image](https://github.com/frankframework/frankframework/assets/10929856/e2589c8a-2a2b-4861-b5aa-dc5ed9fea535)

After ~960 seconds it throws connection timed out error
![image](https://github.com/frankframework/frankframework/assets/10929856/6b50dddd-ff66-4442-864b-de994d9154a6)

**Reporter**
Ali

7.9-20230811.190015

**Comment by alisihab** [comment]
Observed in 7.9-RC1-hotfix10 as well. However,  sometimes the configured timeout is effective
![image](https://github.com/frankframework/frankframework/assets/10929856/943723eb-a311-4d69-919c-b6c10ef6d016)

**Comment by alisihab** [comment]
#6095 could be related

**Comment by alisihab** [comment]
hmm, i think this only happens when the connection becomes stale. After having the keepAlive logic using a FixedQuerySender executing SELECT 1 FROM DUAL every 10 minutes configured timeouts seem to be effective. Recently, I realized that all timeouts seem to happen in the configured amount of seconds.

**Comment by tnleeuw** [comment]
I found out that the word "Timeoutguard" misled me. The Jdbc query sender code sometimes applies the `timeout` attribute to statements as query-timeout.
However it does so rather inconsistently. It was not done for stored procedure queries, and is also not applied to a number of other queries that are executed (such as result-queries).
