### ISSUE TITLE
Store messageContext in error store

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#5992]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have a pipeline where I use context keys and error store is configured in the receiver. I'd to be able get the message context as it was  when resending the message from error store

For the use case see https://github.com/frankframework/frankframework/issues/5993

**Reporter**
Ali

**Comment by alisihab** [comment]
FF: 7.9-20230811.190015

**Comment by tnleeuw** [comment]
> any update on this?

No, not yet.
