### ISSUE TITLE
(OutOfMemoryError) Failed to create a thread, 20.000+ threads associated with JMSManagedConnection

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6064]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In #5953 and by email has been suggested that this has been caused by JEE CDI overhead.

We have explicitly turned off JEE CDI and increased max JVM size to 4G but issue occurred again.

IBM HeapAnalyzer shows us that there are very large thread groups (20.000+ threads) associated with the JMS session. When inspecting what these threads are doing, it seems that 99%+ of them is an `IdleConnectionEvictor`.

Will add sceenshot of the analysis later.

**Reporter**
Richard/Laurens

**Comment by Laurens-makel** [comment]
As you can see here, 11.786 threads associcated with this `JMSManagedConnection`, which is owned by the JMS session object.

![image](https://github.com/frankframework/frankframework/assets/37303445/a29ea537-d921-4d4c-a20d-5634c1127b5e)
![image](https://github.com/frankframework/frankframework/assets/37303445/5913b946-2ba3-43d4-8d77-a6afb8666012)

99% of these threads are as following:
![image](https://github.com/frankframework/frankframework/assets/37303445/b4211889-f8c0-4513-9d60-27d6f342b2ad)

**Comment by Laurens-makel** [comment]
Another crash observed, heap dump shows again 20k+ threads.

A heap dump the morning after the crash does not show any abnormal amount of threads.

**Comment by jjansenvr** [comment]
Is it possible to relate the amount of threads to the number of messages processed (jms to http cmis messages)
