### ISSUE TITLE
In F!F example, REST endpoint Mundo does not appear in OpenAPI spec

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#6076]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
In the F!F sources, there is a configuration in file example/src/main/resources/ConfigurationManualExerciseMundo. It has `<ApiListener name="ManualExerciseMundo" uriPattern="/mundo" method="POST" />`. However, url https://frank2example.frankframework.org/iaf/api shows a page in which the word "mundo" does not appear.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 8.1.0-20231223.223430: Frank2Example
Running on frank2example using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (11.0.21+9)
Heap size: 158M, total JVM memory: 317M
Free disk space: 246GB, total disk space: 501GB
Up since: 2023-12-23 23:43:04 (15d)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Laurens-makel** [comment]
Hoi Martijn,

De link die je deelt refereert naar een endpoint dat een overzicht retourneert van alle beschikbare endpoints van de `F!F` API. 

De OpenAPI spec die je zoekt vind je hier: https://frank2example.frankframework.org/iaf/api/webservices/openapi.json 

Mundo lijkt hier in voor te komen.
![image](https://github.com/frankframework/frankframework/assets/37303445/21681c39-7724-48ab-814a-06df277b9f23)

**Comment by jacodg** [comment]
I would expect the service url in https://frank2example.frankframework.org/iaf/api/webservices/openapi.json?uri=/mundo (which you can find going to webservices and opening the OpenAPI 3.0 for this service)

**Comment by mhdirkse** [comment]
Hallo Laurens. Wat bedoel je met de F!F API? Wie beslist welke adapters in het F!F bij de "F!F API" horen en welke adapters die er ook zijn daar buiten vallen? Is er ergens een file waar dat verschil bepaald wordt?

**Comment by Laurens-makel** [comment]
> Hallo Laurens. Wat bedoel je met de F!F API? Wie beslist welke adapters in het F!F bij de "F!F API" horen en welke adapters die er ook zijn daar buiten vallen? Is er ergens een file waar dat verschil bepaald wordt?

Ik doel op de API van het framework zelf, deze wordt  gebruikt voor de GUI.

De adapters met een `ApiListener` die de Frank developer bouwt met het framework worden op `/api` ontsloten en niet op `/iaf/api` .

**Comment by mhdirkse** [comment]
Als je https://frank2example.frankframework.org/iaf/api/webservices/openapi.json?uri=/mundo opent, dan zie je een OpenAPI spec waarin Mundo beschreven staat.

**Comment by mhdirkse** [comment]
Jaco en ik vinden het vreemd dat er in de status pagina van de console een "*" in het URI pattern staat, zie figuur.
![image](https://github.com/frankframework/frankframework/assets/6784732/bf6a23ce-31af-4686-850e-33023d31e478)

Deze figuur krijg je door in de status pagina van de console de adapter ManualExerciseMundo open te klappen.

**Comment by mhdirkse** [comment]
Ja, is zo afgehandeld, @nielsm5.

**Comment by jacodg** [comment]
Volgens mij is het ook nog steeds een p;robleem dat "servers" leeg is in https://frank2example.frankframework.org/iaf/api/webservices/openapi.json?uri=/mundo (zie mijn comment van 8 jan). Ik heb nu https://github.com/frankframework/frankframework/issues/6373 aangemaakt
