### ISSUE TITLE
Narayana TM: too many open connections problem

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6078]
I switched to Narayana TM in my apps. After some time, I started seeing too many open connections error in console returned from ems server. Then I checked the security items page and it seems that the Narayana tm is keeping the idle connections, although there is no traffic that would require those connections. Moreover, number of idle connections always hit to the max.

Here is an example app that has the issue. I have different apps with idle=max=60 as well

App has been running for 5h and no message was processed

FF:
![image](https://github.com/frankframework/frankframework/assets/10929856/ea4de1a8-4884-4dc4-8442-4153b57f4361)

RR:
![image](https://github.com/frankframework/frankframework/assets/10929856/b8a5743b-db0e-4da1-ba07-8fd8c658304f)

**Reporter**
Ali

7.9.0-hotfix1

**Comment by jacodg** [comment]
This feels like the same issue as https://github.com/frankframework/frankframework/issues/6064

**Comment by jkosternl** [comment]
@alisihab, can you show (add to the issue) the used configuration of Narayana and the database configs?

**Comment by alisihab** [comment]
![image](https://github.com/frankframework/frankframework/assets/10929856/593bf2df-2102-4aeb-8ddc-2f533c670879)

**Comment by alisihab** [comment]
I already tried the following and it made no difference
transactionmanager.narayana.jms.connection.checkInterval=61000

**Comment by nielsm5** [comment]
A default checkInterval of 5 minutes has now been configured by default, and an exception will be thrown when a connection can not be setup within 15 seconds.
By default the FF JMS pools allows a total of 500 open sessions, it's possible the [Tibco default](https://support.tibco.com/s/article/Tibco-KnowledgeArticle-Article-35036) has been set to 250?

**Comment by tnleeuw** [comment]
The conclusion so far is that the behaviour we see is by design. Number of idle connections is set to total number of connections by design.

We should turn down the total number of connection in the pool to a lower number, like 5, or perhaps even 2.

Still doing some experiments and investigation.
