### ISSUE TITLE
Duplicate headers being send to token endpoint when using oauth2 flow on a HttpSender resulting in bad request error from token endpoint

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6114]
While implementing oauth2 flow on a HttpSender, we ran into a vague bad request error from configured Microsoft token endpoint. After adding some custom code to get more information, we noticed that the `Content-Type` header was present twice in the outgoing request. 

According to the HTTP spec it is not allowed to have multiple occurrences of a header, except for when it is a comma-separated value that is mergable. This is not the case here.

The issue might be isolated to requests using oauth2 . Our custom code workaround added a duplicate check to fix the issue here: https://github.dev/frankframework/frankframework/blob/2844695d4a4e97514dde6e618f30b3198355c8bc/core/src/main/java/org/frankframework/http/authentication/OAuthAccessTokenManager.java#L170-L201 

**Reporter**
M. Lenterman

**To Reproduce**
1. Use a HttpSender and configure a tokenEndpoint
2. Set a common header like `Content-Type`
3. Check request object after being converted in `OAuthAccessTokenManager.convertToApacheHttpRequest`
4. See duplicate headers

**Screenshots**

**Configuration**
```
<HttpSender 
	name="CatalogiReadHttpSender" 
	methodType="POST"
	authenticatedTokenRequest="false"
	scope="..."
	clientAlias="dataverse"
	contentType="JSON"
	tokenEndpoint="..."
	/>
```

**Environment**
```
FF! 7.9-20230905.223421: Openforms2bpel 1.0.0
Running on 6954f3acfcaf using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 985M, total JVM memory: 1406M
Free disk space: 210GB, total disk space: 251GB
Up since: 2024-01-16 11:35:31 (2m) 
```

**Comment by jacodg** [comment]
The error message from the Microsoft token endpoint was: the request has an invalid header name

**Comment by jkosternl** [comment]
The class `OAuthAccessTokenManager.java` always added the `Content-Type` header on POST messages, even though it might already exist. Added a check to conditionally add it. That should fix this issue. 
Other headers were not already there or being added, so likely this is the only header that caused the issue.
