### ISSUE TITLE
Authorization header with BASIC auth being sent to token endpoint despite authenticatedTokenRequest set to false when using oauth2 flow on HttpSender

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6115]
While implementing oauth2 flow on a HttpSender, we ran into a vague bad request error from configured Microsoft token endpoint. In the logs we noticed that the Authorization header with BASIC auth was always being sent to the token endpoint. The Frank!Doc suggests that BASIC auth should only be send to the token endpoint if `authenticatedTokenRequest` is true.

**Reporter**
M. Lenterman

**To Reproduce**
1. Use a HttpSender and configure a tokenEndpoint
2. Check logs with `wire` and `headers` on DEBUG level with authenticatedTokenRequest=false by default
3. Check logs with `wire` and `headers` on DEBUG level with authenticatedTokenRequest=true
4. Observe that in both cases the Authorization header with BASIC auth is being sent.

**Configuration**
```
<HttpSender 
	name="CatalogiReadHttpSender" 
	methodType="POST"
	authenticatedTokenRequest="false"
	scope="..."
	clientAlias="dataverse"
	contentType="JSON"
	tokenEndpoint="..."
	/>
```

**Environment**
```
FF! 7.9-20230905.223421: Openforms2bpel 1.0.0
Running on 6954f3acfcaf using Apache Tomcat/8.5.90
Java Version: OpenJDK Runtime Environment (11.0.20.1+1)
Heap size: 985M, total JVM memory: 1406M
Free disk space: 210GB, total disk space: 251GB
Up since: 2024-01-16 11:35:31 (2m) 
```

**Comment by nielsm5** [comment]
Moving this to the 8.2 we need to rewrite how to use oauth. The current implementation is embarrassing...

**Comment by evandongen** [comment]
I think I found where this goes wrong. In `org.frankframework.http.authentication.OAuthAccessTokenManager#retrieveAccessToken` we create a `TokenRequest`. We use the `ClientSecretBasic` implementation. If you read that class / the javadoc of that class, you see it will create a basic auth header:

```
/**
 * Client secret basic authentication at the Token endpoint. Implements
 * {@link ClientAuthenticationMethod#CLIENT_SECRET_BASIC}.
 *
 * <p>Example HTTP Authorization header (for client identifier "s6BhdRkqt3" and
 * secret "7Fjfp0ZBr1KtDRbnfVdmIw"):
 *
 * <pre>
 * Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3
 * </pre>
 **/
```
This header is then transferred to a Apache HttpClient request in `org.frankframework.http.authentication.OAuthAccessTokenManager#convertToApacheHttpRequest`

I've pushed a change in a draft PR for now.

**Comment by evandongen** [comment]
I've tested this change with a customized `org.frankframework.http.authentication.OAuthAccessTokenManagerRequestTest` which points to a running Keycloak (oauth2 server) instance. I can confirm that in both scenarios, an accessToken can ben obtained.

In the future, we'd like to test this in a seperate Testcontainers test.
