### ISSUE TITLE
Multipart request returns error after upgrade to FF 7.9.0

### ISSUE THREAD

**Issue by dirkjanp** [frankframework/frankframework#6118]
**Describe the issue**
This issue occurs after upgrading from FF 7.8.4 to 7.9.0. Functionally nothing was changed.

When doing a multipart request /post through a http sender, the following error is returned.
<?xml version="1.0" encoding="UTF-8"?>
<Errors>
	<Error>
		<errorCode>INVALID_MULTIPART_REQUEST</errorCode>
		<message>Non-binary part must be JSON or XML, was: &apos;image/jpeg&apos;</message>
	</Error>
</Errors>

**Reporter**
Dirk-Jan

**To Reproduce**
Call ibis api listener adapter with a multipart request.

**Comment by nielsm5** [comment]
In order to have a more fine-grained control over what is actually sent we've implemented #5949, to allow users to choose between text and file based uploads.

**Comment by nielsm5** [comment]
I'm closing this issue for now, if new information shows up, or if you require more information (from us), you can re-open this ticket!
