### ISSUE TITLE
Support multiple credential factory classes

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6133]
Related to #5438.

Currently an application instance is bound to a single `ICredentialFactory` instance, allowing the user to load credentials from a single source. 

Within our current implementation we store Azure/AWS related keys under Websphere auth aliasses. However this is not compliant with key rotation policies many companies have. Currently this would force the WebSphere manager to update the aliases every X days.

To solve this, the application should be able to read from AWS/Azure vaults/stores, that is requested in #5438. However this would impose that we would need to move all our credentials to AWS or Azure and a combination of both is not possible. 

Ideally the application instance could be configured with multiple `ICredentialFactory` instances, allowing the user to load credentials from multiple sources. On each listener/sender/pipe that uses the `authAlias` attribute, a new attribute named `authAliasFactory` should be added to choose a certain instance.

Requirements:
- When not specifying any additional `ICredentialFactory` instances, there should be no need to specify the `authAliasFactory`
- When multiple `ICredentialFactory` instances has been configured, the first specified class should be considered as the default,. Developers should only set `authAliasFactory` for credentials that are loaded from secondary sources.

**Comment by nielsm5** [comment]
A CompositeCredentialFactory should be created, the order of the factories should dictate in which order an alias should be looked up.
