### ISSUE TITLE
AmazonS3FileSystem folder exists check doesn't work as expected due the flat structure of S3

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6136]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Let's say we upload a file named `test.txt` at `/a/b/test.txt` without explicitly running MKDIR on these folders. The file is succesfully uploaded to S3, however when I try to list what is in `/a/b`, the `folderExists()` method returns false for `/a/b`.

I need to explicitly run MKDIR on `/a/b` before uploading the files for the `folderExists()` method to work correctly.

For further details, see: https://stackoverflow.com/questions/33565321/aws-s3-listobjects-returns-incomplete-directory-listings

**Comment by nielsm5** [comment]
Since release [7.9](https://github.com/frankframework/frankframework/pull/5220) we have an explicit check to verify if the folder exists to keep the behaviour over all FileSystems persistent. I'm unsure how to proceed here 😧

**Comment by nielsm5** [comment]
I've created a PR to make all FileSystems more consistent, however this functionality does already seem to be present.
There is a `createFolder` attribute which creates the folder before 'creating' the file.
