### ISSUE TITLE
SoapOutputWrapper add xml declaration feature

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6139]
When pipeline has a `soapOutputWrapper`, the xml declaration of the wrapper input is skipped and no option to put it back in wrapper is provided.

**Reporter**
Ali

FF: any

**Comment by jjansenvr** [comment]
add a attribute named omitXmlDeclaration and default it to true
add the xml declaration to the result when is set to omitXmlDeclaration=false
