### ISSUE TITLE
Truncate adapter dropdowns

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6150]
'Test a Pipeline' & 'Add/Edit Scheduler' pages have a dropdown to select an adapter where it displays the adapter name and descriptions as the options.
The options in the dropdown should be truncated to a max length of characters (100 or 150) so that it fits nicely enough on most screens.

**Comment by Matthbo** [comment]
Interesting
```{{adapter.value.name + adapter.value.description != null ? (" - " + adapter.value.description) : "" | truncate:150}}```
Has to be changed to
```{{adapter.value.name + (adapter.value.description != null ? (" - " + adapter.value.description) : "") | truncate:150}}```
In order to not mess it up, maybe angular templates get evaluated differently than I thought

**Comment by Laurens-makel** [comment]
> Interesting `{{adapter.value.name + adapter.value.description != null ? (" - " + adapter.value.description) : "" | truncate:150}}` Has to be changed to `{{adapter.value.name + (adapter.value.description != null ? (" - " + adapter.value.description) : "") | truncate:150}}` In order to not mess it up, maybe angular templates get evaluated differently than I thought

It's not specifically Angular templates or typescript, this expression would be interpreted the same in any language. The string concatenation would occur before the null check.

**Comment by Matthbo** [comment]
> > Interesting `{{adapter.value.name + adapter.value.description != null ? (" - " + adapter.value.description) : "" | truncate:150}}` Has to be changed to `{{adapter.value.name + (adapter.value.description != null ? (" - " + adapter.value.description) : "") | truncate:150}}` In order to not mess it up, maybe angular templates get evaluated differently than I thought
> 
> It's not specifically Angular templates or typescript, this expression would be interpreted the same in any language. The string concatenation would occur before the null check.

That's an interesting order of evaluating the expression, I guess I never really put a lot of thought behind it.
Regardless, I won't forget this anytime soon 😅
