### ISSUE TITLE
Improve visibility of error message summary on status page

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6159]
Issue #6097 explains how it isn't clear enough that error messages have occurred (without error store enabled).
![image](https://github.com/frankframework/frankframework/assets/4380412/57922fcf-8076-455f-8275-cd3c59356afa)

Solution would be to make the Error Messages summary text red and the summary count red and bold when its bigger than 0

**Comment by Matthbo** [comment]
![image](https://github.com/frankframework/frankframework/assets/4380412/8158cf19-65ee-405c-b879-62d6d1d54df5)
![image](https://github.com/frankframework/frankframework/assets/4380412/2558e4df-aac0-423a-b0f3-e03ca2967956)

@nielsm5 @philipsens which one of these styling options do you think would be best in this case?
Or maybe I should only apply the styling to the counter instead of the whole table row?

**Comment by philipsens** [comment]
> ![image](https://private-user-images.githubusercontent.com/4380412/303304751-8158cf19-65ee-405c-b879-62d6d1d54df5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTUzNDAsIm5iZiI6MTcwNzM5NTA0MCwicGF0aCI6Ii80MzgwNDEyLzMwMzMwNDc1MS04MTU4Y2YxOS02NWVlLTQwNWMtYjg3OS02MmQ2ZDFkNTRkZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTIyNDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThmMGIyZDI0Nzg3MmRhMGI2ZWQ1MDA2ODdiN2Q5ZGJjNmJlZDllY2M4YjRlZWNhZmI2ZGNkMjMwYjEwOWFiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZvtJ54p9D6UcjnY2S7EtyEDuQrlC5pufxdl5kVegddk)

This one stands out best, which I think is desirable. 

> My idea was to make it not spring out too much with the underline but noticeable if you're looking for it, but I can imagine that some people still wont notice that errors have occurred

I'm affright for the latter.

**Comment by nielsm5** [comment]
I think the red underline may not be 'aggressive' enough. On the other hand I know people will complain when there's too much 'red' in the console. 

I though perhaps, (and I know this is a bit more resource intensive,) in the adapter messages, when an error message exists < 60 minutes, make the adapter status (green bar) yellow/red. That way when it's 'been there' for 'a while', the red will go...

**Comment by philipsens** [comment]
> I though perhaps, (and I know this is a bit more resource intensive,) in the adapter messages, when an error message exists < 60 minutes, make the adapter status (green bar) yellow/red. That way when it's 'been there' for 'a while', the red will go...

But then it might still get unseen. Maybe this should only count after the user has 'seen' it.
