### ISSUE TITLE
IbisLocalSender async originalMessage is closed by parent

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6177]
**Describe the issue**
While delegating data to a sub-adapter (with the originalMessage) when
- synchronous is set to false
- the main adapter directly closes after delegating to a sub-adapter

The original message is closed by the main adapter, and can no longer be used in the sub-adapter.

**Reporter**
Jeroen/Ali

**Comment by nielsm5** [comment]
Also need check the senderseries (parallel sender) which might also need to implement message#copy() in some places.

**Comment by tnleeuw** [comment]
ParallelSender seems to always wait for all embedded senders to finish, but ShadowSender can collect results and send them on elsewhere in the background so it also needs some fixes.

For both we might need to do `message.preserve()` if the message is not repeatable.
