### ISSUE TITLE
Make config warnings click-able and show the element in show configuration of which it originated from

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6184]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Recently a button/link was added to view a specific adapter in the `Show Configuration` page. It would a great addition if similair mechanics are applied to configuration warnings.

I'd like to be able to click a configuration warning, be redirected to the `Show Configuration` page and the element that threw the warning should be visible and highlighted.

**Comment by nielsm5** [comment]
When line information is known it's already possible to jump to that bit of code in the configuration xml.

**Comment by philipsens** [comment]
@Laurens-makel could you give some examples for warnings where this could be added to? Like Niels said, this is possible for warnings where line number is known.
