### ISSUE TITLE
Frankframework is not getting deployed in the tomcat

### ISSUE THREAD

**Issue by ramanjulu-decos** [frankframework/frankframework#6215]
I have taken latest and tried to run the application in my local, tomcat server started successfully but looks like application is not getting deployed onto it. Please find the screenshots attached below.

![image](https://github.com/frankframework/frankframework/assets/138098789/7b73ec07-23da-4776-b38f-1d3975b9ef4d)

It's been in starting state forever

![image](https://github.com/frankframework/frankframework/assets/138098789/8b10a06c-102f-4606-b542-b04a77d5ed4b)

Your help much appreciated, Thanks.

**Comment by nielsm5** [comment]
I don't see any indication of the Frank!Framework starting. We've recently changed our package names, can you confirm you've got no build errors in Eclipse?

**Comment by ramanjulu-decos** [comment]
Build is successful

![image](https://github.com/frankframework/frankframework/assets/138098789/a14a2ce0-cf6c-4539-80de-3ceecd0bfd39)

All the problems are talking about ',' expected

![image](https://github.com/frankframework/frankframework/assets/138098789/5f68c4e7-1701-47e6-b175-80f541f102e2)


I have cloned it as a separate project instead of taking a pull into the existing project, FYI.

**Comment by nielsm5** [comment]
I'm not too worried about the JavaScript errors, are you able to filter on Java errors?

**Comment by ramanjulu-decos** [comment]
@nielsm5 No java errors, only Javascript errors. Taken latest today again, built it, done maven -> update project, restarted eclipse, ran server -> clean... and started server but still not getting app deployed

![image](https://github.com/frankframework/frankframework/assets/138098789/3f7a2d73-8a5c-4dae-ab7a-0bb9f50ccc75)

**Comment by ramanjulu-decos** [comment]
I am able to deploy generated webapp war in a separate tomcat instance which is working fine as expected but in eclipse iaf-example is not getting deployed, any thoughts?

**Comment by nielsm5** [comment]
No idea, but it does look like Eclipse is having issues somehow 😞
Have you tried going through our common issues yet?
https://github.com/frankframework/frankframework/blob/master/CONTRIBUTING.md#in-some-cases-you-might-wantneed-to
