### ISSUE TITLE
JavascriptSender supports only old ES5/partial ES6 and gives practically no feedback when using unsupported syntax

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6239]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Would be nice if the supported JavaScript version was mentioned somewhere in documentation. Supporting a more modern JavaScript version would be great too. The current version is from almost 10 years ago.

Also would be handy to have the framework automatically transpile the JavaScript code to its supported JavaScript version. Just like Babel does for supporting older browsers. 

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
function validateAndReplaceKeys(obj, parentKey = '') {
    for (const key in obj) {
        if (obj.hasOwnProperty(key)) {
            if (/^\d/.test(key)) {
                if (parentKey === '') {
                    newItemKey = `item${key}`;
                } else {
                    newItemKey = `${parentKey}${key}`;
                }
                obj[newItemKey] = obj[key];
                delete obj[key];
            }

            if (typeof obj[key] === 'object' && !Array.isArray(obj[key])) {
                parent = key;
                validateAndReplaceKeys(obj[key], parent);
            }
        }
    }
}

function replaceXmlIllegalElementNames(obj) {
    json = JSON.parse(obj);
    validateAndReplaceKeys(json);
    return JSON.stringify(json);
}
```

**Environment**
```
FF! 8.1.0-20240111.192324: Openforms2bpel 1.0.0
Running on 00ec8e5bbf7c using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (11.0.22+7)
Heap size: 546M, total JVM memory: 1056M
Free disk space: 202GB, total disk space: 251GB
Up since: 2024-02-05 15:22:15 (19h) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
Lastig, dit hebben wij niet in de hand. Wij willen tzt [de nieuwe GraalVM JS engine](https://github.com/frankframework/frankframework/issues/5496) gaan implementeren. Ook daar is het beperkt hoe ES6 compatibiel we zullen zijn.. Zie https://www.graalvm.org/latest/reference-manual/js/JavaScriptCompatibility/
