### ISSUE TITLE
Generated OpenAPI definition has wrong references under responses.

### ISSUE THREAD

**Issue by rvdstel** [frankframework/frankframework#6243]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The generated openapi.json shows a schema reference under responses we think is not correct. For instance : 

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/GetDocument_Request"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/GetDocument_Request"
                                }
                            }
                        }
                    },

The "GetDocument_Request" refers to the request and not to a response.
Is this something we can modify with the Json2XmlValidatorPipe or is this a bug? 

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**
I can share XSD's and adapter xml's via email.

**Input**

**Environment**
FF version is: FF! 7.8.3-hotfix1

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
How important is this for you? Is it blocking?

**Comment by rvdstel** [comment]
No, it is not blocking. Another team reported this issue, because they used the swagger.json to generate code. When testing this generated code, it failed, because the actual responses were not according to the swagger.json.
They manually changed the code so they could continue.

**Comment by jjansenvr** [comment]
should we do a rework on the whole thing? 
also related #6384
