### ISSUE TITLE
Use inline image for Mermaid

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6261]
**Describe the issue**
Is is possible to use inline images when using Mermaid like it is done with Graphviz?

To not overload the browser when opening the adapters status page I would suggest to not generate the images until a user is clicking on an adapter to see more information.

**Reporter**
Jaco de Groot

**Comment by nielsm5** [comment]
What happens when somebody clicks the 'expand-all' button? The browser screen should not crash when there are more then 250 adapters. (This was the case and the reason it's not inline. Not sure if browsers are 'better' or Angular has dramatically improved over AngularJS...)

**Comment by jacodg** [comment]
Maybe in that case we can only show a limited amount (or none) inline and show a button in that area which the user can press to show the image inline?

**Comment by Matthbo** [comment]
So instead of opening a popup/modal you click on a button or text to make it generate inline instead?
I guess if you click on the generated mermaid image it should still open the modal

**Comment by jacodg** [comment]
Yes, that would be handy. Say you open a number of adapters and you want to see/demo them and scroll a bit through the page it would be nice to have them show the inline images while scrolling up and down and see the images instead of having to open them one by one and after closing you can't see them again until you open the popup again.
