### ISSUE TITLE
Copy button for Mermaid image

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6263]
**Describe the issue**
SG would like to have a copy button to copy the flow image generated by Mermaid to the clipboard to be able to paste it into their documentation.

**Reporter**
Jaco de Groot

**Comment by Matthbo** [comment]
This is going to take some effort to figure out.
Mermaid.js generates and shows the image as an SVG which makes sense when using it in a browser but will be hard if not impossible to convert to a JPEG or PNG image when copied.
