### ISSUE TITLE
(Re)move statics in Message class to an utility class

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6298]
**Describe the issue**
Static methods in the class Message are abused to cast data to other types, message should only be used as pipe(line) input/result, and not for intermediate type casting of data.

- [ ] Documentation in Message class.
- [ ] Type safe utility methods (in utility classes), meaning not use an `Object` as parameter.

**Reporter**
Core Team

**Comment by akshitk20** [comment]
Hi @nielsm5 

I'm having a bit of trouble understanding the issue description. Could you please provide some more details or clarify a few points for me?

1. In Message class there are static methods. One method **(asMessage)** takes  Object as parameter. So we need to pass Message in place of Object here?

2. What is the expectation for below like do we have to add documentation for this 
Documentation in Message class.



Thanks in advance for your help!

**Comment by nielsm5** [comment]
Right now we have an `Message.asString(Object ...)` method, which is 'misused' by many implementations in order to turn an Object into a Message, just in case it's of type `Message`. The same is happing for `Message.asByteArray(Object ...)`

These methods should firstly be moved to MessageUtils, and via tests should ensure that they do not close the underlaying message.

The `Message.asMessage(Object ...)` should also be typed, so it no longer takes any type of Object.

The Message class needs to be documented to reflect these changes. Any `asSomething` method should convert the data but not close the Message. This should only be done when close has explicitly been called.

**Comment by akshitk20** [comment]
Hi @nielsm5 

I am not able to push feature branch to this repo. could you give me write access

**Comment by nielsm5** [comment]
Hi @akshitk20, we don't hand out access. Pull-requests can be opened via a fork 😃 !

**Comment by evandongen** [comment]
I've created #7078 for the more extensive / places to be researched in the codebase.

**Comment by evandongen** [comment]
`asByteArray` and `asString` are done for now, but `asMessage` still needs to be refactored.
