### ISSUE TITLE
Maven build with profile attachFrankDoc does not work with Java 21 - Lombok issue

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#6344]
The Maven build of the Frank!Framework fails if the following are both true:
* Java 21 is used.
* Profile attachFrankDoc is active.

Here is the error:

```
[INFO] Frank!Framework full bundle ........................ SKIPPED
[INFO] Frank!Framework webapp ............................. SKIPPED
[INFO] Frank!Framework Test ............................... SKIPPED
[INFO] Frank!Framework example ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.904 s
[INFO] Finished at: 2024-02-23T13:23:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.20.0:delombok (default) on project frankframework-commons: Unable to delombok: InvocationTargetException: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR]
```

**Reporter**
Martijn Dirkse

**Additional Context**
I found the following about this error: https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n. You need Lombok 1.18.30, but we have that one already. I checked that we are not sneaking in a lower version:

```
martijn@LAPTOP-R1SK28C MINGW64 ~/git/frankframework (fixBuildForJava20WithAttachFrankdoc)
$ mvn21 dependency:tree | grep "lombok"
[INFO] +- org.projectlombok:lombok:jar:1.18.30:provided
....
[INFO] \- org.projectlombok:lombok:jar:1.18.30:provided
[INFO] \- org.projectlombok:lombok:jar:1.18.30:provided

martijn@LAPTOP-R1SK28C MINGW64 ~/git/frankframework (fixBuildForJava20WithAttachFrankdoc)
$
```

**Comment by jkosternl** [comment]
Yes, you are right. I can confirm this behavior with Java 21. We need to find out why it happens, or preferably to avoid delomboking (if that is possible).

**Comment by nielsm5** [comment]
I think it's a good idea to remove de delombok step altogether. We hardly use it, and so far it's been giving us a lot of trouble.
In order to remove lombok we should compare the lombok and delombok'd sources, find the few differences, and solve those.
Then we can remove the delombok step.

**Comment by jkosternl** [comment]
I've just investigated if we can remove the whole `delombok` step, but we can't, unfortunately. The Javadoc tool needs the unwrapper version without the Lombok annotations. It is also state at the website of Lombok itself: https://projectlombok.org/features/delombok

I'll continue in making the delombok step working with Java 21.

**Comment by nielsm5** [comment]
> I've just investigated if we can remove the whole `delombok` step, but we can't, unfortunately. The Javadoc tool needs the unwrapper version without the Lombok annotations. It is also state at the website of Lombok itself: https://projectlombok.org/features/delombok
> 
> To get the `delombok` step working with Java 21: The `lombok.maven` plugin needs an update, but the maintainer does not really maintain the project, it seems. [projectlombok/lombok#3596](https://github.com/projectlombok/lombok/issues/3596)
> 
> I've sent the maintainer an email regarding an outstanding PR which fixes the issue in Java 21.

I don't understand your comment...

**Comment by mhdirkse** [comment]
If all setters that produce an attribute or config child are written out (no @Setter annotation, a real setXxx method), then the Frank!Doc doclet is almost happy. It uses the getters for the following two purposes:

* If for an attribute there is a setter and a getter, the return type of the getter is checked. If the return type differs from the argument type of the setter, the Frank!Doc produces an error.
* If for an attribute setter setXxx there is also a getter named getXxxEnum(), then the return type of getXxxEnum() is expected to be an enum and that enum type is set as the enum type of the attribute. Attributes in general have a type, and attributes of type string can have an enum type in addition.

Only a limited number of getters should be important for the Frank!Doc. If only these are manually de-lombok-ed and if all others remain Lombok-ed with @Getter, then the delombok build step can be eliminated without changing the Frank!Doc. The Frank!Doc trace log may be used to find the getters that are relevant for the Frank!Doc. If you want, I can add some log statements to the Frank!Doc to support this.

**Comment by nielsm5** [comment]
I only found 2 enum suffix fields; `JdbcQuerySenderBase#getQueryTypeEnum()` and `JMSFacade#getAcknowledgeModeEnum()`.
We can easily convert those to 'proper' enums.

The checks if the getters and setters match do not matter as much anymore because we also test this in the `MapPropertyDescriptorsTest`. I suppose that if the getter is not available the Frank!Doc does not run the validation for the field/setter in question?

**Comment by mhdirkse** [comment]
Correct. If the getter is absent (or not seen because of Lombok), the type check does not happen.

**Comment by jkosternl** [comment]
> If all setters that produce an attribute or config child are written out (no @Setter annotation, a real setXxx method), then the Frank!Doc doclet is almost happy. 

@mhdirkse, I do not get the Javadoc generation working properly without the `delombok` step. Here is the output:
```
MavenReportException: Error while generating Javadoc:
[ERROR] /Users/jkoster/projects/iaf/core/src/main/java/org/frankframework/jdbc/JdbcFacade.java:66: error: cannot find symbol
[ERROR] 	private final @Getter(onMethod = @__(@Override)) String domain = "JDBC";
[ERROR] 	                                  ^
```
Besides the `@__`, it also can not parse/compile the `onMethod` itself. I am now discussing this with Tim and Niels.
