### ISSUE TITLE
Feature request: Supply org.opencontainers.image.revision OCI label with commit sha on framework Docker images

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6355]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
To enable automatic updating of custom code when updating to the latest framework version, we would need some way to figure out which commit is the last commit included in the framework image we are updating to. Master branch can have changes that are not released in the framework image yet. 

It would be great if the `org.opencontainers.image.revision` OCI label could be added to the framework image with the commit sha that triggered the build.

Example OCI labels from `docker inspect <image>`:
```
"Labels": {
                "org.opencontainers.image.created": "2024-02-26T10:45:58.926Z",
                "org.opencontainers.image.description": "An app for Dutch municipalities that supports the transition from \"zaak- en documentatieservices\" (zds) to \"zaakgericht werken\" (zgw).",
                "org.opencontainers.image.licenses": "EUPL-1.2",
                "org.opencontainers.image.ref.name": "refs/heads/master",
                "org.opencontainers.image.revision": "0f2394c454e7af88b26a1057dd4f74ab44010557",
                "org.opencontainers.image.source": "https://github.com/wearefrank/zaakbrug",
                "org.opencontainers.image.title": "zaakbrug",
                "org.opencontainers.image.url": "https://github.com/wearefrank/zaakbrug",
                "org.opencontainers.image.version": "1.15.12"
}
```

**Reporter**
M. Lenterman

**Comment by philipsens** [comment]
I've added a little helper to generate label arguments in the JSL: https://github.com/frankframework/jenkins-shared-library/blob/master/utility/vars/kaniko.groovy
It has been added to the CI so the coming Frank!Framework images should have the labels.
