### ISSUE TITLE
"servers" empty in https://frank2example.frankframework.org/iaf/api/webservices/openapi.json?uri=/mundo

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6373]
See title

**Comment by nielsm5** [comment]
That's because it's running behind a reverse proxy, setting the property `loadBalancer.url` will fix this.

**Comment by jacodg** [comment]
I saw/see the same thing (empty "servers") when running locally with the Frank!Runner. I'm quite sure I've seen it having a value locally but would need to retest.

**Comment by jacodg** [comment]
I see this issue is closed so I added a new issue for my last comment: https://github.com/frankframework/frankframework/issues/6384

**Comment by nielsm5** [comment]
The Frank2Example shows property `loadBalancer.url` empty on env vars page.

**Comment by philipsens** [comment]
A new version has been deployed. 

![image](https://github.com/frankframework/frankframework/assets/12416423/3b094357-daa4-4868-a709-5239dd7138b0)
