### ISSUE TITLE
test a pipeline (from a zip file) does not work when the files are in the root of the zip

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#6406]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When resending items via test a pipeline I need to unzip and rezip (wit a root folder in the zip) for the test-a-pipeline to work 

**Reporter**
jjansenvr

**To Reproduce**
1. you could download (n) messages from the errorstore 
2. go to test a pipeline and select the created zipfile
3. send it and see it will not process anyu of the files inside
4. unzip the file to a folder
5. zip the folder 
6. retry with new zip (this works)

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Matthbo** [comment]
Everything on the Console frontend seems to be the same in both cases, its the API that gives a different response based on the different zips (one download vs one self made)

**Comment by Matthbo** [comment]
The same response, so it has something to do with how the zip is generated when user wants to a zip from (error)store.
I can open the zip fine with 7zip so no issues there, clearly the content is also not corrupted or anything so that cant be it either

**Comment by Matthbo** [comment]
I downloaded the blob from the API and manually told my pc it was a zip, so either the blob is wrong or there needs to be an addition step done which also isnt done in the Console front-end
