### ISSUE TITLE
Console: decide and set boundaries for code conventions

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#6411]
Discuss on and try out enforcing a new set of conventions.

For example; keep code explicit
```ts
public subscription: Subscription = new Observable(() => {}).subscribe({ next: () => {} });
```
Instead of
```ts
subscription = new Observable(() => {}).subscribe(_ => {});
```

**Comment by philipsens** [comment]
A private repo has been made. Tweaks will still be done in the background, but this isssue can be closed.
