### ISSUE TITLE
Console: after Reload Configuration button, the adapter names are not reloaded

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#6423]
After `Reload Configuration` button:
1. A renamed adapter is not picked up by the Console. 
2. New entries in `Configuration Messages` are not refreshed.

If you run a F!F Console, with e.g. an adapter `exampleadapter` and you change the name in the file, to `exampleadapter2` and click the `Reload Configuration` button, the new adapter name is not displayed and the old name stays in the list. This is causing issues if you click at one. 

If the adapters are reloaded, after the finishing of the reload configuration, this is fixed. E.g. as it is fetched at: http://localhost/iaf/api/adapters
The same problem also is valid for the contents/lines inside `Configuration Messages`. Can you address that as well?

**Reporter**
J. Koster

**To Reproduce**
See above. 
<img width="960" alt="Scherm­afbeelding 2024-03-11 om 13 12 36" src="https://github.com/frankframework/frankframework/assets/29304914/64a4c869-97cd-4dd2-8df8-7d2ecdfb8442">

**Configuration**
Any example configuration will do.

**Environment**
Verified with `FF! 8.1.0-20240308.042334`

**Comment by Matthbo** [comment]
https://github.com/frankframework/frankframework/commit/3472b8a32a7c67f769e09ee132fe43d4f6da3677 solved this issue, together with https://github.com/frankframework/frankframework/pull/7108
