### ISSUE TITLE
Wrong password leads to (DDOS) like reconnect. 

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#6424]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When the database connection has an wrong password it keeps on trying (in a DDOS like way)

it would be nice to have a different reconnect approach on wrong password than on a timeout.

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
While my attached pr wont solve all the issues, it will certainly reduce it by at least 50%
