### ISSUE TITLE
elementToMove does not restore the value in the message in case of an exception

### ISSUE THREAD

**Issue by rvdstel** [frankframework/frankframework#6438]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The elementToMove functionality on the receiver does not restore the value when there is an exception.
When an incoming message runs into an exception, the message is stored in the errorstore, but the content of the element now only contains: 
`<fileContent>{sessionKey:ref_fileContent}</fileContent>`
The original value is lost !
When we can resend the message again, we get the error:
Error : Pipe [Base64ToStream] getInputFromSessionKey [ref_fileContent] is not present in session

**Reporter**
Richard van der Stel 

**To Reproduce**

**Screenshots**

**Configuration**

**Input**
Mail send to Niels with ladybug report and message.

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
FF! 7.9.1

**Comment by jjansenvr** [comment]
needed for upgrade of ibis4titan
