### ISSUE TITLE
JdbcTableListener error store cant handle filename as storageID

### ISSUE THREAD

**Issue by diedekerkhof** [frankframework/frankframework#6454]
**Describe the issue**
JdbcTableListener error store cant handle filename as storageID.

**Reporter**
@diedekerkhof

**Input**
StoreageID in message is: /opt/data/WAS/wasap08/fxf-work/NNX04734/inProcess/schade.edi.20240314120000018-2024-03-14T14_17_34.686 and the url to see the error contains / represented by %252F.

Maybe allowUrlEncodedPercent has someting to do with it

**Comment by nielsm5** [comment]
I'm unable to reproduce this. Can you confirm which FF version you're using?

**Comment by diedekerkhof** [comment]
https://github.com/frankframework/frankframework/issues/5748
https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/firewall/StrictHttpFirewall.html#setAllowUrlEncodedSlash(boolean)

`/iaf/api/configurations/Services/adapters/MFHProcessor/receivers/JdbcTableListener%20%5BIBISFILETRIGGER_listener%5D/stores/Error/messages/%252Fopt%252Fdata%252FWAS%252Fwasap08%252Ffxf-work%252FNNX04734%252FinProcess%252Fschade.edi.20240314120000018-2024-03-14T14_17_34.686`
