### ISSUE TITLE
Json2XmlValidatorPipe adding linebreaks to base 64 fields

### ISSUE THREAD

**Issue by BonnoSmeele** [frankframework/frankframework#6495]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
When using a jsonpipe to create JSON, base64  input seems to be wrapped. XSD is used and field is set to xs:base64Binary.

\n appears in JSON pipe output base64 field

**Reporter**
Bonno Smeele

Create a JSON pipe with base64 input,
see linebreaks appear as output
 
**Screenshots**
Input:
![image](https://github.com/frankframework/frankframework/assets/73215587/c997531b-f84d-4c35-bf85-b072d5e695ca)

Output:
![image](https://github.com/frankframework/frankframework/assets/73215587/1d61255b-d681-4587-91d2-c6e4868dcb67)

XSD:
![image](https://github.com/frankframework/frankframework/assets/73215587/ccc2e311-3ba1-441e-818a-b71f47025a44)

Please provide the configuration of the Pipe or Receiver with the problem.
```
			<Json2XmlValidatorPipe name="XMLToJSONConversion"
				outputFormat="JSON"
				throwException="true"
				root="PortimaRequest"
				schema="PushPolicy_1/xsd/JSONModel.xsd">
				<Forward name="success" path="CallInvokeAzuretoken"/>
			</Json2XmlValidatorPipe>
[Pipeline PushPolicy_1.zip](https://github.com/frankframework/frankframework/files/14720801/Pipeline.PushPolicy_1.zip)

```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 7.9.1: frank2lifepolicy_portima_con
Running on frank2lifepolicy-portima_con-app-acc using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (11.0.22+7-LTS)
Heap size: 198M, total JVM memory: 603M
Free disk space: 25GB, total disk space: 30GB
Up since: 2024-03-22 09:42:04 (1h)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
You can try setting `lineLength=-1` on the Base64Pipe
