### ISSUE TITLE
empty message not empty when ApiListener is streaming the message.

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6496]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I use an apilistener in the receiver. ApiListener passes the received message as an inputstream to the pipeline. 
In this case the payload is empty string

![image](https://github.com/frankframework/frankframework/assets/10929856/db5222cf-2394-44b5-b081-f4197f6067c2)

1. The pipeline has a pipe XMLToJSONConversion with  skipOnEmptyInput="true". I still see the pipe in the pipeline in ladybug. Not sure what to expect for this attribute but it is also not clear from the logs if it was skipped. Moreover, xmlInput sessionKey(result of this pipe) seems to be filled with the input.

2. In CreateFindDetailedFundMessage I have this basic logic `<param defaultValue="&lt;dummy/&gt;" name="xmlInput" sessionKey="xmlInput" type="DOMDOC"/>` . This throws an error since the xmlInput is stream. But I'd expect xmlInput not to be in the session at all.

Attaching 2 reports (streaming one and the other is just empty string without streaming)
 

**Reporter**
Ali

[Pipeline DispatchAPI_stream.zip](https://github.com/frankframework/frankframework/files/14720950/Pipeline.DispatchAPI_stream.zip)

[Pipeline DispatchAPI_string.zip](https://github.com/frankframework/frankframework/files/14720955/Pipeline.DispatchAPI_string.zip)

FF: 7.9.1

**Comment by nielsm5** [comment]
Hey!

So I understand the confusion here. What's happening is that the pipe is skipped, and the result of the pipe is stored in the session. The result of this pipe is the input, as it's being skipped (seems to work fine, indeed a bit strange how that works).

Your XsltPipe seems to be unaware that the input is empty, and gives you an exception (which contains the input message's info).
