### ISSUE TITLE
Exception configuring SenderPipe [Call LDAP to RemoveLDAPgroup]: while configuring sender: [nl.nn.adapterframework.ldap.LdapSender] Context could not be found

### ISSUE THREAD

**Issue by Htou** [frankframework/frankframework#6498]
ERROR: Error initializing adapter [DeleteAgentUser]: Exception configuring SenderPipe [Call LDAP to RemoveLDAPgroup]: while configuring sender: [nl.nn.adapterframework.ldap.LdapSender] Context could not be found : cannot create InitialDirContext for ldapProviderURL [ldaps://rw.t-direp.biz:636/ou=VA,ou=DI-IUF-EP,ou=Services,DC=T-direp,DC=biz]: (CommunicationException) rw.t-direp.biz:636: (UnknownHostException) rw.t-direp.biz

Upgraded: ja-toegang in the test envoirment to version 7.9.1. but a  lot of adapters are not starting up.

**Comment by nielsm5** [comment]
Seems to be an DNS issue, the new instance cannot resolve the name `rw.t-direp.biz`
