### ISSUE TITLE
CleanupOldFilesPipe does not work

### ISSUE THREAD

**Issue by Htou** [frankframework/frankframework#6546]
Inputmessage should contain filename directory, or directory to filename.

filePattern: This attribute specifies the pattern for files that should be deleted. The parameters of the pipe are applied to this pattern. If this attribute is not set, the input of the pipe is interpreted as the file to be removed.

filePatternSessionKey: If filePattern is not set, this session key contains the pattern of files to be deleted. It’s used as an alternative way to specify the file pattern.

lastModifiedDelta: This parameter defines the time in milliseconds after the last modification that must have passed before a file will be deleted. You can set a negative value to disable this feature.
subdirectories: When set to true, files in subdirectories will also be deleted.

deleteEmptySubdirectories: If set to true, empty subdirectories will be deleted as well.
wildcard: This attribute serves as a filter for files to delete. If not set and a directory is specified, all files in the directory are interpreted to be deleted.

excludeWildcard: Use this filter to specify files that should be excluded from deletion.

minStableTime: This parameter represents the minimal age of a file in milliseconds. It’s used to avoid deleting a file while it is still being written. Note that this is only applicable when the wildcard is set. You can set it to 0 to disable this feature.

**Comment by nielsm5** [comment]
We've decided to deprecate this pipe in the 7.9 and remove the pipe in the 8.0 onwards.
A good solution for removing all files with one pipe would be a [composite sender](https://github.com/frankframework/frankframework/issues/3270).

**Comment by nielsm5** [comment]
UploadFilePipe mag ook weg!

**Comment by tnleeuw** [comment]
@Htou Hichem, We will add labels such as "epic" and we will take care of closing the issue. Especially when we have already started doing some work related to the issue.
