### ISSUE TITLE
Add CSV/flexible option(s) for ApiListener consumes/produces attributes

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6556]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Given that I'd like to create an adapter which only accepts csv messages and exposes an API listener, I'd like to do this by setting the `consumes` attribute to `CSV`, however this option does not exist. 

![image](https://github.com/frankframework/frankframework/assets/37303445/b5285f64-6f25-4e19-a1b9-0418d82b5baf)

Given the above list, I'm not really able to leverage the `Content-Type` header check that the framework provides and I'd have to implement logic to manually check the header and handle un-happy situations.

I'd be happy if I could just set the consumes to `CSV`, however what if next time im writing an adapter which only accepts certain image formats? 

It would be great to have an option which allows the Frank developer to provide one or more content types that would be accepted, i.e `consumes="text/csv"` or `consumes="image/jpg,image/png"`.

**Comment by nielsm5** [comment]
We should create some form of rainbow table with content-types instead of our own fixed list.

**Comment by Laurens-makel** [comment]
Not exactly the same, but related #4420

**Comment by nielsm5** [comment]
> Given that I'd like to create an adapter which only accepts csv messages and exposes an API listener, I'd like to do this by setting

I've given this some thought but it's a bit more difficult to implement then I originally thought. The MimeType enum, which we currently use, has a `includes`, `isCompatibleWith` and `accepts` method. It is possible to rewrite it and allow users to enter their own mimetypes but then it becomes difficult to determine when people are allows to set a `charset` and when it's disallowed (for example binary data such as a pdf).
