### ISSUE TITLE
Pipes gone on statistics page

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6581]
**Describe the issue**
The pipes are not listed anymore on the statistics page.

**Screenshots**

![image](https://github.com/frankframework/frankframework/assets/2970084/675fdde0-f419-430a-8fd5-07f34520fe4b)

While there are several pipes in this adapter:

![image](https://github.com/frankframework/frankframework/assets/2970084/a7fedf69-abc0-4324-8179-c09f38917ddd)

**Environment**
FF! 8.1.0-20240330.042427: Frank2Example
Running on frank2example-77f5f7fd4b-bjfxq using Apache Tomcat/9.0.87
Java Version: OpenJDK Runtime Environment (17.0.10+7)
Heap size: 103M, total JVM memory: 270M
Free disk space: 223GB, total disk space: 501GB
Up since: 2024-03-30 05:46:35 (4d)

**Comment by nielsm5** [comment]
Only pipes that have been executed are shown (lazy loaded). The order will (always) be chronological, even when pipes are 'loaded/called' later.
