### ISSUE TITLE
Data disappeared in statistics graph

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6583]
**Describe the issue**

Before I executed HelloWorlds a couple of times:

![image](https://github.com/frankframework/frankframework/assets/2970084/8a85c4a0-4eb7-424b-9d12-6a2180f735b9)

After I just executed HelloWorlds a couple of times:

![image](https://github.com/frankframework/frankframework/assets/2970084/6b7af7df-f2c7-407c-b9ff-316747f0d222)

**Environment**
```
FF! 8.1.0-20240330.042427: Frank2Example
Running on frank2example-77f5f7fd4b-bjfxq using Apache Tomcat/9.0.87
Java Version: OpenJDK Runtime Environment (17.0.10+7)
Heap size: 81M, total JVM memory: 270M
Free disk space: 223GB, total disk space: 501GB
Up since: 2024-03-30 05:46:35 (4d) 
```

**Comment by nielsm5** [comment]
While adapters statistics have been refactored, this is the only functionality that has been untouched since #462.

**Comment by nielsm5** [comment]
I think that it may have been possible that you were looking at data from the previous day. The message at 2 am is a cron trigger, and the statistics are not cleaned up until a new message has been processed.
