### ISSUE TITLE
using a include in a config xml 

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#6643]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I would like to use a regular sort of an include tag to add a xml code snipit to my adapterconfig.xml

I got it working with the stucture of adding entety refs in the configuration xml

```
<!-- reusable pipeline parts can be used in any underlying configuration -->
<!ENTITY Errorhandling SYSTEM "Generic\parts\genericErrorhandling_1_0_0.xml">
<!ENTITY Errorhandling_RR SYSTEM "Generic\parts\genericErrorhandling_1_0_0_RR.xml">

and
&Errorhandling;

at the place where I want to include it
```

Xinclude is not supported by saxon HE so wondering if this is possible

**Reporter**
jjansenvr

**Comment by nielsm5** [comment]
See https://github.com/frankframework/frankframework/blob/master/test/src/main/configurations/HTTP/Configuration.xml
