### ISSUE TITLE
Test a pipeline does not load the configurations in dropdown

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6699]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Browse https://frank2example.frankframework.org/iaf/gui/#/test-pipeline click configuration dropdown. There is no data loaded and the field can be edited like a text field.

**Reporter**
Ali

**Comment by philipsens** [comment]
We've used a browser native data-list for the input. Can you tell me which browser you are using? Data should be loaded in an "autocomplete" window. The configuration can be selected or typed.

Due to browser differences and user settings, it could be best to create a custom component for this.

**Comment by alisihab** [comment]
both chrome and edge giving me the same

**Comment by philipsens** [comment]
> Oh I see you meant this. not sure about the use case of typing though 

That functionality was requested here: #5893
