### ISSUE TITLE
Download all active configurations button

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6725]
**Describe the issue**
It would be great to have a download all configurations button which downloads all active configurations instead of having to browse each individual page, look for the active one and download it.

**Comment by jacodg** [comment]
What is the use case? You cannot find the configurations in Git?

**Comment by Laurens-makel** [comment]
The same use cases that apply for downloading a single jar file?

For example when you would have to upload all configurations on ACC to PRD during a deployment?
