### ISSUE TITLE
Upgrade Tika to most recent version or maintain tika-mimetypes.xml

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6743]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Due to an upgrade from 7.7.3 to 7.8.5, the Apache Tika library has been upgraded from 1.14.0 to 1.28.5. Usually it's great that dependencies are updated to their last possible versions, however this time the `tika-mimetypes.xml` in Tika has changed and failed to recognize certain files as `.eml` which was possible in 1.14.0 before.

For now we have manged to override the `tika-mimetypes.xml` and patch the file to fix the above problem. However the 1.X range of the Tika lib is not maintained anymore, thus any latest changes to file recognition patterns won't be included in the framework.

Is it possible to upgrade to 2.X or 3.X range of the Tika lib? If not, please consider maintaining the `tika-mimetypes.xml` as your responsibility..

**Tika is used for detecting mime type not only in Aspose, but for the whole framework! The current version used is of September 2022, it's important to keep up-to-date with magic byte matching patterns!**

**Comment by nielsm5** [comment]
We're using the 1.x branch for websphere. But it's indeed now possible to upgrade to the 2.x branch 😄

**Comment by Laurens-makel** [comment]
> We're using the 1.x branch for websphere. But it's indeed now possible to upgrade to the 2.x branch 😄

Just for personal interest, could you elaborate on this? Why is it not compatible with WAS?

**Comment by evandongen** [comment]
Some migration is necessary, check out https://cwiki.apache.org/confluence/display/TIKA/Migrating+to+Tika+2.0.0 for more information
