### ISSUE TITLE
ExecuteJdbcQuery.getJdbcInfo tries to sort an UnmodifiableList

### ISSUE THREAD

**Issue by erikvandongen** [frankframework/frankframework#6752]
**Describe the issue**
I'm working through the Frank Manual and encountered an error in the JDBC handling. Everything was done as it should, but it didn't work 

**Reporter**
Erik van Dongen

**To Reproduce**
1. Go to https://frank-manual.readthedocs.io/en/latest/gettingStarted/horizonsInitialData.html#solution
2. Click on 'download' to get the working solution
3. Set up a Frank with these contents
4. See that "JDBC > Execute Query" results in a server error (red box in the top right)
4.1 Same error comes up in "Security Items" page. 

**Screenshots**
<img width="1152" alt="screenshot_jdbc_error" src="https://github.com/frankframework/frankframework/assets/168641874/08d2adb6-2475-42c2-9845-d2f5f48d6655">

**Configuration**
```
See steps to reproduce
```

**Input**
```
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableList.sort(Collections.java:1523) ~[?:?]
	at org.frankframework.management.bus.endpoints.ExecuteJdbcQuery.getJdbcInfo(ExecuteJdbcQuery.java:63) ~[frankframework-core-8.2.0-20240429.225021.jar:8.2.0-20240429.225021]
```

**Environment**
```
FF! 8.2.0-20240429.225021: Frank2Manual
Running on laptop-erik using Apache Tomcat/9.0.88
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 96.6 MiB, total JVM memory: 189.0 MiB
Free memory: 92.4 MiB, max memory: 1.0 GiB
Free disk space: 776.3 GiB, total disk space: 927.7 GiB
Up since: 2024-05-02 15:16:51 (27m)
```

**Additional Environment**
 - DBMS: H2 (default setup)
 - Browser: Chrome 124.0.6367.92

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Matthbo** [comment]
Relevant for #6755
