### ISSUE TITLE
JDBC Generated Keys support for all databases

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#6795]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
JDBC support for getting generated keys from the database is only partially supported. There is still code to query tables for highest key value, or special support for getting the value from sequence manually.

All this code can now be cleaned up with modern drivers.

**Reporter**
Tim van der Leeuw

**Comment by evandongen** [comment]
Tim, I don't see how your changes are implementing what is described in the issue. Can you explain how these changes enable you to get generated keys from the database?
