### ISSUE TITLE
Show configuration warning/exception when Json2XmlValidator is configured with throwException=true and has a failure forward defined

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6800]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
FrankDoc states the following:
![image](https://github.com/frankframework/frankframework/assets/37303445/3e6835b9-3c30-4c37-bab1-84d4af5628bf)

It would a nice addition to give a configuration warning/exception indicating that the failure forward is ignored when a failure forward is defined and the Json2XmlValidator is configured with `throwException="true"`.

**Reporter**
Laurens

**Comment by evandongen** [comment]
In `XmlValidator#configure` i see the following code:
```
			if (!isForwardFailureToSuccess() && !isThrowException() && findForward("failure") == null) {
				throw new ConfigurationException("must either set throwException=true or have a forward with name [failure]");
			}
```
Isn't this what you describe?

**Comment by Laurens-makel** [comment]
@evandongen 
The above code block checks if a failure forward is defined or throwException is set to true and gives a warning that either must be set.

My suggestion is to check if both are defined `isThrowException () && findForward("failure") != null`, then give a warning that the failure forward will be ignored.
