### ISSUE TITLE
When a new user starts the FF! with the Frank!Runner, he sees a warning

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#6833]
![image](https://github.com/frankframework/frankframework/assets/6784732/6fa8a704-82f2-4d7e-b97d-31bd4eeb18a4)

**Describe the issue**
When you start the FF! you see a warning that has nothing to do with the configuration you supplied. The shown screenshot was produced by starting the FF! using the Frank!Runner.

Someone has to update IAF_Util, I would expect.

**Reporter**
Martijn Dirkse

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 8.1.0-RC2-20240508.012135: v500
Running on LAPTOP-R1SK28C using Apache Tomcat/9.0.88
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 92M, total JVM memory: 169M
Free disk space: 126GB, total disk space: 464GB
Up since: 2024-05-16 13:24:08 (16m)
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Erik told me that the Frank applications that are in the Frank!Manual produce warnings. I am fixing that. To complete this, we also have to fix the warnings that are not caused by the Frank!Manual.

**Comment by mhdirkse** [comment]
Kan het core team beslissen wie dit gaat oplossen. Ik zou het zelf kunnen proberen als core dat wil.

**Comment by nielsm5** [comment]
Not related to the framework, this is an intentional warning.
The Frank!Runner may choose to suppress this warning by setting `warnings.suppress.sqlInjections.ManageDatabase=true`.
