### ISSUE TITLE
https://frank2example.frankframework.org/ should show Ladybug

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#6857]
**Describe the issue**
Ladybug has temporarily been removed from the Frank!Framework because life cycle management of ladybug lags behind. Our demonstration website frank2example should still demo Ladybug, so I propose we power that site with an older version of the Frank!Framework.

![image](https://github.com/frankframework/frankframework/assets/6784732/092d5831-1efb-4d95-88d5-13a8ccadaebc)

**Reporter**
Martijn Dirkse

**To Reproduce**
1. Browse to https://frank2example.frankframework.org/iaf/gui/#/testing/ladybug

**Screenshots**

**Configuration**
```
FF! 8.2.0-20240522.042418: Frank2Example
Running on frank2example-768ff4fd58-22fnp using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (17.0.11+9)
Heap size: 123.3 MiB, total JVM memory: 210.0 MiB
Free memory: 86.7 MiB, max memory: 1.0 GiB
Free disk space: 250.3 GiB, total disk space: 500.6 GiB
Up since: 2024-05-22 05:45:56 (8h)
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by philipsens** [comment]
I've downgraded the Frank2example demo.
