### ISSUE TITLE
In the Frank!Console I can no longer press ctrl+enter to submit a form

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6865]
**Describe the issue**
In the Frank!Console I can no longer press ctrl+enter to submit a form.
I've only tested this in the 8.1 and 8.2

**Reporter**
Niels

**Comment by philipsens** [comment]
Solution: 
Directive that adds a keydown listener

**Comment by philipsens** [comment]
Pressing "Enter" in forms now submits them because of default behavior. But this messes with using enter to select in a dropdown.
It should be fixed again.
Also, a lot of the text areas that has a directive are replaces by Monaco Editor and don't have this behavior anymore.
