### ISSUE TITLE
Create an alternative for reading non-text files without the FilePipe

### ISSUE THREAD

**Issue by evandongen** [frankframework/frankframework#6927]
**Describe the issue**
We need an alternative for reading non-text files (sample.pdf for example), possiby combined with 'outputType' (stream/base64/binary) and 'streamResultToServlet'. FixedResultPipe only supports text. This applies to classpath resources, which isn't supported by the LocalFileSystemPipe.

This blocks the deprecation of the FilePipe, FileSender and FileHandler.

**Reporter**
Erik / core-team

**Configuration**
For instance, see this snippet from `ConfigurationFilePipe.xml` in the test project. We need to be able to read a binary file with the given outputType from the classpath. This is not possible with the FixedResultPipe and the LocalFileSystemPipe
```
<!-- Read binary file as bytes -->
<pipe
	name="read binary file as bytes"
	className="org.frankframework.pipes.FilePipe"
	actions="read"
	outputType="bytes"
	getInputFromFixedValue="FilePipe/file.pdf"
	fileSource="classpath">
</pipe>
<pipe name="encode binary file bytes" className="org.frankframework.pipes.Base64Pipe">
	<forward name="success" path="EXIT" />
</pipe>

<!-- Read binary file as stream -->
<pipe
	name="read binary file as stream"
	className="org.frankframework.pipes.FilePipe"
	actions="read"
	outputType="stream"
	getInputFromFixedValue="FilePipe/file.pdf"
	fileSource="classpath">
</pipe>
<pipe name="encode binary file stream" className="org.frankframework.pipes.Base64Pipe">
	<forward name="success" path="EXIT" />
</pipe>
```

**Input**
Configuration files affected:
  * `ConfigurationRestListener.xml`
  * `ConfigurationJmsBytesMessage.xml`
  * `ConfigurationBigClobAndBlob.xml`
  * `ConfigurationFilePipe.xml` - when this file is fully migrated, please rename it to something like `ConfigrationLocaleFileSystemPipe.xml`.

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. FF!: Ibis4Test
Running on laptop-erik using Apache Tomcat/10.1.23
Java Version: OpenJDK Runtime Environment (21.0.2+13-58)
Heap size: 288.9 MiB, total JVM memory: 432.0 MiB
Free memory: 143.1 MiB, max memory: 7.9 GiB
Free disk space: 778.5 GiB, total disk space: 927.7 GiB
Up since: 2024-05-31 15:48:48 (28m)
```

**Additional Environment**
- Tomcat 10.1.23 / java 21
- Browser: Chrome 125.0.6422.113

**Comment by nielsm5** [comment]
1. Deprecate `styleSheetName` attribute, people should use the `XsltPipe` (or `XsltSender`).
2. Deprecate `replaceTo`, `replaceFrom`, `replaceFixedParams` and `substituteVars`, people should use the `ReplacerPipe`.
3. `filenameSessionKey` should be a param, (may be both).
4. Ensure both character and binary data can be returned.
5. Potentially rename this pipe?

**Comment by evandongen** [comment]
In addition:
* Remove `returnString`, use `getInputFromFixedValue` with an `EchoPipe` instead

**Comment by evandongen** [comment]
Implemented everything, as described but we can't remove the FilePipe just yet since the FixedResultPipe can provide the binary file functionality only after the deprecated elements are removed.
