### ISSUE TITLE
XmlIfPipe regex attribute does not evaluate input correctly

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#6963]
There are 2 problems when using the `<XmlIfPipe regex="pattern">`. 
1. Using pattern `(hoi)+` does not match input message `hoi a hoi`. 
2. A multiline input message is not matched correctly. Perhaps if the first issue is solved, this one is solved too.

**Reporter**
jkoster

**To Reproduce**
1. Use `<XmlIfPipe regex="(hoi)+">`
2. Feed the pipe input `hoi a hoi`
3. Verify that `thenForwardName` and `elseForwardName` does not work as expected.

**Environment**
In current master, 8.2-SNAPSHOT at June 2024. Likely in many versions before. 

**Solution**
Use other pattern matching then `"string".matches(pattern)`, such as:
```
Pattern p = Pattern.compile(getRegex());
if (p.matcher(sInput).find()) {
	forward = thenForwardName;
} else {
	forward = elseForwardName;
}
```
And enable the disabled unit tests in `XmlIfTest.java`. 

Ideas of Niels: deprecate the `regex` attribute in `XmlIfPipe` and create a new real `RegExPipe`, to avoid backwards compatibility issues. 
But perhaps integration specialist will just move to the new one, keeping the pattern the same.

**Comment by nielsm5** [comment]
With Developer eXperience in mind, a new `RegExPipe` would be a better fit with all RegEx options such as (global match, case insensitive, multiline, singleline, unicode, etc) and with multiple forwards such as, no-match, match, etc.
Potentially even add captureing groups (and store them in a session.

**Comment by jkosternl** [comment]
> The pattern given in the example won't match `hoi a hoi`. It would only match the two `hoi` parts of the string. So, if I understand correctly, the real issue is that multiple matches won't work.

So, on the problem as defined at number 1: if there is a whole text line of input, I'd like it to get matched when I use pattern: `(sergi+)` when just your name is in that sentence. Currently, it does not get matched. But if the sentence got multi occurrences of your name, it should get matched too. So, multiple matches is not the right summary. 

Does that make sense and is clear enough @philipsens ?

**Comment by philipsens** [comment]
Thank yo for your quick reply. I still don't think I fully understand.

Do you want to match the whole sentence? Or should it be successful when finding any occurance?

The multiline problem is clear to me.

**Comment by jkosternl** [comment]
Matching the whole sentence is hard to achieve, because I was e.g. only looking for "sergi" and not for all the other words around it. And so I tried "(sergi+)" but that never matches. So, I guess it is your last sentence: successful when it finds any occurence.

**Comment by thomaspj10** [comment]
An idea on how it could be implemented:
```xml
<RegExPipe regex="(.*?) string!" flags="multiline,dotall,unicode">
    <Forward name="then" path="itMatchesPipe"/>
    <Forward name="else" path="itDoesntMatchPipe"/>
</RegExPipe>

<!--
mode: MATCH | FIND
MATCH: Matches the entire string, or nothing at all.
FIND: Finds all the matches in the given string.

Stores the match result (if successful) in a session key:

<matches>
    <match index="1" value="hoi">
        <group index="1">hoi</group>
    </match>
    <match index="2" value="hoi">
        <group index="1">hoi</group>
    </match>
</matches>
-->

```

**Comment by jkosternl** [comment]
Yes, I trust you can find a different regex to solve the same, but that was not the intend of this issue. Otherwise, I'd create an task as "Find an regex that does match X given the context Y", or fix it myself already for the given situation 😉 

The idea is that this pipe can work more intuitive, as explained in the description. 
But as Niels already suggested me in the past, probably it is not a good idea to change the behavior of this pipe, because of backwards compatibility issues.
