### ISSUE TITLE
XmlIfPipe should refuse to startup, when no xpathExpression or regex is given

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#6964]
If no `xpathExpression` or `regex` is supplied in the pipe configuration, no error or warning is displayed or given. This is not correct, because one of them are required to work as expected. 

**Expected behavior**
Give a ConfigurationException when e.g. this is used: 
`<XmlIfPipe name="output-check" thenForwardName="answerOk" elseForwardName="ERROR"/>`
and refuse to start up the pipe. Making it very clear it is used incorrectly.

**Comment by evandongen** [comment]
When implementing this, we found out that the proposed solution doesn't take another scenario into account. Discussed this with Niels and we decided to _not_ implement this
