### ISSUE TITLE
New Ladybug frontend endpoint no longer works

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6979]
**Describe the issue**
Figure out of it actually is CSRF related by turning it off (or run locally, which disables it).
Fix the issue.

**Reporter**
Sergi

**Comment by Matthbo** [comment]
Ladybug works fine with CSRF enabled in local environment (runnning in IDE). However I did check the logs on frank2example.frankframework.org and they show this, which seems to indicate a build error through our CI**CD** @philipsens 

Larva does seem to have issues when CSRF is enabled so I'll keep looking into that

![Image](https://github.com/frankframework/frankframework/assets/4380412/93f8d7c5-b851-4a62-9a09-a9ca9cdb335a)

**Comment by nielsm5** [comment]
Fixed in https://github.com/wearefrank/ladybug/commit/f559450ed8915a565321e47de3617c9a453dd21a
