### ISSUE TITLE
Refactor/migrate AWS api to v2

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6981]
**Describe the issue**
A new version of the AWS spec exists, we are still using:
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk
but ever since 2017 the new api:
https://mvnrepository.com/artifact/software.amazon.awssdk/s3
also exists.

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>bom</artifactId>
      <version>2.24.3</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

There is a [migration guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-steps.html) available.

**Reporter**
Core/Tim

**Comment by evandongen** [comment]
s3mock isn't fully compatible with AWS api v2. We need to implement an alternative first, see #7120

**Comment by evandongen** [comment]
#7120  has been merged to master. With that change, we're already using AWS api v1 with the (adobe) s3mock testcontainer image. The PR for this ticket includes the same testcontainer functionality but is using the AWS api v2.
