### ISSUE TITLE
Secure JSP compilation

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#6996]
### Related Problem or Business Case

Runtime JSP compilation is a security risk.

### Describe the Feature

At first I thought it would be a good idea to disable JSP compilation on Tomcat, but this might be too aggressive.
It might be better to allow JSP's but to disallow them from being reloaded.

The property `modificationTestInterval` [should be set to a high value](https://tomcat.apache.org/tomcat-8.0-doc/jasper-howto.html#Production_Configuration). 

More info can be found here: https://stackoverflow.com/questions/678469/can-a-tomcat-web-app-programmatically-change-the-jsp-servlets-development-true

### Collaboration with External Companies

No, community resolution only

**Comment by jkosternl** [comment]
We only see 3 JSPs in our FF project. Suggestion from the refinement meeting: recompilation can be turned off. Normal compilation, does that hurt existing JSP files? If no, turn off.

**Comment by thomaspj10** [comment]
Setting the `development` flag to false, will still allow JSPs to execute, but changing the source code of the JSP does not re-compile it. I think that this is a better and neater solution then setting the `modificationTestInterval` to a high value without having any significant drawbacks.

The following URL can be used to test the aforementioned behaviour:
http://localhost:8080/iaf-test/test.jsp?nr=hello
