### ISSUE TITLE
Double jar icu4j

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7002]
### Is your Frank! up to date?

8.2.0-20240614.042327

### Current Behavior

When starting with Frank!Runner it says:
    The following double jars are found: icu4j
    In folder C:\ ... \frank-runner\examples\Frank2Example4/../Frank2Example4/src/main/webapp/WEB-INF/lib

### Expected Behavior

No warning

### Environment Information

FF! 8.2.0-20240614.042327: Frank2Example4
Running on xxx using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 137.6 MiB, total JVM memory: 174.0 MiB
Free memory: 36.4 MiB, max memory: 1.0 GiB
Free disk space: 26.5 GiB, total disk space: 474.9 GiB
Up since: 2024-06-15 11:05:15 (2m) 

### Steps To Reproduce

Strart Frank2Example1 or 4 with Frank!Runner

**Comment by jkosternl** [comment]
Input from meeting: it also happens when starting with Docker.

**Comment by evandongen** [comment]
If I take a look at the list of dependencies, I see two icu4j dependencies:
* First one is in the 'core' project: `+- com.ibm.icu:icu4j:jar:74.2`
* Second one is a transitive dependency from graal js / graalvm in the 'ladybug' module:
```
[INFO] |  +- org.graalvm.polyglot:js-community:pom:24.0.1:runtime
[INFO] |  |  +- org.graalvm.js:js-language:jar:24.0.1:runtime
[INFO] |  |  |  +- org.graalvm.regex:regex:jar:24.0.1:runtime
[INFO] |  |  |  +- org.graalvm.truffle:truffle-api:jar:24.0.1:runtime
[INFO] |  |  |  \- org.graalvm.shadowed:icu4j:jar:24.0.1:runtime
```

**Comment by jacodg** [comment]
Some more info:
![image](https://github.com/frankframework/frankframework/assets/2970084/4eeda863-2ccc-4a11-b0a0-a721c8a92415)

**Comment by jacodg** [comment]
Ok, Frank!Runner will ignore them: https://github.com/wearefrank/frank-runner/commit/c1622e9e54b2bcdfe7ead027f4d3cd623f64d464
