### ISSUE TITLE
Add GitHub Star button in console

### ISSUE THREAD

**Issue by nielslam** [frankframework/frankframework#7011]
### Related Problem or Business Case

Enhancing user engagement by integrating a GitHub Star button directly in the console encourages users to support and promote the Frank!Framework. 

### Describe the Feature

A visible GitHub Star button in the console header that replaces the current 'leave feedback' stars.
Clicking the button redirects to the Frank!Framework GitHub repository for starring.

Something like [this](https://buttons.github.io/), or just create a link to leave a GitHub Star.

### Collaboration with External Companies

No, community resolution only

**Comment by philipsens** [comment]
Something like this? 
![image](https://github.com/frankframework/frankframework/assets/12416423/40c0b221-3f85-48ba-92de-5d529745caf2)

**Comment by nielsm5** [comment]
Text is not very clear/intuitive... 

![Image](https://github.com/frankframework/frankframework/assets/4375703/e5ac712a-2375-411b-9e82-32948a4099ce)

Perhaps `* on GitHub` and less whitespace between the icon and text (or a button).

**Comment by philipsens** [comment]
Or ⭐ on :octocat: :^)

**Comment by philipsens** [comment]
![image](https://github.com/frankframework/frankframework/assets/12416423/b8da91f7-9458-4afd-9a79-89f2c961c63e)
Idk

**Comment by nielslam** [comment]
Maybe we could just use the standard GitHub button for this? [https://buttons.github.io/](https://buttons.github.io/)

![image](https://github.com/frankframework/frankframework/assets/16138468/6b788baf-03de-467c-b9ce-3c9172560ebb)

**Comment by philipsens** [comment]
> Maybe we could just use the standard GitHub button for this? https://buttons.github.io/
> 
> ![image](https://private-user-images.githubusercontent.com/16138468/342324797-6b788baf-03de-467c-b9ce-3c9172560ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzAwNzksIm5iZiI6MTcxOTIyOTc3OSwicGF0aCI6Ii8xNjEzODQ2OC8zNDIzMjQ3OTctNmI3ODhiYWYtMDNkZS00NjdjLWI5Y2UtM2M5MTcyNTYwZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExNDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZWZjNmVhZTU4Zjc5MzUyMmM4NjcyMTU1NDhjNzE4ZjI2N2RiNDBjYThjMjUwN2RhMzRhODYyM2Y1YTI2OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ocg4V1wwQfCbjKzAyuT28A-87syXy4BRNMKXTNa12KE)

We would need additional JavaScript and requests to services outside the console

**Comment by philipsens** [comment]
The whitespace after LOC is also too large. I don't think it is very useful to put a lot of time in fixing the styling.

**Comment by philipsens** [comment]
Ended up like this: 
![image](https://github.com/frankframework/frankframework/assets/12416423/8aeef392-7894-492e-b3d2-3bb12890fe8b)
