### ISSUE TITLE
Bar at top of page keeps "loading"

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7014]
### Is your Frank! up to date?

8.2.0-20240614.042327

### Current Behavior

In Firefox the green loading bar of the top of the page doesn't disappear:

![image](https://github.com/frankframework/frankframework/assets/2970084/09ac43e9-fefa-4a49-bb91-41ccb0329e39)

### Expected Behavior

No green bar after the page has been loaded

### Environment Information

FF! 8.2.0-20240614.042327: Frank2Example1
Running on XXX using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 151.0 MiB, total JVM memory: 254.0 MiB
Free memory: 103.0 MiB, max memory: 1.0 GiB
Free disk space: 26.1 GiB, total disk space: 474.9 GiB
Up since: 2024-06-17 19:00:38 (1m)

### What browsers are you seeing the problem on?

Firefox

**Comment by nielsm5** [comment]
Of stopzetten na 3 seconden, of vervangen door iets nieuws.
