### ISSUE TITLE
Browse Tables shows one record (by default) while "Rownum max" is 0

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7020]
### Is your Frank! up to date?

8.1.0

### Current Behavior

When I go to Browse a JDBC Table, insert table name in the "Table name" field and press Send it will show me one record which gives me the feeling there is only one record in the table. As "Rownum max" has value 0 (by default) but still one record is returned it suggest it returns unlimited number of records.

### Expected Behavior

Zero records returned when "Rownum max" is 0 and "Rownum max" being filled with 1 by default (or even better 10 or so).

### Environment Information

FF! 8.1.0: Frank2Example1
Running on XXX using Apache Tomcat/9.0.89
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 77M, total JVM memory: 238M
Free disk space: 26GB, total disk space: 475GB
Up since: 2024-06-18 10:00:46 (1h)

**Comment by nielsm5** [comment]
Set default min to `1` and max to `100`.

**Comment by philipsens** [comment]
I also have an issue with `Rownum max: 100` and `Rownum min: 0`, it will show nothing, until I increase the `Rownum min`

**Comment by Matthbo** [comment]
This is because the difference between rownum min & max cant be 100, the bus gave an exception back for this but it wasn't handled properly
