### ISSUE TITLE
Autofill some values of the Bug Report form when using the `Report a Bug` button

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#7024]
### Related Problem or Business Case

Filing a Bug is quite a bit of work, but users want to get on with their work. The large (but necessary) issue template discourages to file a bug.

### Describe the Feature

Pre-fill some of the values when using the `Report a Bug` button in the console.

I think at lease "Environment" should be pre-filled.

### Collaboration with External Companies

No, community resolution only

### Anything else?

Related #7010

**Comment by nielsm5** [comment]
Versie veld weghalen, environment prefillen.
