### ISSUE TITLE
Message attribute is missing in frank!Doc for Job

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#7027]
### Is your Frank! up to date?

7.9.3 till latest online version

### Current Behavior

https://frankdoc.frankframework.org/#/All/Job

it does not show a message attribute to use in conjunction with the function sendmessage 

### Expected Behavior

I would like to see all elements 

### Environment Information

7.9.3 till latest online version

**Comment by nielsm5** [comment]
Job is the old placeholder to make old configurations work. The framework attempts to set attributes but cannot guarantee anything. If you wish to use autocompletion you will have to choose a specific 'job' implementation, such as [SendMessageJob](https://frankdoc.frankframework.org/#/Scheduling/SendMessageJob). Which has the attributes that can be set on that, and only that, element.
