### ISSUE TITLE
Make the use of OpenJDK distributions consistent

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#7032]
### Related Problem or Business Case

While searching for development environment requirements, I found that Azul Zulu is the preferred OpenJDK distribution. 
I was surprised to see this, because (as long as I know) we build and distribute the Frank!Framework with Temurin. We build using the `eclipse-temurin` Docker image and we distribute the Frank!Framework Docker image, based on `tomcat:10.1.24-jre17-temurin-jammy`. 

I couldn't find any reason to why we use this version, except that Jaco had some experience with it (https://github.com/frankframework/frankframework/pull/2833). I also found that before this got added to the `CONTRIBUTING.md`, Ali already started using it in the GitHub Actions (https://github.com/frankframework/frankframework/pull/2358).

So I think it is a bit confusing, and if not, it is at least inconsistent.

### Describe the Feature

Make a concise choice and _go with it_. 
I've been using Temurin, and because it is driven by a [community](https://www.eclipse.org/org/) and not a [company](https://www.azul.com/about/), it has my favour.

### Collaboration with External Companies

No, community resolution only

### Anything else?

> <img src="https://github.com/frankframework/frankframework/assets/12416423/977a3185-4c7e-424c-abd0-330c669fcc2d" alt="what-is-the-difference-between-azul-openjdk-zulu-openjdk-and-openjdk" width="200" />
> 
> From: https://stackoverflow.com/questions/61335109/what-is-the-difference-between-azul-openjdk-zulu-openjdk-and-openjdk

**Comment by nielsm5** [comment]
Alles temurin maken. (Documenation + GitHub Actions)
