### ISSUE TITLE
CheckSumPipe output turns into string data which results in faulty Base64Encoded output

### ISSUE THREAD

**Issue by Thermalight** [frankframework/frankframework#7047]
### Is your Frank! up to date?

8.2.0-20240621.042325

### Current Behavior

The checksumpipe hashes input and returns a hexadecimal string. 
When this string is converted to base64 with the Base64Pipe, the result is calculated using character encoding instead of the hexadecimal value of the hexstring.

### Expected Behavior

I want the Base64Pipe to convert from hexadecimal to base64 when a hexstring is provided, or be able to retrieve a bas64 encoded version after hashing.

### Environment Information

FF! 8.1.0-RC2-20240508.012135: frank2openbanking
Running on DESKTOP-1R1U3IC using Apache Tomcat/9.0.88
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 151M, total JVM memory: 236M
Free disk space: 59GB, total disk space: 350GB
Up since: 2024-06-21 09:16:00 (19m)

### Steps To Reproduce

Create an adapter with the following pipes:

<ChecksumPipe name="CreateHexString" getInputFromFixedValue="Hello World!" type="SHA256" />

<Base64Pipe name="ConvertHexToB64" />

### Configuration

```xml
<Adapter name="HexToB64">
  <Receiver name="HexToB64Receiver">
    <ApiListener uriPattern="b64" name="HexToB64Listener" />
  </Receiver>
  <Pipeline>
    <Exits>
      <Exit name="Success" state="SUCCESS" />
      <Exit name="Error" state="ERROR" />
    </Exits>

    <!-- Hash Hello World with the sha256 algorithm  -->
    <ChecksumPipe name="CreateHexString" getInputFromFixedValue="Hello World!" type="SHA256" />
    <!-- Convert the hexstring to base64 -->
    <Base64Pipe name="ConvertHexToB64" />

  </Pipeline>
</Adapter>
```

### What browsers are you seeing the problem on?

Chrome

**Comment by nielsm5** [comment]
Related #6622. I think we should (somehow) merge the 2 pipes first, and see how we can create a proper, uniform pipe-output.

**Comment by evandongen** [comment]
`ChecksumPipe` is capable of generating a 'hash' of a given message (file or string) using an algorithm. With this, you can prove **integrity** of the message. 
`HashPipe` uses Mac implementations of algorithms. A Mac algorithm uses a secret, combined with the algorithm to create a 'hash' of a message. Only sources which have this secret are able to generate the same hash for the given message. With this, you can prove **integrity** and **authenticity** of a message.

With this in mind we need to decide whether we want to keep these two implementations and perhaps want to extend the `ChecksumPipe` with a parameter to control the output format (Hex/Base64). The `HashPipe` already has this option. If we decide to keep these, we need to add clear documentation on when and how to use them, preferably with examples.

Also see: https://stackoverflow.com/a/3696947/956884
