### ISSUE TITLE
JdbcTransactionalStorage warning for missing index while it exists

### ISSUE THREAD

**Issue by diedekerkhof** [frankframework/frankframework#7089]
### Is your Frank!Framework up to date?

No, I can't update

### Current Behavior

When the index for IBISSTORE are created in a different order then in the IAF_DatabaseChangelog, it gives a warning that the index still needs to be created.

expected by framework: table [IBISSTORE] has no index on columns [SLOTID,MESSAGEID]
but if the index is created in a different order it doesnt see the index example:
[MESSAGEID,SLOTID]

This is with all the indexes from the IAF_DatabaseChangelog.xml

### Expected Behavior

The framework needs to check if the index has the columms and not only in the one order defined by the framework

### Environment Information

Its hosted on Websphere but the error also happens local

### Steps To Reproduce

Launch an Frank with no database yet, where the SLOTID and MESSAGEID have switched places in the IAF_Util:1b. (in IAF_DatabaseChangelog.xml)

### Configuration

```xml
The warning displayes when a JdbcTransactionalStorage is used that needs the ibisstore table
```

### Input

-

### What database are you using?

Oracle

### What browsers are you seeing the problem on?

Chrome

### Relevant Log Output

```console
JdbcTransactionalStorage [errorStorage of [testtool-DeleteResults]] table [IBISSTORE] has no index on columns [SLOTID,MESSAGEID]
```

**Comment by Laurens-makel** [comment]
The order of columns specified in the index have impact on the performance of the index.

It's like a dictionary, its very inefficient to lookup by message id first and then by slot id. The correct approach is to lookup messages by slotid and then by message id,. 

See the following for more info:
https://stackoverflow.com/questions/2292662/how-important-is-the-order-of-columns-in-indexes

**Comment by nielsm5** [comment]
Considering the performance impact this may have on the database we recommend creating a new index with the correct order.
