### ISSUE TITLE
Cache/EhCache element name mismatch between between Frank!Doc, ff-test and FrankConfig.xsd

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#7110]
### Is your Frank!Framework up to date?

Yes I've updated and the bug still exists

### Current Behavior

Frank!Doc references `EhCache` as the caching mechanism element name, while the FrankConfig.xsd or f!f don't allow this. Instead it expects the element to be named `Cache`. However the FrankConfig.xsd won't accept any attributes that are shown in ff-test under `cache` or the ones referenced under `EhCache` in Frank!Doc. Additionally the use-case of adding a `cache` in a SenderPipe seems to be not accepted anymore.

### Expected Behavior

- Use the same name between Frank!Doc, FrankConfig.xsd and ff-test.
- More clear documentation/examples on the usage of the caching mechanism

### Environment Information

FF! 8.1.0-20240404.042328: ZaakBrug 1.19.14
Running on d2d6f882944e using Apache Tomcat/9.0.87
Java Version: OpenJDK Runtime Environment (17.0.10+7)
Heap size: 506M, total JVM memory: 2192M
Free disk space: 178GB, total disk space: 251GB
Up since: 2024-07-03 15:45:29 (12m)

**Comment by nielsm5** [comment]
Good to know, the [@ff.defaultElement](https://github.com/frankframework/frankframework/blob/2234e907c02269b9d8a2e02b0cc6bb95a85c18ab/core/src/main/java/org/frankframework/cache/ICache.java#L28) annotation is present on the ICache interface. Not sure why the JSON and XSD are giving mixed results...

**Comment by thomaspj10** [comment]
It has since been silently fixed and works correctly on the latest version. Closing this issue.
