### ISSUE TITLE
In the Console Test a Pipeline clear selected adapter on configuration switch

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7143]
### Current Behavior

This issue was observed by opening Frank2Example1 in the Frank!Runner. It has two configurations, namely Example1a and Example1b. Configuration Example1a contains Adapter1a and Example1b contains Adapter1b. I am in Test a Pipeline and have Example1b and Adapter1b selected, see figure:

![image](https://github.com/frankframework/frankframework/assets/6784732/6dd01fe4-8ede-4cf4-a21b-6ed6a13ae7f9)

If I open the dropdown to select a configuration, the only choice I see is Example1b, there is no Example1a. I can type Example1a to select it. Then I see a red error window to the top right that vanishes before I can read its text. I see a warning in yellow now that Adapter1b does not exist, above the dropdown to select a configuration.

What does work is that I can take Adapter1a and run it.

### Expected Behavior

When I open the dropdown to select a configuration I should have the options Example1a and Example1b. If I change from Example1b to Example1a, the chosen adapter should be made empty or it should be changed to an adapter that exists within configuration Example1a.

### Environment Information

FF! 8.2.0-20240711.042331: Frank2Example1
Running on LAPTOP-R1SK28C using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 125.7 MiB, total JVM memory: 270.0 MiB
Free memory: 144.3 MiB, max memory: 1.0 GiB
Free disk space: 116.9 GiB, total disk space: 464.3 GiB
Up since: 2024-07-11 16:58:43 (11m)

**Comment by Matthbo** [comment]
Its a special input field which updates the options based on what's already been typed in, if you were to have `Example` typed into it you would see both `Example1a` and `Example1b` as the available options

**Comment by mhdirkse** [comment]
Als je een andere configuratie kiest, misschien kan dan het veld voor de adapter geleegd worden? Nu blijft de text die er was staan als filter. Dat werkt in dit geval verwarrend.
