### ISSUE TITLE
Unclear why ApiListenerServlet could not read mime multipart request

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#7159]
### Current Behavior

A new consumer is trying to send multipart messages to our API however the API only responds with 400 Bad Request `Could not read mime multipart request`.

When checking the application's log files, it does indeed mention that it could not read it, but the reason why is left out.
 
![image](https://github.com/user-attachments/assets/1999f651-d1d6-42a4-a7c5-e59501af72e9)

In the underlying code, the exception message is not handled at all:
![image](https://github.com/user-attachments/assets/16e3b79d-b432-4deb-be9f-b9206f8f4d64)

### Expected Behavior

The exception message should be included in the log statements and kept out of the API response for security by obscurity reasons

### Environment Information

FF! 7.9.2: X 32-7.9-b556420
Running on x.x.xusing IBM WebSphere Application Server/9.0.5.19
Java Version: Java(TM) SE Runtime Environment (8.0.8.21 - pxa6480sr8fp21-20240221_01(SR8 FP21))
Heap size: 1254M, total JVM memory: 1536M
Free disk space: 9GB, total disk space: 12GB
Up since: 2024-07-11 12:41:11 (4d)

### Steps To Reproduce

Not sure on how to reproduce, observed when a consumer sent a message through UIPath..

### Configuration

```xml
<Receiver name="X">
            <ApiListener
                    name="X"
                    uriPattern="x/x"
                    method="POST"
                    consumes="MULTIPART"
                    multipartBodyName="body"
                    authenticationMethod="AUTHROLE"
                    authenticationRoles="IbisWebService"
                    produces="JSON"
            />
        </Receiver>
```

### Input

Don't have input or a Ladybug report since this doesn't hit an adapter.

### What database are you using?

MSSQL

### What browsers are you seeing the problem on?

Chrome

### Relevant Log Output

```console
2024-07-15 15:53:50,492 WARN  [WebContainer : 0] {} rest.ApiListenerServlet - Aborting request issued by [X] with status code [400],  Could not read mime multipart request
2024-07-15 15:53:54,118 WARN  [WebContainer : 0] {} rest.ApiListenerServlet - Aborting request issued by [X] with status code [400],  Could not read mime multipart request
2024-07-15 15:54:27,904 WARN  [WebContainer : 4] {} rest.ApiListenerServlet - Aborting request issued by [X] with status code [400],  Could not read mime multipart request
2024-07-15 15:55:41,023 WARN  [WebContainer : 4] {} rest.ApiListenerServlet - Aborting request issued by [X] with status code [400],  Could not read mime multipart request
```

**Comment by nielsm5** [comment]
Oh boy that's a bit silly...
