### ISSUE TITLE
In Test a Pipeline, boundaries of input fields are not visible on my monitor

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7179]
### Related Problem or Business Case

Not applicable.

### Describe the Feature

When I open Test a Pipeline, it looks as follows:

![image](https://github.com/user-attachments/assets/34525ecc-0bb9-45b4-a8a0-c76e2806d887)

On my machine in the WeAreFrank! office, I do not see boundaries of the "Configuration", "Select an adapter" and "Message" fields. I have to search these fields by moving the mouse around and clicking. When I click on the right spot, the boundary I need appears:

![image](https://github.com/user-attachments/assets/6fca6252-2988-4f0b-933c-083845b0a1b9)

Requested behavior is that this boundary is visible immediately when Test a Pipeline is opened, prefarably in another color to indicate it is not selected.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
You're claiming it does not work at your office location, but it works in other locations? The website does not change depending on location, so maybe there's some external factor that may effect this, such as your monitor's contrast-ratio?

**Comment by mhdirkse** [comment]
Ja, het is inderdaad alleen op het werk. Als ik mijn WeAreFrank! laptop, dezelfde als toen ik last had van dit issue, thuis aansluit, dan ziet Test a Pipeline er goed uit. Het plaatje dat bij deze PR zit ziet er dan ook goed uit.

Ik zou het kunnen vast kunnen oplossen door op het werk de settings van mijn monitor te veranderen, maar misschien hebben andere gebruikers ook onverwachtse instellingen voor hun monitor. Misschien is het toch goed om de kleuren te veranderen in de FF! frontend code.

**Comment by nielsm5** [comment]
Duidelijk, dan weten we waar het vandaan komt!

**Comment by Laurens-makel** [comment]
@nielsm5 @mhdirkse 
Ik ervaar dit probleem ook op mijn goedkopere monitor.

Ik ben het met Martijn eens, als je met een simpele kleur change het contrast op de pagina zelf kan verbeteren, dan help je de groep gebruikers met goedkopere monitors :)

**Comment by Laurens-makel** [comment]
> @mhdirkse @Laurens-makel How does this look on your screens? I turned down the lightness of the border around the input fields.
> 
> ![Image](https://private-user-images.githubusercontent.com/4380412/357464800-b5742872-2ea9-4fff-997b-353f2cb2476a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjM4NjksIm5iZiI6MTcyMzU2MzU2OSwicGF0aCI6Ii80MzgwNDEyLzM1NzQ2NDgwMC1iNTc0Mjg3Mi0yZWE5LTRmZmYtOTk3Yi0zNTNmMmNiMjQ3NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTUzOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRkMTBmNGFkMzJjMWRiN2FlNDQzODA0ZjJmOTViYzlmNGM4MGZmZDU4N2JkYzJkOTE2ZTE5ZDI4YTVlNTVkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VGjIloK640Q3yA2EIKgHtKLqPhwno7OVpKDGwtW98OA)

Too bad I can't share screenshots of this :)

In the current frank2example, I see barely any difference between the input fields.
In the screenshot you shared, the outline of the fields is clearly visible, it helps to identify the input fields

How does it look when an input field has been selected? Could you share a screen so I can share my thoughts?

**Comment by nielsm5** [comment]
A selected field remains unchanged (green border).

**Comment by mhdirkse** [comment]
Hello @Laurens-makel . I cannot check this anymore because Niels adjusted my monitor for me. After this adjustment, the borders looked fine before this issue was solved.
