### ISSUE TITLE
Document in the Frank!Doc how to test ApiListener with curl

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7186]
### Related Problem or Business Case

I was testing my Frank config that had an ApiListener. I observed that I could do my test with HTTP client Bruno, but that I got an unexpected result using curl. With curl, my data was not properly received by the pipeline. In Ladybug, I could see that there was a session key that had the curl data as its name. The input message of the pipeline was empty.

The problem was that curl added a header `Content-Type: application/x-www-form-urlencoded`. When you add to your curl command the option `-H 'Content-Type:'`, the test behaves as expected. @tnleeuw told me that we should not update the FF!. The FF! behaves as expected because it can expect form data because of the header and because there is no form data. On the other hand, I believe integration specialists should be informed about this caveat.

### Describe the Feature

I propose we add the information in a comment in ApiListener.java to add it to the Frank!Doc. Here is a proposal for the text:

```
/**
 * Listener that allows a {@link Receiver} to receive messages as a REST webservice.
 * Prepends the configured URI pattern with <code>api/</code>. The structure of REST messages is described
 * by OpenAPI specifications. The Frank!Framework generates an OpenAPI specification for each ApiListener and
 * for all ApiListeners in all configurations combined. You can
 * find them in the Frank!Console under main menu item Webservices, heading Available ApiListeners.
 * <p>
 * NOTE: There is a caveat when you want to test your ApiListener using curl. By default, curl adds
 * header <code>Content-Type: application/x-www-form-urlencoded</code>. To omit it, add the following
 * option to your curl command: <code>-H 'Content-Type:'</code>.
 * <p>
 * The generated OpenAPI specifications have <code>servers</code> and <code>paths</code> objects and
 * therefore they document the full URLs of the provided services.
 * <p>
```

The first and the third paragraph shown here are existing text. My proposal is to add the middle paragraph.

This is not in a pull request because I do not have a proper development enviroment to test this update. When I build the FF! with the Frank!Runner, the Frank!Doc I see is empty. Can someone from core do this edit for me and check the result in the Frank!Doc?

### Collaboration with External Companies

No, community resolution only

### Anything else?

I do not see an input field anymore to state my name. Martijn Dirkse wrote this.

**Comment by mhdirkse** [comment]
Hm, lastig. Nu ik het teruglees staat mijn toevoeging op een te prominente plek in de Frank!Doc. Als we dit opnemen, dan moet het meer onderaan, tussen de andere details.

**Comment by mhdirkse** [comment]
Of ik doe het in de Frank!Manual bij de questions and answers; dat hebben we ook.

**Comment by mhdirkse** [comment]
The -H option I am writing about in the issue did the trick under MinGW, but not in a DOS prompt.

**Comment by tnleeuw** [comment]
> The -H option I am writing about in the issue did the trick under MinGW, but not in a DOS prompt.

How do you start curl from a DOS prompt? Are you sure that it is actually curl that is starting, same application as that is running under MinGW?

According to this post, what you start as "curl" in a "DOS Prompt" (or PowerShell window, really) might be an alias for a PowerShell command:

https://stackoverflow.com/a/16216825/3588231

**Comment by nielsm5** [comment]
This is a caveat of CURL not of the framework. When using CURL with a post request, CURL attempts to autofill some headers for you. 

I am opposed to adding this. It is the responsibility of the person using the tool to know what he or she is doing. Otherwise we would have to document things like this for every single http tool that may be able to send/receive http data.
