### ISSUE TITLE
Allow JDBC datasource name to be passed via parameter

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#7189]
### Related Problem or Business Case

NN has some adapters where datasource name needs to be determined at runtime, not static during configuration.

### Describe the Feature

NN has custom code to allow passing a datasource-name for JDBC senders via a parameter.
It appears useful to add this as feature to the framework, using their changes as basis.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
Closing this as we don't intend to merge this.
