### ISSUE TITLE
Update WildFly image

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7239]
### Related Problem or Business Case

WildFly 32.0.1 is released: https://www.wildfly.org/news/2024/05/31/WildFly3201-Released/

### Describe the Feature

Newer WildFly image

### Collaboration with External Companies

No, community resolution only

**Comment by philipsens** [comment]
https://www.wildfly.org/news/2024/07/23/WildFly33-Released/ even newer

**Comment by nielsm5** [comment]
Maybe a good idea to add the docker image version updates to dependabot.
