### ISSUE TITLE
Fix BrowseQueue isNotEmpty bug

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7240]
### Current Behavior

During a refactor a null check was turned in an not-empty (instead of empty) check.

### Expected Behavior

A test + empty check

### Environment Information

7.9 +

**Comment by Matthbo** [comment]
https://github.com/frankframework/frankframework/pull/7180/files#diff-0d49602b930a3209a80b3aff16b5fa4d00bf07b012b27578543cc7ca63ff1b6bR56-R58
