### ISSUE TITLE
Console backend endpoints should have 80%+ test coverage

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7241]
### Related Problem or Business Case

We have very many silly errors in our console backend, adding tests now should prevent issues in the furture.

### Describe the Feature

Make this page green: https://app.codecov.io/gh/frankframework/frankframework/tree/master/console%2Fbackend%2Fsrc%2Fmain%2Fjava%2Forg%2Ffrankframework%2Fmanagement%2Fweb

### Collaboration with External Companies

No, community resolution only

**Comment by evandongen** [comment]
This is already covered in #7180 . Merged my code with that branch
