### ISSUE TITLE
custom stub4testtool is not being used in frankframework docker container

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#7243]
### Current Behavior

when using a custom stub4testtool it's not being applied to my configs when placing this stub4testtool at /opt/frank/resources/xml/xsl/stub4testtool.xsl

Niels mentioned something about a scopeProvider needing to be provided here https://github.com/frankframework/frankframework/blob/36b2cae5d9e33e820ba8df2bf95c56694832bfeb/core/src/main/java/org/frankframework/configuration/ConfigurationDigester.java#L290 

### Expected Behavior

properly implemented custom stub4testtool

### Environment Information

**FF! 8.3.0-20240803.152218**: Frank
Running on **ce22432c7c80** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (17.0.11+9)**
Heap size: **515.0 MiB**, total JVM memory: **1.8 GiB**
Free memory: **1.3 GiB**, max memory: **1.9 GiB**
Free disk space: **21.8 GiB**, total disk space: **58.4 GiB**

### Steps To Reproduce

1. create custom stub4testtool.xsl, e.g. where the httpsender is not being stubbed
2. create config with this unstubbed sender
3. place stub4testtool.xsl at the expected location of /opt/frank/resources/xml/xsl/stub4testtool.xsl
4. start frank and see that the httpsender is still stubbed

**Comment by nielsm5** [comment]
Also relevant: #3622

**Comment by Laurens-makel** [comment]
Recently observed something quite similar, local tomcat did pickup the xsl file however in the dockerized environment not
