### ISSUE TITLE
Frank!Doc of FixedResultPipe not visible

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7273]
### Current Behavior

![image](https://github.com/user-attachments/assets/c8ef0b07-73ea-43fb-84a3-fdb36ff8f2cd)

### Expected Behavior

Working @code examples

### Environment Information

8.3.0-20240803.152218

**Comment by nielsm5** [comment]
Vivy: PRE -> CODE

**Comment by evandongen** [comment]
Javadoc has been modified where needed. We now need a change to the frank doc that correctly supports `<pre>{@code }</pre>` blocks

**Comment by nielsm5** [comment]
Blocked till https://github.com/frankframework/frank-doc/issues/196 has been solved.
