### ISSUE TITLE
Pipeline doesn't return error message when state="ERROR"

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7275]
### Current Behavior

I have the following config:

		<Pipeline>
			<Exits>
				<Exit name="READY" state="SUCCESS" />
				<Exit name="InternalServerError" state="ERROR" code="500"/>
			</Exits>
			...
			<FixedResultPipe
				name="Return error message"
				returnString="Temperature not found in response of api.openweathermap.org"
				>
				<Forward name="success" path="InternalServerError" />
			</FixedResultPipe>
			...
		</Pipeline>

The string "Temperature not found in response of api.openweathermap.org" is not returned by the Pipeline althought it is in result:

![image](https://github.com/user-attachments/assets/4d3d5fc1-1e32-4110-b654-429f64cd2a09)
![image](https://github.com/user-attachments/assets/ed8d2d21-b83b-4d52-b993-f8b286dc2767)

### Expected Behavior

I would expect the return string as output of the Pipeline too

### Environment Information

FF! 8.3.0-SNAPSHOT: webapp
Running on xxx using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 166.6 MiB, total JVM memory: 729.0 MiB
Free memory: 562.4 MiB, max memory: 1.0 GiB
Free disk space: 58.3 GiB, total disk space: 237.8 GiB
Up since: 2024-08-07 10:28:46 (1h)

**Comment by nielsm5** [comment]
Which listener do you use?

**Comment by jacodg** [comment]
I'm using both JavaListener and ApiListener:

		<Receiver name="Update temperature" flow:y="100" flow:x="100">
			<JavaListener name="Update temperature" serviceName="UpdateTemperature"/>
		</Receiver>
		<Receiver name="ApiListenerReceiver" flow:y="250" flow:x="100">
			<ApiListener name="ApiListener" uriPattern="temp"/>
		</Receiver>

I was rerunning from Ladybug Test tab but I now also tried test a pipeline, calling it by opening http://localhost/api/temp in my browser and from the scheduler (changed "Temperature present?" to always go to "Return error message" so it fails every minute now). All with the same result. The test a pipeline page does show:

![image](https://github.com/user-attachments/assets/e8ccb32a-d4cd-4ca7-a4e4-bf36cdcf8f17)

And the browser:

![image](https://github.com/user-attachments/assets/17a1586b-0504-46ba-99e2-361a48e95d62)

But in all Ladybug reports I see "Message is null" at the end of the pipeline
