### ISSUE TITLE
If configurations.directory.autoLoad: true, then you still have to set configurations.names: ""

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7288]
### Current Behavior

I am starting a Frank config with docker. In my docker-compose.yml, I need to set both `configurations.directory.autoLoad: true` and `configurations.names: ""`. Without `configurations.names: ""`, I get an error in the Frank!Console even though my config is available in `/opt/frank/configurations`.

### Expected Behavior

I should be able to start up with `configurations.directory.autoLoad: true` only.

### Environment Information

**FF! 8.2.0**: frank-docker-example 
Running on **d71dacdb9658** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (17.0.11+9)**
Heap size: **93.4 MiB**, total JVM memory: **200.0 MiB**
Free memory: **106.6 MiB**, max memory: **2.0 GiB**
Free disk space: **40.1 GiB**, total disk space: **58.4 GiB**

### Anything else?

This is relevant because it is difficult to explain why you should set `configurations.names: ""`. As long as this issue is not fixed, the explanation of developing with docker will be less appealing. See https://frank-manual.readthedocs.io/en/latest/advancedDevelopment/dockerDevel/dockerDevel.html for the text I am working on.

**Comment by philipsens** [comment]
Is the error about not being able to load the `${instance.name}` with the WebAppClassLoader?
If not, I would like to see the error you are getting.

**Comment by mhdirkse** [comment]
```
Configuration [frank-docker-example] - Configuration file [Configuration.xml] not found in ClassLoader [WebAppClassLoader@450b94e9[frank-docker-example]]
```

**Comment by nielsm5** [comment]
> Is the error about not being able to load the `${instance.name}` with the WebAppClassLoader? If not, I would like to see the error you are getting.

I believe the answer is yes :)

**Comment by nielsm5** [comment]
Default: `configurations.names=${instance.name}`
Als `configurations.directory.autoLoad: true` mag de default (WebAppClassloader ${instance.name}) leeg zijn.

**Comment by mhdirkse** [comment]
This fix indeed does what I want. I can omit `configurations.names: ""` which can make the manual more clear. I will edit the Frank!Manual.
