### ISSUE TITLE
Change default value for trimSpaces attribute on query senders from true to false

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#7315]
### Related Problem or Business Case

It often occurs that Frank developers find themselves confused about the query senders trimming spaces by default. Especially during investigation of production incidents, its quite hard to figure out that values are trimmed by the query sender.

In 99% of the cases you actually don't want the spaces to be trimmed and you'd have to remember yourself everytime you write a query sender with a SELECT statement that you have to set the trim spaces attribute to false.

See the following issue reports as examples:
#7245
#3402
#992

### Describe the Feature

Change default value from true to false.

### Collaboration with External Companies

No, community resolution only

**Comment by philipsens** [comment]
We don't think changing a default value is a good solution. We will implement a better way to document this behavour.
