### ISSUE TITLE
The parameters are not shown on Ladybug although they are used in the pipe processes

### ISSUE THREAD

**Issue by mericakgul** [frankframework/frankframework#7329]
### Current Behavior

The parameter passed to the pipes are not shown on ladybug. The problem is encountered on the FF version 8.3.0-20240730.042429. However, the parameter values are used in the pipes in the related processes so pipes are working fine but we just cannot see the parameters on ladybug.

### Expected Behavior

Show the parameters passed to the pipes as it used to be. The screenshots showing how it is now and how it should be and the example pipe showed in the screenshots.

![how-it-should-be](https://github.com/user-attachments/assets/fbfa71dd-759a-41e5-b2ac-12cdc38d323b)
![example-pipe-showed-in-ladybug](https://github.com/user-attachments/assets/8dc5ada6-5f9c-4c21-be57-875eaa53a822)
![how-it-is](https://github.com/user-attachments/assets/bb04309f-3a56-4ee1-a894-16d77c631cfb)

### Environment Information

**FF! 8.3.0-20240730.042429**: Openforms2xxllnc 1.0.1
Running on **44b12f6a7058** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (17.0.11+9)**
Heap size: **247.4 MiB**, total JVM memory: **392.0 MiB**
Free memory: **144.6 MiB**, max memory: **5.9 GiB**
Free disk space: **207.3 GiB**, total disk space: **250.9 GiB**

**Comment by nielsm5** [comment]
Hi,

Which version were you using before the upgrade?

**Comment by mericakgul** [comment]
Hi,
The version I used before was 8.1.0-20240404.042328. @nielsm5
