### ISSUE TITLE
csvparser pipe should translate plus sign in headers to underscore

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#7332]
### Current Behavior

given a csv file with a plus sign in one of the headers, the csvparserpipe, doesn't translate this to, say, an underscore. This gives issues when trying to transform the resulting xml 

### Expected Behavior

csvparserpipe translating plus signs to underscore

### Environment Information

**FF! 8.3.0-20240808.191517**: Frank2Eekels 1.0.0
Running on **[redacted]** using **Apache Tomcat/10.1.26**
Java Version: **OpenJDK Runtime Environment (21.0.4+7-adhoc.Administrator.jdk21u)**
Heap size: **214.7 MiB**, total JVM memory: **256.0 MiB**
Free memory: **41.3 MiB**, max memory: **256.0 MiB**
Free disk space: **49.1 GiB**, total disk space: **89.4 GiB**

### Steps To Reproduce

1. configure adapter with csvparserpipe
2. input csv with plus sign in header
3. see that plus sign is not translated to valid xml

### Configuration

```xml
<Module
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FrankConfig.xsd"
>
    <Adapter name="test">
        <Receiver>
            <JavaListener name="test" />
        </Receiver>
        <Pipeline>
            <CsvParserPipe name="test"></CsvParserPipe>
        </Pipeline>
    </Adapter>
</Module>
```

### Input

naam,woonplaats+postcode,land
Frank,Rotterdam+3014GT,Frankland

### Anything else?

Fix might be something similar to this commig https://github.com/frankframework/frankframework/pull/7232/commits/b57b2749aa2484f8481fa49284233d9f2b8f9d84

**Comment by philipsens** [comment]
The `SaxDocumentBuilder` needs to handle non-valid element name characters.
