### ISSUE TITLE
Use `java.sql.driver` as default type in the FrankResources.Resource

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#7379]
### Related Problem or Business Case

Not everybody knows the class names for the driver that needs to be used. 
It is already possible to get the class name from the `jdbc.[0].url` but then the type should be set to `java.sql.driver`. 

### Describe the Feature

Make the `java.sql.driver` default so the type can be left out.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
`FrankResources.Resource` has a type field. By default this value may be set to `java.sql.Driver`.
Needs testing if this has any implications.

**Comment by nielsm5** [comment]
Oracle driver version is `oracle.jdbc.driver.OracleDriver`. You need to specify the implementation else the driver wont be loaded.

**Comment by nielsm5** [comment]
Soortgelijke pagina: https://www.netiq.com/documentation/identity-manager-49-drivers/jdbc/data/supported-third-party-jdbc-drivers.html#bvx364n moet komen in de Manual

**Comment by mhdirkse** [comment]
Bij een PostgreSQL database werkt het om het type veld op `java.sql.Driver` te zetten in plaats van `org.postgresql.Driver`, de waarde die tot nu toe in de Frank!Manual wordt gebruikt.

**Comment by nielsm5** [comment]
> Het werkt nog niet om het `type` veld weg te laten uit resources.yml.

Van wat ik kan zien, de individuele drivers moeten zich zelf registreren door `DriverManager.registerDriver(myDriver)` aan te roepen. Zolang een Driver niet wordt ingeladen (class.forName) zal dit niet gebeuren. Het veld weglaten kan dus niet.

**Comment by nielsm5** [comment]
The following page now exists to describe how drivers can and should be configured. https://frank-manual.readthedocs.io/en/latest/deploying/database.html
