### ISSUE TITLE
No stacktrace for RuntimeException

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7389]
### Current Behavior

Made a mistake while changing Ladybug which caused a NPE. The console shows:

![image](https://github.com/user-attachments/assets/b5e80393-1d75-486e-9c04-0b1ac90575e0)

The log shows:

2024-08-24 10:14:20,513 WARN  [http-nio-80-exec-3] {mid=ladybug-testmessagec0a8b227--2b61175c_191837178b9_-7ff9, cid=Ladybug_Test_Tool-3.0-SNAPSHOT--2b61175c:191837178b9:-7ffa, adapter=Update temperature} core.Adapter - Adapter [Update temperature] error processing message with messageId [ladybug-testmessagec0a8b227--2b61175c_191837178b9_-7ff9]: RuntimeException calling PipeLine with tx attribute [SUPPORTS]: (NullPointerException) Cannot invoke "String.toString()" because "this.path" is null

I couldn't find a stacktrace to find out where I made a mistake until changing TransactionAttributePipeLineProcessor.java to print the stacktrace

### Expected Behavior

Would like to see the stracktrace somewhere. Or would this in some cases give to much logging? Do older versions of F!F also not print a stacktrace? In that case it might not be a problem.

### Environment Information

FF! 8.3.0-SNAPSHOT: webapp
Running on xxx using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 94.2 MiB, total JVM memory: 530.0 MiB
Free memory: 435.8 MiB, max memory: 1.0 GiB

### Steps To Reproduce

Make a pipe throw a RuntimeException

**Comment by nielsm5** [comment]
I'm unsure what 'code' path is being followed here. I see a try catch with 
`error("Exception in message processing", t);`

**Comment by nielsm5** [comment]
Ah, yes this is an 'issue', limited to test-pipeline.

**Comment by tnleeuw** [comment]
@jacodg Niet gerelateerd aan dit issue, maar omdat je er hier een opmerking over maakte, die `Leak detection` log berichten hebben we nu ook verwijderd. We hebben nu een betere manier om dit te detecteren.

**Comment by jacodg** [comment]
Check, thanks!
