### ISSUE TITLE
Add data-cy* attribute to query configuration warnings and/or errors

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7399]
### Related Problem or Business Case

Project https://github.com/frankframework/frankframework contains example configurations. It has Cypress tests that check that these configs do not show (unwanted) warnings when started in the FF!. Presently, the DOM is queried with `.alert-warning`. It would be nice to have a data-cy* attribute for this. This might have the added benefit that also errors can match the data-cy* selector, allowing the test to configure configuration errors as well. I remember such data-cy* attributes were present earlier, but they seem to be gone.

### Describe the Feature

See above.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
The `data-cy-status-component="configuration-warnings"` tag is on the `UL` element, you can use `selector-name > li` to refine the results.
