### ISSUE TITLE
The flow diagram does not show the possible forwards for XmlSwitchPipe

### ISSUE THREAD

**Issue by RayetSena** [frankframework/frankframework#7423]
### Current Behavior

The flow diagram does not show the possible forwards for XmlSwitchPipe.
![image](https://github.com/user-attachments/assets/c0f20c3a-93d8-4a69-a2c7-72afffb38069)

### Expected Behavior

It is expected to show possible forwards as in the old version
![image](https://github.com/user-attachments/assets/9e9eeb77-819c-4716-a4c1-957f4ee74852)

### Environment Information

ff.version=8.3.0-20240813.042338

### Configuration

```xml
<XmlSwitchPipe 
    name="ForwardBySoapActionSwitch"
    forwardNameSessionKey="LegalizedSoapAction"
    notFoundForwardName="UnsupportedSoapActionError"
    />
```

**Comment by nielsm5** [comment]
This is not possible, you're determining the forward based on runtime data (session key).
