### ISSUE TITLE
HttpSender gives errorMessage even when success is true and status-code is 200

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7450]
### Current Behavior

![image](https://github.com/user-attachments/assets/a8342c1c-3888-47f8-be91-e506853af6c9)
![image](https://github.com/user-attachments/assets/431331d6-996c-4c71-8de5-a68ff1f3cc49)

### Expected Behavior

No errorMessage checkpoint in Ladybug when everything is okay

### Environment Information

FF! 8.3.0-20240906.042421: Frank2Example3
Running on XXX using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 213.6 MiB, total JVM memory: 384.0 MiB
Free memory: 170.4 MiB, max memory: 1.0 GiB

**Comment by nielsm5** [comment]
In https://github.com/frankframework/frankframework/blob/master/core/src/main/java/org/frankframework/http/HttpSenderBase.java#L492, only set errorMessage when statuscode `>= 400 < 600`.
