### ISSUE TITLE
Convert primitive values and enum constants to string before supplying them to Ladybug

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7486]
### Related Problem or Business Case

For example, Ladybug shows a checkpoint named "success" after executing a sender. The code that writes the value provides a Boolean, but in Ladybug it shows up as a number. This is very confusing.

### Describe the Feature

Something like "success: false" or "success: true" looks much clearer.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
Ik zie:

**Comment by mhdirkse** [comment]
In Ladybug, output checkpoints (and probably also input checkpoints) that have a Boolean or enum value look awkward, see screenshots below:

![image](https://github.com/user-attachments/assets/d60573cf-5a0b-4066-ada3-66bb3d44e48e)

![image](https://github.com/user-attachments/assets/04d09b81-86f3-4654-bef9-19db47c5b282)

I understand that the value of a Ladybug checkpoint is a Java object. If it is not a String, then a transformation is needed to get the string presented in the Ladybug UI. In this case, an XMLEncoder is applied, which converts the Java object to XML.

This mechanism is fine for non-trivial Java objects, say an instance of some fictional Bicicle class that has wheels, a frame, lights, etc. But primitive values should not look confusing by adding XML around them. The Frank!Framework can achieve this by converting primitive values and enum constants to String before supplying them to Ladybug.

**Comment by nielsm5** [comment]
Looks like the ladybug's `MessageEncoder` should handle this?

**Comment by philipsens** [comment]
This issue should be resolved in the Ladybug, as Niels elaborated.
