### ISSUE TITLE
Double jars jaxb-core

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7491]
### Current Behavior

In Frank!Runner output:

The following double jars are found: jaxb-core

### Expected Behavior

No warning about double jars

### Environment Information

FF! 8.3.0-20240910.042339: Frank2Example3
Running on xxx using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 276.6 MiB, total JVM memory: 553.0 MiB
Free memory: 276.4 MiB, max memory: 1.0 GiB

### Steps To Reproduce

Start Frank2Example3 with 8.3.0-20240910.042339 with Frank!Runner

**Comment by nielsm5** [comment]
They are two different dependencies but after looking inside them it looks like one is a superset of the other.
I'll try and create some excludes and enforce-rules to prevent this from happening.
