### ISSUE TITLE
Session key exitCode should only be generated if the pipeline has an <Exit> with a code attribute.

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7521]
### Related Problem or Business Case

In Ladybug, I see that my sender outputs a session key named exitCode and that its value is 0. See screenshot below:

![image](https://github.com/user-attachments/assets/94e98d1d-8009-4990-84f8-813502905cb5)

I understood that this comes from attribute "code" of element `<Exit>`. If my `<Exit>` does not have attribute "code", I do not want to see this sessionKey and hence it should not be created in this case. I do not mean that the session key may be created but should be omitted from Ladybug - I really mean the session key should not come into existence.

### Describe the Feature

See above

### Collaboration with External Companies

No, community resolution only

**Comment by philipsens** [comment]
We will change the default to `null`
