### ISSUE TITLE
Senders should not produce checkpoint "forwardName"

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7522]
### Related Problem or Business Case

In Ladybug, I see that my sender outputs a checkpoint "forwardName" that has value 0. See below.

![image](https://github.com/user-attachments/assets/f58e79d6-406b-4050-bb06-a138f80b650c)

Me and Jaco do not see the value of this checkpoint and we would like the Frank!Framework not to create it.

### Describe the Feature

See above.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
I can see the value, it's `0`..

I think what's happening is that you're calling a subadapter with exit-code `0`, which is seen in the main adapter as the preferred forward. I agree that when the code has not been explicitly set on the exit it should not count/report anything.

**Comment by mhdirkse** [comment]
Issue #7521 is about the exit code while this issue is about checkpoint "forwardName". Assume that a sub-adapter is called, that this sub-adapter has an `<Exit>` with code attribute, and this that exit is the outcome of the sub-adapter. Will the caller then use the exit code of the sub-adapter as a forward to follow? Only if this is the case, I would think that a forwardName checkpoint makes sense.

**Comment by mhdirkse** [comment]
Niels sent Teams messages about this:

Een sender mag teruggeven welke forward gewenst is. bij http is dit bijvoorbeeld de statuscode
 
bij een localsender is dit de exit code.
 
(van de aangeroepen adapter/pipeline)
