### ISSUE TITLE
Checkpoint errorMessage produced by sender should be more meaningful

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7523]
### Related Problem or Business Case

In Ladybug, I see that my sender has a checkpoint errorMessage while execution of the sender was successful. The value is `exitState=SUCCESS`. See picture below:

![image](https://github.com/user-attachments/assets/10dd8d6b-32f6-4aca-b84a-8953830a07f9)

This is a confusing checkpoint. I suggest we change this behavior as follows:
* This checkpoint should not be created if execution of the pipeline was successful. In this case there is no error and hence there should be no errorMessage.
* If there is an error, then the value should be just the error message, nothing more.

### Describe the Feature

See above.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
This happens in the soon to be deprecated `IbisLocalSender`, please use the `FrankSender` instead.
