### ISSUE TITLE
ObfuscatePipe is not compatible with java 17

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#7526]
### Current Behavior

![image](https://github.com/user-attachments/assets/50a0e543-eaa0-400e-855c-9aa34c496759)

### Expected Behavior

https://medium.com/@agrawalprince617/eliminating-tibcrypt-dependency-for-a-seamless-java-8-to-17-upgrade-23c95c82a8ad

### Environment Information

FF! 8.1.1: frank2utility_oauthtokenservice
Running on frank2utility-oauthtokenservice-app-tst using Apache Tomcat/9.0.83
Java Version: OpenJDK Runtime Environment (17.0.12+7-LTS)
Heap size: 448M, total JVM memory: 1006M
Free disk space: 10GB, total disk space: 15GB
Up since: 2024-09-03 11:17:36 (16d)

**Comment by alisihab** [comment]
some background: the application was using 7.9.3 with a custom ObfuscatePipe. That is why the old package names are visible in the stacktrace. 8.1.1 was reported as FF version in the issue description since ObfuscatePipe was only introduced in 8.1.x versions. 
The line numbers in the stacktrace and the code might differ a little but it is basically the same code.
Unfortunately, i can no longer reach the original stacktrace but I found another image that gives the other part(the important part :D ) of the stacktrace. 
![image (1)](https://github.com/user-attachments/assets/d71f2bd1-29d0-4627-873f-b81a6e538b40)

From the stacktrace the issue seems to happen while decrypting

Moreover, the issue must be reproducible by running the ObfuscatePipeTest class against jdk 17 I think

**Comment by philipsens** [comment]
Thank you for your response!

**Comment by evandongen** [comment]
Tibcrypt library is deprecated/removed and doesn't work well with Java 17 or higher. We need to remove this library and implement an alternative.
