### ISSUE TITLE
In Frank2Example krijg je een 404 fout als je naar Ladybug gaat

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7563]
### Current Behavior

Zie titel.

### Expected Behavior

Ladybug wordt getoond.

### Environment Information

FF! 8.3.0-20240925.042333: frank2example
Running on frank2example-frankframework-ff765977c-f2hkt using Apache Tomcat/10.1.28
Java Version: OpenJDK Runtime Environment (21.0.4+7-LTS)
Heap size: 2.2 GiB, total JVM memory: 4.0 GiB
Free memory: 1.8 GiB, max memory: 4.0 GiB
Free disk space: 43.2 GiB, total disk space: 123.4 GiB
Up since: 2024-09-25 05:38:44 (13h)

**Comment by nielsm5** [comment]
This is a known defect when running on k8s and will be fixed before the 8.3 release.
