### ISSUE TITLE
Trim headerParams in ApiListener

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#7593]
### Current Behavior

headerParams="ApiKey, ApplicationElementId" to
headerParams="ApiKey,ApplicationElementId"

![image](https://github.com/user-attachments/assets/b25540a1-9a0c-4102-bef2-5faa32387941)

### Expected Behavior

trim

### Environment Information

FF! 8.3.0-20240925.042333: [****] 
Running on [****]using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Up since: 2024-10-01 13:37:55 (21h)

**Comment by evandongen** [comment]
A similar solution was implemented in https://github.com/frankframework/frankframework/pull/7568
