### ISSUE TITLE
Cannot insert multiple data entries in single query 

### ISSUE THREAD

**Issue by rob-wolters** [frankframework/frankframework#7604]
### Current Behavior

`<manageDatabaseREQ>
    <sql>
        <type>other</type>
        <query>
            INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('1', '2', 'Nederland');
            INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('3', '4', 'Duitsland')
        </query>
    </sql>
</manageDatabaseREQ>`

Using the script above, I tried inserting this data locally into an Oracle 11g database.
This results in the following error: 
`nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.XmlQuerySender] [Query-sender] got exception executing query [INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('1', '2', 'Nederland');
INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('3', '4', 'Duitsland')]: (SQLSyntaxErrorException) ORA-00911: invalid character
https://docs.oracle.com/error-help/db/ora-00911/: (OracleDatabaseException) ORA-00911: invalid character`

Moving the semicolon results in:
`nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.XmlQuerySender] [Query-sender] got exception executing query [INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('1', '2', 'Nederland')
INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('3', '4', 'Duitsland');]: (SQLSyntaxErrorException) ORA-00933: SQL command not properly ended
https://docs.oracle.com/error-help/db/ora-00933/: (OracleDatabaseException) ORA-00933: SQL command not properly ended`

and removing it:

`nl.nn.adapterframework.core.SenderException: [nl.nn.adapterframework.jdbc.XmlQuerySender] [Query-sender] got exception executing query [INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('1', '2', 'Nederland')
INSERT INTO ISSUERS (ISSUERID, ISSUERNAME, COUNTRYNAMES) VALUES ('3', '4', 'Duitsland')]: (SQLSyntaxErrorException) ORA-00933: SQL command not properly ended
https://docs.oracle.com/error-help/db/ora-00933/: (OracleDatabaseException) ORA-00933: SQL command not properly ended`

Running this same query in the Dev environment, utilizing Microsoft SQL, is accepted.
Altering the query to one entry at a time does not give an error.

### Expected Behavior

I expect it to execute 2 queries concurrently, with no errors.

### Environment Information

FF! 7.9.4: ija_xxx
Running on xxx using Apache Tomcat/9.0.89
Java Version: OpenJDK Runtime Environment (1.8.0_392-b08)
Heap size: 238M, total JVM memory: 547M
Free disk space: 147GB, total disk space: 237GB
Up since: 2024-10-02 14:20:29 (2h)

### What database are you using?

Oracle

### What browsers are you seeing the problem on?

Chrome

**Comment by nielsm5** [comment]
Please use the following syntax: 
`INSERT INTO MyTable ( Column1, Column2 ) VALUES ( Value1, Value2 ), ( Value1, Value2 );`
Or use the XML configuration to use multiple inserts.
