### ISSUE TITLE
Onderzoek GreenMail comment + mail-fs tests (maken)

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7623]
https://github.com/frankframework/frankframework/blob/541828b2ce8f5572c5ec45dfea5971aeaaad54d4/core/pom.xml#L725
Is dit comment nog relevant, moeten wij nog iets doen?

Kijken naar extra coverage in de volgende files:
- [ ] MailFileSystemBase.java
- [ ] MailListener.java
- [ ] MailFileSystemUtils.java

**Comment by evandongen** [comment]
Comment is niet meer relevant, ik heb heb het gecheckt met een dependency:tree:
```
[INFO] +- com.icegreen:greenmail-junit5:jar:2.1.0:test
[INFO] |  \- com.icegreen:greenmail:jar:2.1.0:test
[INFO] |     \- org.eclipse.angus:jakarta.mail:jar:2.0.3:test
```
Gebruikt nu netjes jakarta mail. Daarnaast is de junit:junit exclusion ook niet meer van toepassing
