### ISSUE TITLE
Include correlationId in API response of Test-A-Pipeline (optional: link to Ladybug report in web console)

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#7648]
### Related Problem or Business Case

When implementing features which involve multiple Frank applications, testing becomes more difficult. Larva tests cover each individual component but do not offer any guarantee that the system is functioning correctly as a whole. Depending on the architecture and protocols used, certain testing tools could be applied but it's hard to assert an entire functional flow with those tools.

I'm doing some research into developing a integration/system testing tool and I'd like to validate the idea of using the IAF & Ladybug API's to submit and assert messages across participants of a certain functional flow, described in simple YAML files which also serve as documentation to developers.

However I'm unable to correlate a message published by Test-A-Pipeline to a Ladybug report without a correlationId, the current implementation of the Test-A-Pipeline API does not include the correlationId in the response.

### Describe the Feature

Include correlationId in API response of Test-A-Pipeline so this value could be used by the testing implementation to make additional API calls.

Another use case could be to display a link to the corresponding Ladybug report, could be useful to the end-user to directly open the Ladybug report of the submitted message.

### Collaboration with External Companies

No, community resolution only

### Anything else?

Would be very appreciated if the API response change is backported to 7.9!

**Comment by nielsm5** [comment]
This is actually possible since #7535. Hope this helps!

**Comment by Laurens-makel** [comment]
> This is actually possible since #7535. Hope this helps!

This seems sufficient indeed, any chance that this could be backported to 7.9 ?
