### ISSUE TITLE
ForEachChildElementPipe results in NullPointerException

### ISSUE THREAD

**Issue by DelanoWAF** [frankframework/frankframework#7708]
### Current Behavior

A multi-threaded usage of ForEachChildElementPipe is resulting in a NullPointerException. When given 26 items to iterate over, 27 threads are started according to the Ladybug report. Report is available upon request.

### Expected Behavior

Regular ForEachChildElementPipe behaviour where the pipe iterates over each element in the input and performs correct actions on them.

### Environment Information

Locally tested using Zaakbrug via Docker. F!F version set to 8.3.0. 
Test performed by rerunning the client-provided report in Ladybug.

### Steps To Reproduce

1. Rerun report.
2. Report will fail.

### Configuration

```xml
<ForEachChildElementPipe 
                name="ZaakTypeInformatieObjectTypeUrlIterator"
                getInputFromSessionKey="ZgwZaakType"
                storeResultInSessionKey="ZgwInformatieObjectTypen"
                elementXPathExpression="/ZgwZaakType/informatieobjecttypen"
                parallel="true" >
                <IbisLocalSender
                    name="GetZgwInformatieObjectTypeByUrlLocalSender"
                    javaListener="GetZgwInformatieObjectTypeByUrl"
                    returnedSessionKeys="Error">
                    <Param name="Url" xpathExpression="/informatieobjecttypen"/>
                </IbisLocalSender>
                <Forward name="success" path="UnwrapZgwInformatieObjectTypenToList"/>
                <Forward name="exception" path="EXCEPTION" />
            </ForEachChildElementPipe>
```

### Input

Ladybug report available privately.

### Relevant Log Output

```console
org.frankframework.xml.SaxException: an error occurred during parallel execution: <error xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<code>TechnicalError</code>
	<reason>some negative response from ZGW API received by GetZgwInformatieObjectTypeByUrl</reason>
	<details/>
	<detailsXml>
		<root>
			<errorMessage timestamp="Thu Oct 03 11:45:37 CEST 2024" originator="IAF 8.3.0-20240910.042339" message="SenderPipe [GetZgwInformatieObjectTypeByUrl] msgId [synthetic-message-id-0a2e1849--4f7a5f05_1925151492a_-6e34]: Cannot invoke &quot;io.micrometer.core.instrument.Timer$ResourceSample.tag(String, String)&quot; because the return value of &quot;java.util.Map.remove(Object)&quot; is null">
				<location class="org.frankframework.pipes.SenderPipe" name="GetZgwInformatieObjectTypeByUrl"/>
				<details>java.lang.NullPointerException: Cannot invoke "io.micrometer.core.instrument.Timer$ResourceSample.tag(String, String)" because the return value of "java.util.Map.remove(Object)" is null
	

Log cut off due to length.
```

**Comment by evandongen** [comment]
I found some relevant information on the http components github:
* [Someone with the same error](https://github.com/micrometer-metrics/micrometer/issues/1886#issuecomment-1529851272)
* https://github.com/micrometer-metrics/micrometer/issues/3797
* https://github.com/micrometer-metrics/micrometer/issues/3932 (deprecate http components 4 instrumentation)

**Comment by evandongen** [comment]
Possible fix pushed, need to test this locally for the given situation

**Comment by checkiecheck** [comment]
Is this being release anytime soon? We're struggling with multiple issue on a client and want to see if we can clear some errors like these.
