### ISSUE TITLE
Make it possible to hide IAF_Util tab

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7729]
### Related Problem or Business Case

At https://demo.wearefrank.nl/iaf/gui/#/status the IAF_Util tab is shown which is empty:

![image](https://github.com/user-attachments/assets/12f2236d-4fd9-416f-b48f-ba946b919678)

For people seeing the Frank!Framework for the first time this only gives confusion

### Describe the Feature

I would like to be able to hide this tab. I see a couple of solutions:

1. Hide tabs that are empty (maybe create a property for it)
2. Move IAF_Util "business logic" from a Frank!Configuration to Java backend code. Would we still show the jobs on the Scheduler page or consider it low level Frank!Framework logic that will only log to log file and not show anything in the console?
3. When we take the Configuration page and Scheduler page into consideration also it would be nice (at least for the demo) to also hide IAF_Util on these pages. When showing the Scheduler page it can be confusing there are a lot of jobs wheras the demo configurations only has one job (which we show to the user in a demo). So it might be nice to have a property to hide IAF_Util on all pages.

### Collaboration with External Companies

No, community resolution only

### Anything else?

- [x] Create a component, so this feature can be implemented in multiple places @Matthbo 
- [x] Persist selected tab across pages with a service
- [x] Implement a filter that filters out IAF_Util (if needs to be hidden)
- [x] Implement a filter that hides other empty (no adapter) configurations
  - [ ] This may conflict on some pages [like @nielsm5 mentioned](https://github.com/frankframework/frankframework/issues/7729#issuecomment-2475772598)

**Comment by nielsm5** [comment]
Would be nice if all pages use the tabs, that the selected-tab is persistent when you change (adapterstatus to schow-configurations or whatever).
When tabs are hidden some functionality will disappear, such as the 'add monitor' button... We need to figure out what to do with these buttons. As well as what happens when you move from a tab (environment status) to another (adapter status) which may not exist because it's hidden...

**Comment by philipsens** [comment]
I had the idea to add an eye icon which has a dropdown with:
```
Hide Configurations without adapters
Hide FF! Utility configuration ✔️
```
---
Normal UI features like cookies can be used, so no user setting will ever be used. I forgot this for a moment.

Edit edit: Doesn't mean local storage cant be used!

**Comment by Matthbo** [comment]
I'm starting with making the tabs menu a reusable component so that we only have to make it once and it'll work consistently on all pages that have it.

**Comment by jacodg** [comment]
How do I hide the IAF_Util tab?
