### ISSUE TITLE
Add Trigger on Monitors page broken

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7735]
### Current Behavior

Using the button gives me an error:

![image](https://github.com/user-attachments/assets/be7ea184-c37c-40de-acc4-851a9f483538)

### Expected Behavior

No error and a way to configure a trigger

### Environment Information

FF! 9.0.0-20241018.042327: Demo
Running on LPCENL007133916 using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 510.0 MiB, total JVM memory: 710.0 MiB
Free memory: 200.0 MiB, max memory: 1.0 GiB
Free disk space: 48.0 GiB, total disk space: 237.8 GiB
Up since: 2024-10-21 16:51:54 (8m)

**Comment by nielsm5** [comment]
There's a `/` at the end of the `/monitors/<name>/triggers/` endpoint. Sigh... Thanks Spring-Web!
