### ISSUE TITLE
Hazelcast voorbeeld config aanpassen, en documenteren dat dit expliciet uitgezet moet worden.

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7743]
<auto-detection enabled="false"/>

https://github.com/frankframework/frankframework/blob/2ee0fa12fa043e38d7a79f8ac89dbbfe04e92345/management-gateway/src/main/resources/ff-hazelcast-network-kubernetes.xml#L8

En mogelijk ook naar https://docs.hazelcast.com/hazelcast/5.5/storage/configuring-persistence#single-member kijken.

**Comment by philipsens** [comment]
https://github.com/frankframework/charts/issues/35

**Comment by nielsm5** [comment]
<auto-detection enabled="false"/>
