### ISSUE TITLE
timestamps in console are not consistent

### ISSUE THREAD

**Issue by checkiecheck** [frankframework/frankframework#7823]
### Current Behavior

Timestamps in scheduler and adapter status are seemingly linked to desktop timezone. Time stamp in ladybug and application logs are set to server timezone (? guessing here).
![image](https://github.com/user-attachments/assets/75c41762-d545-4c89-9435-b8ae09d01ec0)
![image](https://github.com/user-attachments/assets/67eb2c17-3419-41a0-96ea-040002ac823e)
![image](https://github.com/user-attachments/assets/688d4a76-1282-4582-9f32-c32b8e72d107)

### Expected Behavior

Wll timestamps to be consistent so there is no descrepancy during troubleshooting which message is processed at what time.

### Environment Information

**FF! 8.3.0-20241010.042329**: demo 
Running on **frankframework-demo-c5958cf98-pmtm7** using **Apache Tomcat/10.1.28**
Java Version: **OpenJDK Runtime Environment (21.0.4+7-LTS)**
Heap size: **323.9 MiB**, total JVM memory: **480.0 MiB**
Free memory: **156.1 MiB**, max memory: **62.8 GiB**
Free disk space: **85.5 GiB**, total disk space: **123.4 GiB**

### Configuration

```xml
see demo.wearefrank.nl
```

**Comment by Matthbo** [comment]
The console frontend is currently not receiving the server timezone and so its not possible to convert a date timestamp properly to a date format with the server timezone while information from ladybug or logging have dates already converted to a string or is already part of text so the frontend is not managing that.

This could be more consistent by having the frontend know the timezone / calculate time difference and trying to display all the dates based on server timezone.

**Comment by philipsens** [comment]
Relevant issue: #4945
