### ISSUE TITLE
Slow console API response may cause version checking to see 'undefined' instead of application version

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#7839]
### Current Behavior

When the API is slow due to the server being under heavy load or other issues it may cause the frontend to continue loading after it got response on some API endpoints but version checking doesn't wait for appconstants to be fully loaded before checking if a newer version exists, causing it to try and match 'undefined' with the latest version and give the user a notification.

### Expected Behavior

Wait for the app constants to be loaded before checking if a newer version of the framework exists. Also never check the version if current version is 'undefined' but give a warning (either custom server warning or in the browser console).

### Environment Information

Master

### Anything else?

Could be backported if Niels thinks it's worth it

- [ ] Subissue: #7900

**Comment by nielsm5** [comment]
It would also be nice if the `Information` popup also displays something useful opposed to:
