### ISSUE TITLE
Add listener name as sessionKey to the context

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#7846]
### Related Problem or Business Case

When you create an Adapter with multiple listeners, and you want logic in xslt or xmlif to act differently based on which listener the pipeline was accessed.

### Describe the Feature

Add sessionkey with listener name as string value.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
It's a good idea to add a new metadata field for the previous pipe and where it originates from, the `InputOutputPipeProcessor` (previous pipe) and `Receiver` (originator).
category-name.originator or entrypoint, or listener?
category-name.previous-pipe?

**Comment by Laurens-makel** [comment]
> It's a good idea to add a new metadata field for the previous pipe and where it originates from, the `InputOutputPipeProcessor` (previous pipe) and `Receiver` (originator). `Pipeline.Caller` en `Pipeline.PreviousPipe`.
> 
> entrypoints: (test pipeline, resend via errorstorage, franksender, receiver)

Would this approach be suitable to work with the following attributes on most pipes?
![image](https://github.com/user-attachments/assets/ee361215-8285-4e42-84ba-efa8782f2934)
