### ISSUE TITLE
Example of monitoring is syntax 1, should be syntax 2

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7959]
### Related Problem or Business Case

See 
![image](https://github.com/user-attachments/assets/d2f713fe-774c-4dde-9947-8bb4e71f7289)

This example is syntax 1 (e.g. `<trigger className=... >` but should be syntax 2.

### Describe the Feature

See above.

### Collaboration with External Companies

No, community resolution only

**Comment by mhdirkse** [comment]
Supersedes https://github.com/frankframework/frank-doc/issues/245.

**Comment by nielsm5** [comment]
It would be nice if we could make the elements `Alarm` and `Trigger`. The way the frankdoc now determines the element names is not preferred

**Comment by mhdirkse** [comment]
I agree. I think `<AlarmTrigger ... >` is still better than `<trigger className="org.frankframework.monitoring.Alarm" ...>`. Can you adjust the examples without waiting for someone to improve the Frank!Doc?
