### ISSUE TITLE
The Frank!Doc does not make clear that monitor events are just strings

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7960]
### Related Problem or Business Case

See 
![image](https://github.com/user-attachments/assets/df2f5d95-b4ae-4882-9cd3-bebf75b02d63)

You see config child "event" here. Unlike any other config child, you do not insert an element here but just plain text. It would be an improvement to state that in the description.

### Describe the Feature

See above.

### Collaboration with External Companies

No, community resolution only

**Comment by mhdirkse** [comment]
Supersedes https://github.com/frankframework/frank-doc/issues/245.

**Comment by nielsm5** [comment]
Nested element description should mention this is an element with TEXT inside. `<event>im text inside</event>`
