### ISSUE TITLE
Monitoring: The UI allows me to save a trigger without a type

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7963]
### Current Behavior

I started Frank2Example1 with the Frank!Runner. I changed Configuration.xml of Adapter1a to include monitoring and a destination. Then I made a monitor with a trigger as shown:

![image](https://github.com/user-attachments/assets/c3b84d16-1210-4d5b-9fd7-af94a94f9700)

The type was not selected. Nevertheless I could press the Save button and the following screen appeared:

![image](https://github.com/user-attachments/assets/7b3ac408-dcff-4654-a146-acc10292eee1)

Next I stopped Adapter1a. It entered state ERROR. The following message was shown in the Adapter Status screen:

ERROR: got error stopping Adapter (java.lang.IllegalStateException): unable to evaluate trigger for event [Receiver Shutdown]

![image](https://github.com/user-attachments/assets/385d4fb1-37a2-4379-b182-d88246b02af0)

### Expected Behavior

The UI should not allow me to save and exit when the type field is blank. Or the UI should always show Alarm or Clearing as the type, without the option to leave it blank in the first place.

### Environment Information

FF! 9.0.0-20241115.042343: Frank2Example1
Running on LAPTOP-R1SK28C using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 130.2 MiB, total JVM memory: 249.0 MiB
Free memory: 118.8 MiB, max memory: 1.0 GiB
Free disk space: 116.0 GiB, total disk space: 464.3 GiB
Up since: 2024-11-19 11:19:53 (4m)

### Configuration

```xml
<Configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../FrankConfig.xsd"
	>
	<Adapter name="Adapter1a">
		<Receiver name="Receiver1a">
			<ApiListener name="Listener1a" uriPattern="service1a"/>
		</Receiver>
		<Pipeline>
			<EchoPipe name="HelloWorld" getInputFromFixedValue="Hello World!"/>
		</Pipeline>
	</Adapter>
	<Monitoring>
		<SenderMonitorAdapterDestination>
			<IbisLocalSender name="triggerIt" javaListener="reactToMonitor"></IbisLocalSender>
		</SenderMonitorAdapterDestination>
	</Monitoring>
</Configuration>
```

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by nielsm5** [comment]
The console should select TYPE = ALARM by default.

**Comment by mhdirkse** [comment]
The second screenshot suggests so. This UI issue struck me because I saw unexpected behavior of my monitor later. I wondered whether those issues were caused by not selecting the type. I think it is worthwhile to fix this to make monitoring easier to understand.

**Comment by mhdirkse** [comment]
Thanks.
