### ISSUE TITLE
Monitoring: Adapter enters state error due to trigger

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7964]
### Current Behavior

I create the following monitor:

![image](https://github.com/user-attachments/assets/f73f98b8-94ca-4c80-a005-89d40b257e04)

![image](https://github.com/user-attachments/assets/7cff091f-0bd0-4c01-99c2-a3ddd22d4c90)

Then I stop Adapter1a. It enters state ERROR and I see the following message in the Adapter Status screen:

ERROR: got error stopping Adapter (java.lang.IllegalStateException): unable to evaluate trigger for event [Receiver Shutdown]

When I return to Monitors, I see that my monitor is not raised.

### Expected Behavior

Adapter1a should stop without entering state ERROR. My monitor should raise.

### Environment Information

FF! 9.0.0-20241115.042343: Frank2Example1
Running on LAPTOP-R1SK28C using Apache Tomcat/10.1.24
Java Version: OpenJDK Runtime Environment (21.0.2+13-LTS)
Heap size: 125.6 MiB, total JVM memory: 263.0 MiB
Free memory: 137.4 MiB, max memory: 1.0 GiB
Free disk space: 116.0 GiB, total disk space: 464.3 GiB
Up since: 2024-11-19 11:27:30 (6m)

### Configuration

```xml
<Configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../FrankConfig.xsd"
	>
	<Adapter name="Adapter1a">
		<Receiver name="Receiver1a">
			<ApiListener name="Listener1a" uriPattern="service1a"/>
		</Receiver>
		<Pipeline>
			<EchoPipe name="HelloWorld" getInputFromFixedValue="Hello World!"/>
		</Pipeline>
	</Adapter>
	<Monitoring>
		<SenderMonitorAdapterDestination>
			<IbisLocalSender name="triggerIt" javaListener="reactToMonitor"></IbisLocalSender>
		</SenderMonitorAdapterDestination>
	</Monitoring>
</Configuration>
```

**Comment by nielsm5** [comment]
It appears a monitor has not been configured properly. In cases when this happens the monitor event should be ignored.

**Comment by mhdirkse** [comment]
Very good. That is quite possible because I was not accustomed to the UI of monitoring.
