### ISSUE TITLE
I would like the selector box for events to be bigger

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7965]
### Related Problem or Business Case

Make it easier to define monitors.

### Describe the Feature

See picture:

![image](https://github.com/user-attachments/assets/a658f125-f30e-4e4f-bdac-3be32512b326)

There are many events to choose from. Therefore I would like this box to be bigger. Or I would like to have a control to make it bigger by dragging.

### Collaboration with External Companies

No, community resolution only

**Comment by nielsm5** [comment]
Once we have a super nice (multi) select dropdown form component, with search, we can also apply it here. (a-la #5893)

**Comment by nielsm5** [comment]
Subtask of epic #5934
