### ISSUE TITLE
Monitoring: when you enter an erroneous trigger, you cannot correct anymore

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7968]
### Current Behavior

I was experimenting with triggers and made some error. That error is probably the cause of the following message in the log:

```
2024-11-19 13:48:19,113 ERROR [http-nio-80-exec-4] {} bus.BusException - unable to (re)configure Monitor
org.frankframework.configuration.ConfigurationException: you must define a period when using threshold > 0
```

However, this error message resulted from saving the following:

![image](https://github.com/user-attachments/assets/7feae246-d9e1-43b9-ac33-c7d54e5d10af)

When you make an error configuring a trigger once, the wrong data seems to persist somewhere, making it impossible to correct.

When you click back, it appears that the triggers were actually saved:

![image](https://github.com/user-attachments/assets/1d791800-eec1-4660-a6a7-e0c398c0c1ac)

### Expected Behavior

When you correct the data after entering wrong input, saving should work. And if the trigger was saved, the UI should not show an issue stating that there was an error.

### Environment Information

**FF! 9.0.0-20241115.042343**: Frank2Example1 
Running on **LAPTOP-R1SK28C** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (21.0.2+13-LTS)**
Heap size: **226.0 MiB**, total JVM memory: **281.0 MiB**
Free memory: **55.0 MiB**, max memory: **1.0 GiB**
Free disk space: **115.1 GiB**, total disk space: **464.3 GiB**

### Configuration

```xml
<Configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../FrankConfig.xsd"
	>
	<Adapter name="Adapter1a">
		<Receiver name="Receiver1a">
			<ApiListener name="Listener1a" uriPattern="service1a"/>
		</Receiver>
		<Pipeline>
			<EchoPipe name="HelloWorld" getInputFromFixedValue="Hello World!"/>
		</Pipeline>
	</Adapter>
	<Monitoring>
		<SenderMonitorAdapterDestination>
			<IbisLocalSender name="triggerIt" javaListener="reactToMonitor"></IbisLocalSender>
		</SenderMonitorAdapterDestination>
	</Monitoring>
</Configuration>
```

**Comment by mhdirkse** [comment]
I have another idea about the cause of this issue. The Save button may save all triggers instead of only the trigger just edited. If some earlier trigger is erroneous then saving all triggers reproduces the error. This problem does not occur anymore when you start with a new monitor.

**Comment by nielsm5** [comment]
In frontend validation (form-control) when threshold >1 make period a mandatory field.

**Comment by philipsens** [comment]
It is not possible to save an erroneous trigger anymore. This is fixed in.
