### ISSUE TITLE
MQTT sender needs persistent storage

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#8012]
### Current Behavior

When using the MQTT sender the Persistant directory is mandatory. 

### Expected Behavior

Either have MQTT sender working without or implementing the MemoryPersistence https://eclipse.dev/paho/files/javadoc/org/eclipse/paho/client/mqttv3/persist/MemoryPersistence.html

### Environment Information

We use Active MQ and MQTT

**Comment by jjansenvr** [comment]
@tommy2d please add info

**Comment by tommy2d** [comment]
When using the MqttSender within a pipeline, it insists on being configured with a persistenceDirectory attribute that I simply fill using "./". Most of the times it seems to work, but sometimes during development (=many restarts) it throws errors when attempting to write files to that folder (files named using pattern host + port stripped from '.' and ':').

I would argue a typical MqttSender does not care about these paths, and they should not be required parameters.

In related issues (that I might create additional tickets for): stability for this sender is still less-than-perfect, and reloads sometimes require me to restart the docker compose stack. Also, the requirement to set a clientId is strange from a usage perspective: It has to be unique but I typically do not care about that when sending data towards a Mqtt endpoint.

**Comment by tommy2d** [comment]
Another issue: When using multiple senders to connect to the same queue from 1 pipeline, the connection seems to be shared. This triggers the following exception:

` Status Report

Message Pipe [event-payload-sender] caught exception: (LifecycleException) Could not connect: (MqttException) Connect already in progress

Description The server encountered an unexpected condition that prevented it from fulfilling the request.`

**Comment by thomaspj10** [comment]
@tommy2d Could you share the configuration used to trigger the second error?

**Comment by tommy2d** [comment]
I dont have a copy of that state of my configuration,  but I simply copied the MQTT Sender block so I'd expect the clientID to be the same.  I'd expect the MQTT connection to be cleaned up after sending the first message and commencing to send the second message, but I guess this is not how it works internally?

Does this mean that it is currently not possible to send two different messages to a MQTT from within 1 Adapter without falling back to using multiple clientIds?

**Comment by thomaspj10** [comment]
Thank you for the input. The issue lies with the clientId. Having the same clientId accross multiple senders is not supported by the MQTT protocol and should not be done.
