### ISSUE TITLE
Scroll to top button in console isn't visible

### ISSUE THREAD

**Issue by Matthbo** [frankframework/frankframework#8022]
### Current Behavior

When scrolling down in the console, the scroll to top button in the sidebar is not visible at all, even though it exists and you _can_ click on it

### Expected Behavior

Scroll to top button should become visible when scrolling down and be hidden again when at the top

### Environment Information

**FF! 9.0.0-20241126.042327**: frank2example 
Running on **frank2example-frankframework-54bf4cf58c-k2vhl** using **Apache Tomcat/10.1.33**
Java Version: **OpenJDK Runtime Environment (21.0.5+11-LTS)**
Heap size: **206.9 MiB**, total JVM memory: **245.0 MiB**
Free memory: **38.1 MiB**, max memory: **792.7 MiB**
Free disk space: **73.3 GiB**, total disk space: **146.1 GiB**

**Comment by nielsm5** [comment]
Fix opacity eventlistener in main.ts
