### ISSUE TITLE
Ladybug report generator always on

### ISSUE THREAD

**Issue by dirkjanp** [frankframework/frankframework#8028]
### Current Behavior

The ladybug reports are by default always on after a redeploy. Occurs in FF 8.1.1.
Does not occur when running FF 8.0.2.

In Application Constants `testtool.enabled=false` and also in System Properties (so property with same name is present twice).

### Expected Behavior

Ladybug reports turned off after deployment

### Environment Information

Any

### Steps To Reproduce

Deploy IbisOnCloud app with FF 8.1.1

**Comment by evandongen** [comment]
I don't think I really get it: on application startup, in `DeploymentSpecificsBeanPostProcessor` we set the debugger by using an `DebuggerStatusChangedEvent`. This event never gets handled by `org.frankframework.ladybug.LadybugDebugger#onApplicationEvent` and `org.frankframework.ladybug.IbisDebuggerAdvice#onApplicationEvent` (not available yet?). If I manually update the setting on the 'log settings' page, the event is handled by both the Debugger and the DebuggerAdvice, and the value is updated.

**Comment by evandongen** [comment]
8.1: https://github.com/frankframework/frankframework/pull/8048
8.2:
8.3:
9.0 / master: https://github.com/frankframework/frankframework/pull/8056
