### ISSUE TITLE
Disable or Hide page elements and buttons if the user is not allowed to access these

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#8051]
### Related Problem or Business Case

The user is able to see every button and form, even when they don't have access to this. 
This can be confusing because some people see a lot of testing tools when they don't need it. And when they try to use this, they get an (intended) 500 server error.

Pages are already hidden in courtesy of #3628, but to keep the PR readable, we only included the business logic and the authorization for whole pages.

### Describe the Feature

- [ ] Add `appHasAccessToLink` directive to page elements
- [ ] Check if navigation permissions can be lifted if there are some read-only elements
- [ ] Add `appHasAccessToLink` directive to buttons

### Collaboration with External Companies

No, community resolution only

### Anything else?

- [ ] We could maybe add an integration test to test this and to check if all endpoints are matching with the backend.

**Comment by Laurens-makel** [comment]
Just thinking out loud, what about disabling buttons and optionally showing tooltips such as "You need role A,B,C to be able do stop adapters"

**Comment by nielsm5** [comment]
There are so few buttons, I'm not sure if people will notice this, we'll have to see when we implement this.
Don't forget there is also a 'Security Roles Overview' section in 'Security Items':
![image](https://github.com/user-attachments/assets/91790903-8ab2-4a5a-9d26-e949abb5b660)
