### ISSUE TITLE
When using the "Back" button in a browser, the page gets stuck at the IAF_Util tab

### ISSUE THREAD

**Issue by philipsens** [frankframework/frankframework#8068]
### Current Behavior

When visiting a page with tabs where `?configuration=` is missing, `?configuration=IAF_Util` will be set. This will also happen when going back, breaking the build-in back button of the browser.

### Expected Behavior

Going back to the previous page. (Not same URL without `?configuration=IAF_Util`)

### Environment Information

Local development on master

### Steps To Reproduce

1. Go to Monitors page
2. Press "Back"

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by Matthbo** [comment]
This happens because the console keeps track of the latest used tab or uses the first one when it cant find a previous state, this messes with when going back through browser history since the state isn't going back to a previous state
