### ISSUE TITLE
Allow named authenticator to protect the Frank!Console

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#8111]
### Related Problem or Business Case

I create this issue based on a conversation with Vincent de Gans, right after lunch.

### Describe the Feature

The properties you need to configure authentication are confusing. As explained in the manual, https://frank-manual.readthedocs.io/en/latest/advancedDevelopment/authorization/httpInterfaces.html, you need to define a named authenticator to protect servlets. You have `application.security.http.authenticators=<list of names>` and you define each authenticator by setting properties `application.security.http.authenticators.<name>.*`. On the other hand, you define properties `application.security.console.authentication.*` to protect the Frank!Console. This difference is confusing. It would be more clear when you could protect the console with a named authenticator, for example `application.security.console.authentication.authenticator=<name of authenticator>`.

### Collaboration with External Companies

No, community resolution only

**Comment by jjansenvr** [comment]
@nielsm5 please close issue when you add the "Won't Fix" label
