### ISSUE TITLE
Enhance use of icons in Frank console

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#865]
**Reporter**
Gerrit

**Is your feature request related to a problem? Please describe.**
When I am using the framework, I often have a lot of browser tabs open, and then I easily get lost in the tabs related to the framework

**Describe the solution you'd like**
I would like to have every menu sub-item (e.g. like 'larva', 'ladybug') to have an individual graphical icon, that is also reappears in the title of the browser tab.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by philipsens** [comment]
I don't think that the proposed solution is the best way to solve the issue. Needing a lot of tabs is an UX issue in itself, I think. The issue could be turned around to: "I need too many tabs to use the console".
I also don't think the icons are individually recognizable, they are more of a visual support while scanning menu items.
